### ISSUE TITLE
Ubuntu Training Ml-Agent

### ISSUE THREAD

**Issue by Gaduu** [Unity-Technologies/ml-agents#1009]
Hi,

Quick question regarding training the agent using Ubuntu. This is the first time I've tried doing this on Linux, installed Unity and opened up the example environments (3D Ball to be precise), all the brains work just fine apart from the external brain. Whenever I set the brain to external Unity freezes (even without running learn.py script), tried building the project and running training this way, with and without graphics (--no-graphics) and I get an error "Unity Environment” is not responding.".

Anyone tried training the agents on Ubuntu (elementary os) and have encountered similar error?

Cheers,

**Comment by mmattar** [comment]
Hi @Gaduu - a few clarification questions:
- What version of Unity are you using?
- To verify, the internal brain works well, but the moment you switch to external, Unity freezes?

**Comment by Gaduu** [comment]
Unity version - Unity-2018.1.6f1 (As anything above is bugged in terms of resizing of windows)
It doesn't freeze when I switch to the brain right away, but when the brain is set to External and I press play. Pretty much as with the build version, so whenever I run the learn.py and point it to the build, the project starts and freezes instantly, the error occurs and the learn.py throws timeout error

**Comment by Gaduu** [comment]
Up

**Comment by cjm715** [comment]
I think this is problem is related to issue #929  but I don't understand the solution given.

**Comment by mmattar** [comment]
Thanks for raising this @Gaduu and @cjm715. We haven't tested ML-Agents on Ubuntu, but it does [work on AWS](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md).

Can you share with us the Unity console log so we can better investigate what may be causing the issue? As @cjm715 pointed this is likely due to #929, but more broadly due to the use of gRPC.

In the short-term, you can get training working using our [Docker set-up](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Docker.md), it won't enable you to leverage in-editor training though.

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if there are any additional follow-ups.

**Comment by mantoone** [comment]
I'm having the exact same problem. 

After changing the brain type to external and pressing play Unity freezes. Also standalone build freezes. I don't think running in docker helps in my case, because I cannot even build a working standalone environment. 
 
This is what I see:
<img width="915" alt="screen shot 2018-11-01 at 21 30 07" src="https://user-images.githubusercontent.com/5957589/47874899-b6f92800-de1d-11e8-9b09-d266bac4c393.png">

I'm running Ubuntu 18.04
Running Unity 2018.2.7f1 Personal (64-bit)

**Comment by mantoone** [comment]
> I had this problem too, and I successfully fixed it by uninstalling completely tensorflow, protobuf, ml-agents and gym-unity, and then installing all of it again, with --no-cache-dir, just to be sure (For Tensorflow, I installed the version 1.7.0). Note that I had to do it in my global python3 environment, not a virtualenv.
> 
> Once done, my editor was able to at least start the game, but seemed frozen once again. However, this was only due to my python code not sending actions to the environment. Once that changed, the editor started working perfectly while training.
> 
> I am still unable to train from built executables, but that seems to be another problem altogether.
> 
> Using
> 
> * Ubuntu 18.04
> * Unity 2018.2.7f1
> 
> I hope it can help you

Thanks for commenting! I was using a virtualenv as well. I'll test your solution and report back.

**Comment by DerKapellmeister** [comment]
I also have exactly the same issue. As soon as i select "external brain" and click play in the editor Unity completely freezes.
I tried @4rzael recommendation but without any luck
      
Using:
- macOS 10.14
- Unity 2018.2.17f1
