### ISSUE TITLE
pip3 install . doesn't work

### ISSUE THREAD

**Issue by KehanDream** [Unity-Technologies/ml-agents#1013]
I am trying to use pip3 install . under the python subdirectory but it gives me error message like that:
Could not find a version that satisfies the requirement tensorflow==1.7.1 (from unityagents==0.4.0) (from versions: )
No matching distribution found for tensorflow==1.7.1 (from unityagents==0.4.0)

I think it's probably because tensorflow currently provides 1.8.0 version instead of 1.7.1
Do you have any clue how to solve this problem?

**Comment by KehanDream** [comment]
I think it's probably because tensorflow currently provides 1.8.0 version instead of 1.7.1

**Comment by clankill3r** [comment]
@KehanDream Do you know what it was? I have the same problem.

**Comment by c43892** [comment]
it might because of your python version is not 3.6, it's 3.7 ?
my question is I didn't find any 'python' subfolder in the repository....

**Comment by chriselion** [comment]
@c43892 This question is over a year old; the repo structure has changed a lot since then. You should follow the instructions here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md#install-python-and-mlagents-package or here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md#installing-for-development and open a new issue if you have further problems.
