### ISSUE TITLE
Question : Difference between SetReward() and AddReward() ? 

### ISSUE THREAD

**Issue by shrirammoni** [Unity-Technologies/ml-agents#1024]
I am confused between SetReward() and AddReward() methods. Can someone help me out ?

**Comment by phatal** [comment]
As I understand AddReward increases current episode reward value and SetReward replace current episode value with value which you set as parameters when call SetReward method. 

For example if you current value is 5 and you call AddReward(1.0f) then reward will be 6.0 and if you call SetReward(1.0)  then reward will be 1.0

**Comment by vincentpierre** [comment]
@phatal Yes you are right. AddReward and SetReward modify the reward for the __current step__ (not the episode). Since these methods can be called multiple times per step, AddReward increments the value and SetReward modifies it directly.

**Comment by shrirammoni** [comment]
Hey @phatal  @vincentpierre  thanks for the help.

**Comment by shrirammoni** [comment]
Where to use` SetReward()` and where to use `AddReward()` method. Any examples ?

**Comment by vincentpierre** [comment]
[BalanceBall](https://github.com/Unity-Technologies/ml-agents/blob/master/unity-environment/Assets/ML-Agents/Examples/3DBall/Scripts/Ball3DAgent.cs) uses set reward because you want to have 0.1 reward no matter the amount of actions between decisions (decision frequency is set to 5, if you used AddReward, you would get 0.5 rewards per decision) In [CrawlerAgent](https://github.com/Unity-Technologies/ml-agents/blob/master/unity-environment/Assets/ML-Agents/Examples/Crawler/Scripts/CrawlerAgent.cs) you use AddReward because the crawler is rewarded for multiple things at each step (Where it is facing, it's speed ...)

**Comment by shrirammoni** [comment]
@vincentpierre  thanks for the help.

**Comment by xiaomaogy** [comment]
We've updated the doc that explain this in more details. https://github.com/Unity-Technologies/ml-agents/pull/1996
