### ISSUE TITLE
Can I set frames to skip based on the number of Update(not FixedUpdate) calls?

### ISSUE THREAD

**Issue by matsui-k20xx** [Unity-Technologies/ml-agents#104]
Hi, 
I want to set the number of Update to skip between AgentStep calls. Are there any efficient and reliable ways to do this?

**Comment by matsui-k20xx** [comment]
I changed FixedUpdate into Update in Academy. it seems working in python. Are there any other ways to do this safely?

**Comment by dora-gt** [comment]
`frameToSkip` in `Academy` ?

**Comment by dora-gt** [comment]
Is it merely `Target Frame Rate` ?

**Comment by vincentpierre** [comment]
The reason the AgentStep is done in FixedUpdate is because Update is not called reliably and do not happen in sync with physics. If your game does not use any physics, changing to Update could work, but I cannot guarantee it. If you want to be able to stop the steps during inference for a certain amount of time rather that a certain amount of fixed updates, you could look into `Wait Time` in the academy, which will make the agent wait for `Wait Time` at inference between each of his actions.

**Comment by matsui-k20xx** [comment]
Thank you for the reply. The reason I want to call AgentStep in Update is that my game is heavily based on Unity's Animator which is evaluated after every Update. So I will try to keep the ratio of FixedUpdate to Update nearly the same by adjusting the parameters of Academy, or maybe quit using Unity's pysics.

**Comment by vincentpierre** [comment]
To go the other way around, would it be possible to select Update Mode `Animated Physics` in the Animator Component?

**Comment by matsui-k20xx** [comment]
I didn't know that. It's helpful information!
