### ISSUE TITLE
Add action/observation every episode (Not every step)

### ISSUE THREAD

**Issue by antoine-doolaeghe** [Unity-Technologies/ml-agents#1066]
Hi everyone, I have been working on learning environment like the ML Agent example where the all actions are taken at every steps. I would like now to experiment with actions taken at every episode. For example, allowing the Crawler environment to generate a number of legs for the length of an episode, the number would be according to an action and compare the observation for each episodes instead of steps ?  Would this be possible ? 
Thank you
Antoine

**Comment by unityjeffrey** [comment]
hi @antoine-doolaeghe - thank you for your note.  I wanted to make sure I understood your scenario.  Instead of taking an observation / action each step, you want to collect observations each step, but take only the action at the end of the episode and collect the observation after the action at the end of each episode?

**Comment by antoine-doolaeghe** [comment]
Hi @unityjeffrey, thanks a lot for your reply. I am looking at collecting observations each step, but taking only the action at the end of the episode. For example on the Crawler example, I am trying to set up a second brain that defines a new rotation of each legs(around the body) per episode. I would like the brain to learn the 'optimised' rotation of legs.
