### ISSUE TITLE
Getting a numpy import error when numpy is installed

### ISSUE THREAD

**Issue by AndreTInfante** [Unity-Technologies/ml-agents#11]

**Comment by AndreTInfante** [comment]
Sorry, accidentally submitted before filling this out. I'm getting this error: 
![image](https://user-images.githubusercontent.com/3455125/30677984-5ade5bba-9e4c-11e7-9bff-739930e5f5ff.png)

when I try to run the ball balancing example project. I initially thought it was because I had the wrong version of numpy installed, but I reverted to 1.11.0, and it's still throwing the issue. Any thoughts on what might be up?

**Comment by AndreTInfante** [comment]
For reference:

>(tensorflowcpu) C:\Users\aticp\Downloads\ml-agents-master\ml-agents-master\python>pip3 install numpy
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\aticp\appdata\local\programs\python\python35\lib\site-packages

**Comment by vincentpierre** [comment]
I think there is something wrong with jupyter, not python.  
 * Is the Kernel of the Jupyter notebook set to Python3 or Python2 ?
 * Do you have multiple versions of Python installed ? If yes, jupyter must use the same python as pip.
 * What happens if you open Python3 from the command line and try to `import numpy`?
 * I think you are using a virtual environment called tensorflowcpu, are you sure you launched `jupyter notebook`from the same virtual environment ?   

Let us know if you find a solution, we are interested in knowing about this issue.

**Comment by AndreTInfante** [comment]
The tensorflowcpu environment is made using anaconda, to try to simplify things. I definitely launched jupyter notebook from within the same environment. I'll try setting things up outside of anaconda as well, and see if I have any more luck.

mporting numpy in python seems to work (or at least throws no errors.  

The kernel.json file shows 

> {
 "language": "python",
 "display_name": "Python 3",
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ]
}

Which looks correct to me, since I'm trying to use python 3.5. Anything else I should check?

Thanks!

**Comment by AndreTInfante** [comment]
Ah, interesting! Doing it outside of anaconda seems to have fixed the issue. Weird. Thank you for your help!
