### ISSUE TITLE
Basic demo: AgentAction confuse me

### ISSUE THREAD

**Issue by evehal** [Unity-Technologies/ml-agents#1104]
In basic demo,VectorActionSize set to 2,but in agent script, only 1 action used:for direction.
After changing VectorActionSize to 1,In training process,mean of reward always at 0.08.
so why VectorActionSize have to be 2 if we only use 1 action.
thank you for help

**Comment by vincentpierre** [comment]
Hi, 
In discrete control, the number of actions signifies the range of values the action can take. See [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#discrete-action-space) for more info.
In the case of basic there are 2 actions : Move left and move right. I hope this helps.

**Comment by jo3w4rd** [comment]
When you use the **Discrete** Action Space, the meaning of the state space is quite different then when you use the **Continuous** Action Space. In a discrete space, the size of the state space is the number of discrete values that the action can have. (Although the Action values are passed to the  AgentAction() function in an array, this is just so that the function signature that you need to implement for an Agent is the same in both cases. In the discrete case, the vectorAction argument is always an array with one element.)

For the Basic example, the action space has a size of 2 because there are two things that the agent can do. It can move left (action 0) or it can move right (action 1). In the AgentAction(), action 0 is interpreted as a negative direction, while action 1 is interpreted as a positive direction:

                 var movement = (int)vectorAction[0];	    
		int direction = 0;
	    
		switch (movement)
		{
		    case 0:
		        direction = -1;
		        break;
		    case 1:
		        direction = 1;
		        break;
		}

Given the way the rewards are set up, a mean reward of 0.08 means that the agent is only finding the smaller target. Check that the agent is actually able to move to the right. (You can make the training window bigger in the Academy's Training settings to make it easier to see what the training agent is doing.
