### ISSUE TITLE
Reloading the scene without destroying your Communicator object

### ISSUE THREAD

**Issue by Szpaqn** [Unity-Technologies/ml-agents#1122]
Hi,
I am trying to find a way to reset my scene without losing the connection to learn.py script.

I am trying to use ML-Agents in my game.
The goal is to jump a ball through an obstacle.
I set up the environment. Configured the Agent, Academy, and the Brain.
The game works in brains Player and Heuristic modes.
But when I try to use the External mode with the learn.py script, the game plays only once and then the script stops with a message:

> Traceback (most recent call last):
  File "learn.py", line 84, in <module>
    tc.start_learning()
  File "D:\Unity_ml_agetn\ml-agents\python\unitytrainers\trainer_controller.py", line 258, in start_learning
    text_action=take_action_text)
  File "D:\Unity_ml_agetn\ml-agents\python\unityagents\environment.py", line 377, in step
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: 'BendyRoadBrain'

I think it's because I reset the scene after every 'death' of the ball.
In Agent:

     public override void AgentReset()
        {
            if( killed )
            {
            killed = false;
            GameMaster.Instance.InitialiseAfterKill();
            }
        }

In GameMaster.cs:
  
    public void InitialiseAfterKill()
          {
                IsInGameplay = false;
                Time.timeScale = 0;
                // Application.LoadLevel(Application.loadedLevel);
                UnityEngine.SceneManagement.SceneManager.LoadScene(UnityEngine.SceneManagement.SceneManager.GetActiveScene().buildIndex);
           }

 @jo3w4rd wrote in [Isue711](https://github.com/Unity-Technologies/ml-agents/issues/711) that resetting the scene breaks the connection, but does it always? Is there a way?

My Agent script is added to this message.
[BallAgent.zip](https://github.com/Unity-Technologies/ml-agents/files/2318129/BallAgent.zip)

**Comment by jo3w4rd** [comment]
Resetting the scene breaks the connection because the connection is maintained by an object in the scene that you are reloading (so the original connection object is destroyed and a new created).

Instead of reloading the entire scene, you could just reposition/reset individual GameObjects. This seems the simplest way, especially for a simple scene.

Otherwise, you **might** be able to put the Academy in a parent scene and the things you need to reset into a child scene, and then additively load the child scene into the parent (instead of replacing it as with a normal scene load):

    SceneManager.LoadScene(index, LoadSceneMode.Additive);

You will still need to [re-attach the brains to the agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#instantiating-an-agent-at-runtime).

I haven't tried this second approach and so can't guarantee it will work. You might just run into different troubles further in.

**Comment by harperj** [comment]
It looks like you've found a way to solve the problem you were having and this issue has become inactive, so I'm going to close it.  Please feel free to reopen if you have any additional issues.
