### ISSUE TITLE
Please Add Visual Output Action, Image Output!

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#1185]
Would it be possible to add Image output to Action Space? (Inverse CNN). This will open up many other possibilities such as implementing GAN (Generative Network). This should also be GPU accelerated.

**Comment by awjuliani** [comment]
HI @superjayman,

This is an interesting feature. We currently don't support this because we have focused on the typical RL scenarios. However, it is possible to modify the communication protocol directly to add this to your project, if you are interested. Additionally, we will be expanding the API in the future to support more arbitrary observation and action spaces, and image actions will be one such new possibility.

**Comment by awjuliani** [comment]
Hi @superjayman 

In v0.8 we will support custom observations and actions, which will make this possible. As such I am closing the issue for now.

**Comment by superjayman** [comment]
Can you please elaborate on this feature?

**Comment by unityjeffrey** [comment]
Hi @superjayman - see link to documentation:

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Creating-Custom-Protobuf-Messages.md
