### ISSUE TITLE
GPU Memory Remains Unallocated

### ISSUE THREAD

**Issue by sam-ulrich1** [Unity-Technologies/ml-agents#1238]
This isn't urgent because I have ample memory available but I did notice that since updating to v.0.5 my 11GB of GPU Memory is unused in training. On v.0.4 I was using all of the GPU Memory so I'm not sure what changed. I checked the Trainer_Controller and found that I should still be able to use all of the memory:
`        config = tf.ConfigProto()
        config.gpu_options.allow_growth = True`

However I am using less than 1GB (which is unrelated to tensorflow) on my GPU. I was wondering if anyone has encountered this issue because I have not been able to find any indication as to why it happens.

**Comment by awjuliani** [comment]
Hi @sam-ulrich1,

There are two possible causes for this. The first is that since our setup file specifies the CPU version of tensorflow, it is somehow defaulting to that. In that case, you would expect to see no GPU memory usage. The other is indeed because of the line you mention ere. A few users were having issues with the default TF GPU memory allocation pattern, so we added this to by default only allocate as much as is necessary. Since our PPO algorithm isn't optimized to take advantage of a GPU fully (as opposed to a fully supervised learning algorithm), this shouldn't be a problem in most cases. 

Are you experiencing a degradation in performance as well?

**Comment by sam-ulrich1** [comment]
First off, thanks for the help!

I don't think it has had much of an effect on performance. I only noticed it because my system's memory usage was more than double what it used to be. I just checked and from what I can tell the only tensorflow i have on my computer is tensorflow_gpu 1.7.1. I'll mess around with it tonight and let you know if I find anything.

Thanks again!

**Comment by sam-ulrich1** [comment]
I got it working again. I just manually allocated the memory from the GPU instead of using the growth option. Thanks!
