### ISSUE TITLE
retroactively reward update

### ISSUE THREAD

**Issue by surferau** [Unity-Technologies/ml-agents#1239]
Say we have connect4 game with 2 agents. Agent1 makes a bad move but we dont know that yet, so we dont update a reward here. Agent2 makes a winning move because of the agent1 mistake and gets a "1" reward. This way agent learns to make 4 chips in row as fast as possible but never learns how to prevent other agent from winning. Can we update a reward somehow for the past episode or Is there another way around this? Of course i could write a check after each move "is this move allows other player to win" but this approach will fail with more complex games.

So far i could not train agents to play any turn based board game because of this problem.

**Comment by vincentpierre** [comment]
Maybe if you penalize the agent for losing, the agent will learn to avoid doing moves that put it in a configuration in which it will lose pieces. This should all happen in the same episode, an episode ends when the game is won or lost, since all the games are independent the reward should not carry between episodes. I am sorry for the late reply, I am closing this issue now, feel free to reopen if you want to continue this conversation.
