### ISSUE TITLE
How To Load Model to continue with training

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/ml-agents#138]
Hello,

after training is finished and I want to train the saved model for some more time I set LoadModel to True and click Restart & Run All in the kernel option but instead of starting another session I get:

```
Loading Model...
INFO:tensorflow:Restoring parameters from ./models/ppo\model-500001.cptk
INFO:tensorflow:Restoring parameters from ./models/ppo\model-500001.cptk
Saved Model
INFO:tensorflow:Restoring parameters from ./models/ppo\model-500001.cptk
INFO:tensorflow:Restoring parameters from ./models/ppo\model-500001.cptk
INFO:tensorflow:Froze 4 variables.
INFO:tensorflow:Froze 4 variables.
Converted 4 variables to const ops.
```

**Comment by marwie** [comment]
Ok sorry I just looked at the Closed Issues and found the answer (Increae Max Steps)
I'm not sure if this is common and a no brainer for people in ML (I'm not obviously :)) but I expected MaxSteps to relate to the newly started training process. 

A followup question might be: is there a way to automatically stop the training once the model reaches a certain mean reward ? Maybe some sort of callback so I can (automatically) act upon it finishing :)

**Comment by marwie** [comment]
I also haven't really figured out yet how curriculum learning really works - maybe someone could answer these questions:

- When does the Academy reset (I understand Max Steps but when I just start my training the academy resets after the (one) agent resets and after that takes some time
- How do I control if the environment should change (or the difficulty of the task): do I need to get the current training mean reward in code?

**Comment by vincentpierre** [comment]
@marwie  
**I expected MaxSteps to relate to the newly started training process:** `MaxSteps` in ppo refers to the total amount of steps to be realized. Loading a model means you continue training where it stoped which means the number of steps realized is reloaded and cannot exceed the `MaxStep`. It is a choice we made in order to have models you can compare (it is not fair to compare models based of their number of steps if one of them had a head start)   
**About curriculum learning** We are working on additional features of curriculum learning that will allow you to modify reset parameters based of the training progress when using ppo. In the mean time, here is how reset parameters work. Reset parameters allow you to change the way your environment works directly from python without having to create a new build.     
 * The academy resets when the academy `done` flag is set to true or when the maximum number of academy steps has been reached. 
 * An academy has a set of reset parameters which default values you can set in the academy inspector. These values can be accessed with `academy.resetParameters['nameOfPArameter']` and can be modified via python.
 * In python, when you call `env.reset()`, you can pass an argument called `config` that takes a dictionary of strings to floats. This configuration must correspond to the new values of the reset parameters you wish to send.  

By modifying the reset parameters, you can make your game progressively harder to play from python. I hope this helps.

**Comment by marwie** [comment]
@vincentpierre 

**MaxSteps**: ok that makes absolute sense

**Curriculum Learning**: so for example I could check the training progress in a python script and modify my reset parameters based on these? 

Thanks for taking the time to explain

**Comment by awjuliani** [comment]
Hi @marwie,

Yes, that would be the manual way to handle curriculum learning. We will be providing a more automated version where a curriculum can be defined in a json file, and then carried out based on certain criteria. This is included in the `development` branch, if you would like to test it out. Documentation is available here: https://github.com/Unity-Technologies/ml-agents/blob/development/docs/curriculum.md

**Comment by stevenluda** [comment]
Is it possible to continue training on a different machine?

**Comment by trinhthanhtrung** [comment]
Dear all,

I have a different question related to Load Model to continue training.

I trained my model for 1.2M steps. After looking at the data, I continued training by loading the old model, with no changes to the environment, rewarding and training parameters (except for only max step increased to 3M).

Here is the statistics on my TensorBoard
[TensorBoard statistics](https://lh3.googleusercontent.com/q6hWUqEHrtK3pFjYiCCs0mdaF-Ybv3zBfT6sA21hlr3tyax7LXXBKGdydZoEfYptQIr85XFm9Hi6ZRDGwzuqBq4l2skgBlVhDww-y2RSOfRjZcm_b_EGI5k7CnN0yrI3qF1mMjByjZbDXnrhUhW76eHAGhUJrf4PfHjw7RfxNpeeZroUT8ivEp59k4Iq4knm8ivMoNHtDI-cdV-C-XjmCGM4DG6dDjYb067_Mf2s6rs7oKKEoxPQFpcfwFkXhlrnadZc3n2FsMuy3M9ZU3eR5kQaQvrBZ5W5aFuCNfW2Gea-eqJOE96egeMd2-D1wJCFH1CNA_L4-a7utkrIQe9b8W8u7HB0Xt0vtbOsJIi2p5t-wKyCswHgs7fLS0lhIoINFZDYRh1xa9RtOCHdbWw3v7P5b5NGqEsMlEpnXOGxmPvHgm3uIH_TGN2zi0mdbAB1siKmVTXt4CU2Pvd_QZVssiqESlFYI0KGEsWacCo947W_NjEr0pLSCiiVqRVY5zrbUC5h6m6cmMIEW80uxUmcq9nsxDqAL1BqFrC4yGccsHxUqrD8wNhYbU2tBX4CiQfqsbCEdTjU3aaRuRBuCuVdpIHNhZ-xxcQv4_WyHAL_uuo7LrOa1IRpy-SzgHUGJ15WjbDMrqDgzvNXsSbaWawN84QofL7b5UNa=w1555-h959-no)

What I am wondering is Losses, Policy Reward etc. at 1.2Mth step, as if it is a completely new training session with using only updated weights. I just want to ask if what I think is true, and will the result (as in agent behaviour) be any different to if I train the agent from the start with 3M as max step?
