### ISSUE TITLE
Only one brain on gym environment

### ISSUE THREAD

**Issue by 4rzael** [Unity-Technologies/ml-agents#1388]
Hello,

I am trying to figure out which tool I should use for a machine learning application.
In my case, I want to perform reinforcement learning on multi-agent scenarios, with both collaboration and competition taking place. (basically, the equivalent of a football game, with each agent playing a player)

I am therefore considering Unity ml-agents, as it gives me a full 3D environment with physics, etc...

However, when looking at the unity-gym part (because I would like to have my environment running as a gym environment), the readme says I can only have 1 brain per environment.

Does it make it impossible to train multiple different agents in a multi-agent environment ? And if so, where does this limitation come from ?

**Comment by awjuliani** [comment]
Hi @4rzael,

It is possible to have multiple agents within a unity gym, it is just that they must all be connected to the same brain (meaning they must have the same observation and action space). We provide this restriction because there is no gym wrapper which I am aware of that does not also provide this restriction. When designing the wrapper, the intention was to maintain as much compatability with pre-existing gyms as possible. It is always the case that information from multiple brains can be exposed using our own `UnityEnvironment` python API.

**Comment by awjuliani** [comment]
Hi @4rzael,

It is possible to have multiple agents within a unity gym, it is just that they must all be connected to the same brain (meaning they must have the same observation and action space). We provide this restriction because there is no gym wrapper which I am aware of that does not also provide this restriction. When designing the wrapper, the intention was to maintain as much compatibility with pre-existing gyms as possible. It is always the case that information from multiple brains can be exposed using our own `UnityEnvironment` python API.

**Comment by 4rzael** [comment]
Thanks a lot for clarifying that !

**Comment by Usmaniatech** [comment]
In order to train multiple agents having the same brain, Is there any restriction related discrete and continuous observations. Do gym supports both type of observations.
