### ISSUE TITLE
Having problem when try to use external data input

### ISSUE THREAD

**Issue by matonglidewazi** [Unity-Technologies/ml-agents#141]
Hi there,

I'm trying to send the sensor data from OpenBCI, while found some problem,

I steam the data to a file path, e.g. @C/a.txt,

In fact I can't directly read it, since the OpenBCI program is steaming,

So I make a copy out, to @C/a_copy.txt,

Of course I've the code like find the path and rewrite the path,

Everything is find until I build **a version with external brain**,

I mean it works nice inside unity brain/player and a built version brain/player,

When I try to train the model, it simply report 2 error messages

'IOException: Sharing violation on path (followed by the path of original path)'
'IOException: Sharing violation on path (followed by the path of the copied file path)'

Anyone knows what's happening here?

**Comment by vincentpierre** [comment]
I am not sure I understand everything, but it seems the external brain and player brain behave differently, which should not be the case. I am not familiar with OpenBCI but it seems it generates a static txt file that you are trying to read from C#. The exception you get seems could be due to an attempt to open the file while it has not been properly closed.  
Did you modify any code? In some versions of ml-agents, `CollectStates` is not called when using a Player brain (because the player does not use the states at all). This could be a source or difference between external and player brain. I would recommend trying with an Heuristic Brain (with a random decision script) in order to debug the `CollectStates` method.  
Also, maybe try to put `Debug.Log()` messages every time you open, write, read and close the file. This will help you figure when and maybe why this error happens.  
I hope this helps.

**Comment by matonglidewazi** [comment]
@vincentpierre 

Yeah, thanks for yor advices,
The case is it takes me a day to realise that the problem doesn't relate to the ml-agent,
It's a System IO issue, and I solve it with "try {} catch(IOException) {}"

The Heuristic Brain is cool, better to test with player.

**Comment by awjuliani** [comment]
@matonglidewazi,

Glad you were able to get things working!
