### ISSUE TITLE
About Joint Drive Controller

### ISSUE THREAD

**Issue by tanakataiki4** [Unity-Technologies/ml-agents#1445]
https://github.com/Unity-Technologies/ml-agents/blob/d6dad11c773a8598540a8896d0d48b2489b222ae/UnitySDK/Assets/ML-Agents/Examples/Walker/Scripts/WalkerAgent.cs#L120

I want to know about unity joints configuration.
I assume this decides the joints forces and so on every time.
But I think it also works with constant strength so I want to test it.
and Is  it possible to avoid setting joint strength every time if it's constant value?
Or should I feed same strength every time?

**Comment by xiaomaogy** [comment]
@mmattar

**Comment by harperj** [comment]
If your strength is a constant, you could just keep them as constants and make no changes to them in the `AgentAction` method.  You'd want to also change the action space by modifying the Brain configuration.  You can see the [documentation on Brains](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Brains.md) for more on this.

I'm going to close this issue now since beyond basic information about ML-Agents we don't have the resources to support custom / modified environments.  Please feel free to reopen or create a new issue if you have any more trouble.
