### ISSUE TITLE
Suggestion in Heuristic Brain

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1487]
Hi,

@awjuliani , In my decision script, I needed to add an id to inform the agent requesting the action. I think that having the agent id in this script is of fundamental importance for us to be able to have greater control over a replay file for example.

```
public float[] Decide(  List<float> vectorObs,
                            List<Texture2D> visualObs,
                            float reward,
                            bool done,
                            List<float> memory,
                            int playerNumber)
```

I insert the playerNumber as my ID.

**Comment by vincentpierre** [comment]
Were you able to modify the code to have the result you expected ? You probably would have to modify [this code](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/CoreBrainHeuristic.cs#L61) to obtain the result needed. The reason we did not include the agentId in the Decide arguments is because none of the other brains use that information. The relevant past information about the agent should be stored in the memory of the agent. Taking a decision based on the identity of the agent is not in our framework.

**Comment by icaro56** [comment]
Thanks, I maybe will put a vector of the custom data in this point.  I need this information in the Heuristic Brain because depending on the agent's id and his scenario, I retrieve his next move from a replay file.

I use this Heuristic brain with specialist for Imitation Learning training.
