### ISSUE TITLE
One tick of action with deferred rewards. 

### ISSUE THREAD

**Issue by batu** [Unity-Technologies/ml-agents#150]
Sorry for the flurry of questions but here is another one.

Right now I am trying to make a "simple" model in which the agent learns to apply force to a rigid body to throw it a given target. Basically, the pseudocode is as follows:
```
if (!shot)
    rb.AddForce(new Vector3(act[0], act[1], act[2]), ForceMode.VelocityChange);
    shot = true;
```
The reward is given when the ball makes contact with the plane, based on how far it is. 

I could get the naive set up to learn. My intuition is that this set up has extremely sparse rewards. In essence, while the ball is in flight, the model is acting, yet, there is no change in the world state. When it gets the reward, I assume, it updates its belief based on the sum of the actions it took, which, mean severely reduces its ability to discern the salience of the first action. I am going to experiment with the reward discount rate to see if that changes anything.

Is it possible to block the agent from acting until it is rewarded, manually increasing the concentration of the salient rewards? 

I experimented with the skip frames and wait time fields but I don't think I achieved success. 

> `Frames` To Skip` Number of frames (or physics updates) to skip between steps. The agents will act at every frame but get new actions only at every step.

This explanation in "[Making a New Environment](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md)" isn't exactly clear to me.

Also, I apologize if my intuition of how PPO works is flawed, as I have not fully read the paper.

Cheers and enjoy life,
batu

**Comment by awjuliani** [comment]
Hi @batu,

`Frames To Skip` works by only asking the neural network for input every n frames, instead of every frame. `AgentStep()` is still run every frame, but uses a cached decision from the last time the network was called, instead of calling the network if it isn't an `nth` frame. Hopefully that makes it more clear. I will edit the document to reflect that.

As for sparsity of reward, even though your network takes "meaningless" actions after it has thrown the object, it should be able to eventually learn to assign credit to the important moment where there is contact with the object. This would be dependent on your state representation though. You will want to ensure information about the direction and location of all the relevant objects are in `CollectState()`. 

Another possibility is to give the reward not when the target it hit, but when the agent applies the force by "fast forwarding" to calculate whether the force applied will be sufficient to hit the target. That way there isn't a temporal delay.
