### ISSUE TITLE
How to check GPU works properly.

### ISSUE THREAD

**Issue by RavenLeeANU** [Unity-Technologies/ml-agents#1502]
Hi guys,
I installed cuda and cudnn for tensorflow gpu version. But I do not know how to check if it works or just work as CPU version. Can someone give me some hints for that? thanks..

**Comment by vincentpierre** [comment]
According to this [thread](https://github.com/tensorflow/tensorflow/issues/22472) you can run this command to see if there is a GPU to use. 
```python
tf.test.is_gpu_available()
```

**Comment by oddEventHorizon** [comment]
I used this command with result: TRUE, however when I train my GFX card load is not going up at all and training is quite slow. Cpu is like 50-100% busy.

![image](https://user-images.githubusercontent.com/19377008/50539575-f70d2a80-0b82-11e9-923c-996ae9b76926.png)

**Comment by MarcoMeter** [comment]
ML-Agents is not optimized for GPU usage yet.

In general, Reinforcement Learning is hard to be optimized for GPUs, because especially on-policy algorithms do not sample enough data to efficiently use a GPU. So most of the time, you are better of with a CPU for now. Highly scaled up systems like IMPALA or OpenAI Five take advantage of a GPU.
