### ISSUE TITLE
Help on creating 'Chess' AI using Adversarial Self-Play Training Model

### ISSUE THREAD

**Issue by amrittb** [Unity-Technologies/ml-agents#152]
I am somewhat beginner in Reinforcement Learning. I have gone through the Tennis demo in the project, but I am still confused on how to create an environment to train the agent to play 'Chess'.

I have thought of several things on how to approach this problem.

**State**: A 8x8x12 3D Tensor to track the position of each chess piece in the game. *Discrete state?*

![Chess Tensor](http://blueanalysis.com/iulianserban/wp-content/uploads/2015/03/3D_Chess_Cube_Illustrated-300x195.png?raw=true "Chess board state tensor")

**Action**: Confused on how to implement actions. Since the state is discrete(*Isn't it?*), how should this be handled?

**Reward**: Positive reward for taking opponent's piece and Negative reward for the piece being taken. The reward for each piece are:
* Pawn: 0.1
* Knight: 0.3
* Bishop: 0.3
* Rook: 0.5
* Queen: 0.9

> How can I implement **infinity** chess piece value for King? Also, How do I maintain combinational reward that may exceed 1.0, as I am directly converting chess points to reward as in [Chess Piece points](https://chess.stackexchange.com/questions/2409/how-many-points-is-each-chess-piece-worth)?

**Episode**: Each episode should start with correct piece starting position and end with either a draw or with a checkmate (or some other form of game ending criteria),

> Since there would be two agents for white and black, how would the agent train each agent? Would the learned data be shared between the agents?

I don't have a clear picture of what I am doing and what should be done. Any guides are appreciated.

> Would the inbuilt PPO algorithm implementation work fine with this kind of problem?

**Comment by awjuliani** [comment]
Hi @amrittb,

This is an interesting problem, and hopefully I can provide some insight. As for state, I think you want continuous. You will be using binary values, but it will not be a "one-of-n" input but rather an "n" input, if that makes sense. Your idea for a 3D tensor is interesting as well. You would have to somewhat modify our existing PPO model code to properly take that tensor as input, but that is relatively simple to do as well.

Instead of infinity reward, the king can simply be 1.0, and the other pieces could be scaled appropriately. 

If setting up this problem using ML-Agents, you could create two agents which each share a single brain, similar to the Tennis example. PPO should be able to accommodate this. If you look at AlphaGo or other adversarial training scenarios, it is often the case that an agent is trained against a fixed older copy of itself. This is something we currently don't support in our PPO, but will be adding in the future.

Hope these answers are helpful.

**Comment by kwea123** [comment]
Yeah I agree with @awjuliani, your state space should be continuous. Although there is only a finite number of states - which makes you want to treat it as discrete -, but if you treat it as a discrete space, you will have to count that number of states, and make each state a one-hot vector (what @awjuliani meant by "one-of-n" input, where n is the number of all possible states, amazingly large I reckon). So by making the state **continuous**, you can treat it as a binary vector of length n, where n is only your tensor's size = 8*8*12. To make the representation more complete, I think you should also add another value representing the current player's color, for example 1 for black and -1 for white, so that makes the state size 8*8*12+1.
In AlphaGo's paper they added some past board representations as well, but you won't need them if you want to keep things simple.

You could set the king's reward to about 100 (a large number), or scale down other pieces' rewards. I personally don't experience any training difficulties with very large rewards (I have like reward=100 or so along with reward = -0.01ish and the agent still learns without any problem), but I use my own implementation of RL algorithms, so I don't know if their PPO works well or not in this scenario. In my opinion, the ratio between different rewards, positive and negative ones, is way more important that the actual values. Your agent might only learn with a correct ratio of the rewards.

Lastly I think you can use the same NN to train the agents, with the state representation containing the color of the current player, as my suggestion in the first paragraph.

**Comment by amrittb** [comment]
Thanks for the reply @awjuliani and @kwea123. Your comments provided me with great insights to approach this problem. I do have a problem with how to invoke a certain action? Should I randomly select a piece to move to a random possible position? I am having a hard time wrapping my head around the algorithm.

**Comment by amrittb** [comment]
Hello, @awjuliani @kwea123 @unityjeffrey How do I define the action space for this particular problem? Since the action that can be taken for each state in Chess can be very large and discrete, how could I make it continuous? Also, can I modify the python code to take in List of floats as the state instead of just floats?

**Comment by amrittb** [comment]
I was thinking to represent the action space as continuous space with length 8x8x2 where the first 64 represents the current piece to be selected to move and the next 64 represents the next position to move. Since the action space is continuous, the action space would treat the whole 128 floats as a single unit generating the values which tend to make only one action have high probability. Also, Is it possible to only generate valid actions from the network?

**Comment by LeoTheCatMeow** [comment]
I am experiencing a similar problem with a custom chess like game made by myself. I only have 37 locations or spaces on one map, but my game has multiple maps with varying number of available spots. To make matters worse, the units I made can perform 4 types of actions, including switching, moving, attacking, and casting skills. I have absolute 0 idea right now on how to define the action space. I've thought about doing a 37 + 4 + 37 action space. But I don't know how much that would affect the learning speed. And my actions also have different target search algorithms. It seems simply impossible for ml-agents to learn the differences.

**Comment by awjuliani** [comment]
Hi all,

A discrete action space would be necessary here, since only one action could be taken at a time. It is also the case that for a game like Chess a planning algorithm may be necessary, since learning using model-free RL (like the PPO algorithm included here( is likely to be much more difficult.
