### ISSUE TITLE
what about Space Size and Stacked Vectors of Vector Observation?

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/ml-agents#1522]
Hello!
For example,3Dball scene.
the  Observation function is
 public override void CollectObservations()
    {
        AddVectorObs(gameObject.transform.rotation.z);
        AddVectorObs(gameObject.transform.rotation.x);
        AddVectorObs((ball.transform.position - gameObject.transform.position));
        AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity);
        SetTextObs("Testing " + gameObject.GetInstanceID());
    }

 I just see 4 Vectors above,but the brain show the space size is 8 and stacked vectors is 3 ,so the sum is 24.
How to get this result? 
Thanks in advance!

**Comment by yumianhuli2** [comment]
Answer is gameObject has 2 states,  ball.transform.position - gameObject.transform.position has 3 states, and ball velocity has 3 states. Right?
so What is the meaning of  Stacked Vectors?

**Comment by 13Flo** [comment]
@yumianhuli2 This page is an "issue tracker". You should ask your question [on the forum](https://forum.unity.com/threads/ml-agents.541390/) instead.

**Comment by awjuliani** [comment]
Hi @yumianhuli2 

The stacked vectors takes whatever you action observation space is and allows you to feed a history of those observations into the brain. This can capture information about how observations change over time, which may be useful in some instances.

**Comment by yumianhuli2** [comment]
> Hi @yumianhuli2
> 
> The stacked vectors takes whatever you action observation space is and allows you to feed a history of those observations into the brain. This can capture information about how observations change over time, which may be useful in some instances.

Thank U for your reply! You mean  Stacked Vectors is 3 allow me to feed a history observations into brain and
maybe useful. I change Stacked Vectors to 1 in 3dball demo scene that Console showed  UnityAgentsException: Incompatible shapes: [12,8] vs. [24],So My question is why I need select 3 with Stacked Vectors item in 3dball project?
Thank U very much!

**Comment by yumianhuli2** [comment]
> > Hi @yumianhuli2
> > The stacked vectors takes whatever you action observation space is and allows you to feed a history of those observations into the brain. This can capture information about how observations change over time, which may be useful in some instances.
> 
> Thank U for your reply! You mean Stacked Vectors is 3 allow me to feed a history observations into brain and
> maybe useful. I change Stacked Vectors to 1 in 3dball demo scene that Console showed UnityAgentsException: Incompatible shapes: [12,8] vs. [24],So My question is why I have to select 3 with Stacked Vectors item in 3dball project?
> Thank U very much!

**Comment by awjuliani** [comment]
Hi @yumianhuli2 

If a model was trained with stacked vector 3, then you need to use stacked vector 3 for inference as well. If you want to change this value, you will need to retrain the model.

**Comment by yumianhuli2** [comment]
> Hi @yumianhuli2
> 
> If a model was trained with stacked vector 3, then you need to use stacked vector 3 for inference as well. If you want to change this value, you will need to retrain the model.

ok,got it,thank U!But may you tell me the effect of stacked vector through some paper or docs or something else,it will be very useful! Thank U!

**Comment by nanxintin** [comment]
Hi @yumianhuli2 , could you tell me where the Observation function of each environment is ? I want to figure out the detailed information of  Vector Observation space.
Thanks.

**Comment by MarcoMeter** [comment]
@nanxintin 
For each agent implementation, there is the  CollectObservations() function, which comprises the to be collected state information of the agents.

@yumianhuli2 
I'll give you an example:
Imagine the game of pong where an agent controls a paddle.
Its observation space comprises the image of the current state of the game.
So now there is one dilemma apparent:
How does the agent know in which direction the paddles and the ball are moving?
The solution to this dilemma is to add the past image to the observation space as well.
So this temporal correlation states the change in position of the ball and the paddles.

**Comment by nanxintin** [comment]
@MarcoMeter Thanks a lot.
In the  ml-agents/UnitySDK/Assets/ML-Agents/Examples/Soccer/Scripts/AgentSoccer.cs, the  detectableObjects = new string[] { "ball", "redGoal", "blueGoal", "wall", "redAgent", "blueAgent" }.
The agent need to detect 7 possible object types as presented in the docs, but there are only 6 types in the code. If the agent is red, the "blueAgent" in the detectableObjects has 2 objects. Am I right?  
In addition, could you tell me the meanings of the following two codes:
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 1f, 0f)).
The rayAngles has only 7 values. Does these mean the total local 14 ray casts ?

**Comment by MarcoMeter** [comment]
Concerning the detectable objects: the 7th detectable object type indicates that something unknown got detected (meaning everything else instead of the specified detectable objects).

**Comment by nanxintin** [comment]
@MarcoMeter Each team has two agents. If a ray detects "blueAgent", how can we konw this agent is a striker or a goalie ? And if a ray detects two opponent agents, how to define the distance in the 8th dimension?

**Comment by cratkid** [comment]
In the equal parts measures system 0-9 infinitely in every where. With my
understanding if super position I see a way my bank to make even the
thought of values to be just less relative than particle's being concussion
odserver has a soild that matters. Fear is all you got, a gun to a head and
value is meaning to the dallor.  I know we are better humans than this why
is hate all that I see, I am hatefull too, step to fear I am a little
psych. To challenge all that is taught, see what it really Worth fear is
near money hear. I like too see it burn (or each numberical spot in Bank.
$#####.##. Has a change of 4-9 every faction of a second so all can have to
chance of main scent of amount that's their. To me all forms of represent I
on of anything is wrong or never equal to value, then too get all of haman
to agree. I know better I will not help your broken system.

Maybe too work together on this, I all ready know how best to start. Agree
to disagree, neither wrong but not right. The only thing that throughout s
balance is is a lie!

Patrick's Thompson
" * Atryx. TommyGun
     Eztin Rizon Wav*"
 P.S. with the removal of $$$atin stress levels would fall a medication a
drugs consumption would not be such a dilemma.

On Jan 7, 2019 3:31 AM, "Kun Shao" <notifications@github.com> wrote:

@MarcoMeter <https://github.com/MarcoMeter> Thanks a lot.
In the
ml-agents/UnitySDK/Assets/ML-Agents/Examples/Soccer/Scripts/AgentSoccer.cs,
the detectableObjects = new string[] { "ball", "redGoal", "blueGoal",
"wall", "redAgent", "blueAgent" }.
The agent need to detect 7 possible object types as presented in the docs,
but there are only 6 types in the code. If the agent is red, the
"blueAgent" in the detectableObjects has 2 objects. Am I right?
In addition, could you tell me the meanings of the following two codes:
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0f,
0f));
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 1f,
0f)).
The rayAngles has only 7 values. Does these mean the total local 14 ray
casts ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Unity-Technologies/ml-agents/issues/1522#issuecomment-451874222>,
or mute the thread

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
