### ISSUE TITLE
cd C:\Downloads\ml-agents\ml-agents cannot find path specified 

### ISSUE THREAD

**Issue by IamJustaguy1** [Unity-Technologies/ml-agents#1531]
it seems that as of now while i try to install ml agents the documentation tells me to put in the command  
cd C:\Downloads\ml-agents\ml-agents cannot find path specified  i am very new to this kind of setup and i would appreciate any help thank you in advanced

**Comment by oddEventHorizon** [comment]
this issue is probably not in the scope of this forum to be honest as it is not ML Agents related but you should probably read a little bit about terminal commands.

Basically cd stand for change directory. 

Let's say you are in C:\Downloads
if you wanted to go to ml-agents\ml-agents you can do:

1) go to the directory one command at a time so:

cd ml-agents (Now you are in C:\downloads\ml-agents)
cd ml-agents (Now you are in C:\downloads\ml-agents\ml-agents)

Now you are in C:\Downloads\ml-agents\ml-agents

or you could go there with one command:

2)

cd ml-agents\ml-agents and you are in the same place as you were after first method. 

cd .. moves you one directory up.

dir shows you files and directories that are in the folder you are at.

Most likely your problem is that you are trying to reach folder that does not exists in your computer. 
Tutorial doesn't know where you downloaded the ml agents, you have to know it yourself. 

If you want to get to your ml agents from terminal you need to know where it's placed on your disk. Then use command prompt to get there.

**Comment by unityjeffrey** [comment]
hi @IamJustaguy1 it seems that this was solved so will close out the ticket. @oddEventHorizon  - thank you so much for assisting!
