### ISSUE TITLE
Best approach for rigidbody finding target in (zero gravity) 3D space?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1577]
Hi! I'm struggling to meaningfully train a simple test case:

1. A no-gravity rigidbody agent (space ship ShipAgent) is surrounded by random Reward spheres in an empty space
2. It locks on to the closest one (doing an OverlapSphere for the non-ship layer)
3. It then tries to collect it by moving towards it via AddForce (the Rewards are triggers informing the agent upon triggerEnter, which is all confirmed to work)

![ship](https://user-images.githubusercontent.com/1754503/50831702-0bec7980-134c-11e9-932d-a9900d540515.png)

I've tried a variety of approaches:
- Observing target's relative position to space ship
- Giving rewards when it collects it
- With or without (usually with): Observing space ship's rigidbody velocity
- With or without: Giving positive rewards when it's nearer since last (indicated by a green debug line)
- With or without: Giving negative rewards when it's going further (indicated by a red debug line)
- With or without: Punishing when it leaves the area
- With or without: Using max steps for the agent, or the academy
- With or without: Observing ship's absolute position
- With or without: Observing target's absolute position
- Using different vector observation stack sizes, usually 1, but I also tried e.g. 3
- Using AddForce mode ForceMode.Force, or ForceMode.VelocityChange
- Various increase or decrease multipliers for the force strength
- Hunting multiple Rewards in succession in one session, or using Done() after the first collect to shuffle the Rewards again
- etc.

... yet nothing seems to show good results after e.g. 100,000 or many more steps. I've been using the default trainer_config settings (except mostly using more 100k steps instead of 50k, though I also tried the latter).

I've uploaded my full project to http://anyland.com/Space.zip

What could be optimized, what am I doing wrong? Thanks!

**Comment by vincentpierre** [comment]
Hi, I am sorry to hear it does not work for you. I would recommend starting with fewer rewards, this way, the agent will not change target during training and it could help it get started. You need to increase the decision frequency of your agent, I would say between 5 and 10. You also need to normalize the observations between -1 and 1, for this problem, I would normalize the relative direction to target and add the distance as a side variable. Since your rewards are so sparse, I think you need a way to add some proxy rewards Start with bigger spheres or use reward when getting closer. MaxStep should be a lot higher than it is right now (I set it to 20000)
Having multiple agents each after their own rewards would also speed up training.

I made some experiments and I enclosed the files I modified, the agents seem to be doing something after 30000 steps with the default config of config/trainer_config.yaml.
[Assets.zip](https://github.com/Unity-Technologies/ml-agents/files/2737778/Assets.zip)

**Comment by JPhilipp** [comment]
Thank you very much for this helpful advice!

**Comment by JPhilipp** [comment]
Works like a charm!

**Comment by JPhilipp** [comment]
If I may ask, could you please elaborate on the meaning of this line, both why you chose magnitude, as well as why 50? Thank you!

`AddVectorObs(relativeTargetPosition.magnitude / 50);`

**Comment by vincentpierre** [comment]
I added the magnitude because if I use just the normalized relativeTargetPosition, the agent does not have information on the distance to target. I divide it by 50 because `relativeTargetPosition.magnitude` values should be around this value. I am trying to keep the vector observations to values between -1 and 1. There are other functions that achieve the same thing but I think using a linear function is simplest.
