### ISSUE TITLE
Questions about multi brain and reading learned data.

### ISSUE THREAD

**Issue by Felix-Koch** [Unity-Technologies/ml-agents#161]
Hi, at first i will say that you are making great work here.

What i have made:
A arena with a floor and 4 walls, two of them are goals.
A ball that must find the right way towards the right goal.
This works all fine (Unity -> Python -> Unity)

What i want to make:
- Make multiple arena with different obstacles and different brains that make the same and match the differnt leaning.
- Put more balls with different tasks inside the same arena and look how they learn.
- Maybe if i have enough time, the both with differnet algorithm.

My Questions:
- Im not the best with python, is the Multi-agent branch usebil for multi brain usige or has it known issuses the needs to be observed?
- Is a way implemented to make graphs from the learning data?
(Maybe inside "raw_graph_def.bp" if yes how can it be opened?)
- You are interestet at the results when im finished?

**Comment by vincentpierre** [comment]
@Felix-Koch Sounds like a great project. It is possible to connect multiple agents to a single brain : like in the Balance ball example. For example : if an agent must go right and the other go left, you can specify this in the state so that even if their objectives are different, they can still be trained with the same brain. If the tasks are too different, you will have to use multiple brains.   
The multi agent branch is a development branch, a lot of things are not optimized and the functionalities are very limited for now. Still, I was able to use it in a very simple scenario and if you end up using it, any feedback will be appreciated. When training with the dev-multi (notebook only btw) you will end up with a single graph for all the brains, you will have to specify the graph scope to specify which brain you are using in the internal brain. We are super interested in projects made with ML-Agents, please keep us updated!

**Comment by vladimiroster** [comment]
@Felix-Koch, we're closing this issue. Feel free to reopen if you still have any questions.
