### ISSUE TITLE
how do you represent the interaction between characters with this plugin?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#163]
How could the relationship between agents be represented with this plugin? In other words, how do you represent the interaction between characters?

Thanks.

**Comment by awjuliani** [comment]
Hi @icaro56,

Are you interested in communication between agents? Or by interaction do you mean simply actions which can effect other agents? In both cases, you can reserve a sub-set of the state space for the message or action of other agents, in order to allow the agent to take it into account when making its own decisions. Let me know if that answers your question!

**Comment by icaro56** [comment]
I think that's it. I'll ask my advisor if that's it.

Thanks

**Comment by icaro56** [comment]
That's it. Thank you @awjuliani .
