### ISSUE TITLE
After training

### ISSUE THREAD

**Issue by Semih67** [Unity-Technologies/ml-agents#1651]
When I have finished training and I want to build the game, I have to set the brain type to internal and do I have to set the max steps to 0? Because I don't want to reset the game all 30 secs.

**Comment by MarcoMeter** [comment]
You can set max steps to 0 in order to avoid the reset of the environment.
In ml-agents 0.5 and before, you would use internal.
In ml-agents 0.6 you create a LearningBrain, reference the trained bytes file and then uncheck broadcasting on the Academy for the learning brain.

**Comment by harperj** [comment]
Agree with what @MarcoMeter said :)

If you want to change the behavior like "reset on done" or "reset on max step" you'd currently need to change your scene.

I'm going to close this issue for now since I think the question has been answered.  Please feel free to reopen or open a new issue if you have any further questions / issues.
