### ISSUE TITLE
Can we use Animations as Actions?

### ISSUE THREAD

**Issue by georgecarbune** [Unity-Technologies/ml-agents#1655]
Hey!
Is possible to use as discrete actions animations instead of instant actions ( rotate/transform/etc ). Also the rewards to be distributed at the end of the animation?
Thanks in advice!
PS: this is more like a question, not really an issue.

**Comment by MarcoMeter** [comment]
The implementation of ml-agents should be flexible enough to suit your use-case.
Just simply setup discrete actions, make some switch or if-statement and set the parameters of the Animator accordingly.

Given animations, you can add events, which could be received by the agent to trigger reward signals.

There might be many more ways or even more intuitive ones.

**Comment by harperj** [comment]
Agreed-- you should be able to add the reward whenever your animation has completed.  You may want to consider whether these animations are taking multiple timesteps during which you don't want to provide additional actions to the agent though.  In this case you may want to use something like [On Demand Decisions](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#on-demand-decision-making) so that you only request a new action once the animation is completed and the reward has been provided.

I think between my answer and @MarcoMeter's this should answer your question so I'll close this issue.  Feel free to reopen or start a new issue if you have any trouble.
