### ISSUE TITLE
experience  buffer mechanism

### ISSUE THREAD

**Issue by ishaybe** [Unity-Technologies/ml-agents#1661]
can you explain how the experience buffer that you implemented for PPO is working.
1. how it gets filled ?
2. when it getting empty/reset?
3. what is the connection between buffer_size and the learning procedure?
4. how the episode ending is connect to it?
5. if the episode ends before filling the buffer is learning is done?
thanks in advance

**Comment by ishaybe** [comment]
any help?

**Comment by harperj** [comment]
Hi @ishaybe -- unfortunately the best reference for this is to browse the source code at this time.  At a high level we fill the buffer on each environment step and reset each agent's buffer when the episode is complete or the time horizon is reached.  Since PPO is on-policy, we clear the buffer from previous after each policy update.

For reference you can check out the `add_experiences` and `process_experiences` methods in `PPOTrainer`: https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/ppo/trainer.py#L177

I'm going to close this since it's not a specific issue with ML-Agents but I hope it helps with your exploration.
