### ISSUE TITLE
Multiscene environment

### ISSUE THREAD

**Issue by cyrilibrahim** [Unity-Technologies/ml-agents#1666]
Hi, 

Is there a way to have an environment build with multiple scenes to be able to have one executable for all the scenes ?

The reason is that there's a lot of shared elements between the environments. 

Thanks a lot !

**Comment by harperj** [comment]
Hi @cyrilibrahim -- the current ML-Agents flow would make this difficult since everything related to communication with the trainer is happening within the scene.  This isn't something we've tested but would welcome you sharing any experience you have working on this.

We don't have this on our roadmap at this time, but I'll share with the team since this seems like something worth considering.

**Comment by unityjeffrey** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.

**Comment by lukemadera** [comment]
Hi @unityjeffrey I am running into an issue that I think is related to having multiple scenes. I just opened this: https://github.com/Unity-Technologies/ml-agents/issues/3371
If I have multiple scenes, should I have 1 academy per scene, or 1 total for all scenes? If 1 total, how do I properly destroy an agent (when the scene unloads with that agent in it) so the Academy knows to stop trying to reference it?
