### ISSUE TITLE
how to train more than one brains in one env

### ISSUE THREAD

**Issue by vxgu86** [Unity-Technologies/ml-agents#1671]
how to train more than one brains in one env？
for example，an agent with four friend agent,but with different brains。
is there any examples for this situation?

**Comment by harperj** [comment]
You can check out the [Soccer example environment](https://github.com/Unity-Technologies/ml-agents/tree/master/UnitySDK/Assets/ML-Agents/Examples/Soccer) for an example of multiple brains in a single environment.

I'm going to close this issue since the example environment should give sufficient info.  Please feel free to reopen or create an additional issue if you run into problems.
