### ISSUE TITLE
UnityEnvironmentException : Unity environment took too long to respond.

### ISSUE THREAD

**Issue by anktplwl91** [Unity-Technologies/ml-agents#17]
Hello, I am running 3d_ball example on Jupyter notebook on Windows 10 machine. The training function stops in between with the following exception.
![screenshot-2017-9-21 ppo](https://user-images.githubusercontent.com/13707940/30693358-cb010b04-9eec-11e7-8af2-edafb1a7b3d5.png)

**Comment by eagleEggs** [comment]
Does the game open in a new window, and do you get prompted to allow the Unity app to accept incoming communications? Also, I'm assuming you didn't change any of the Brain configuration in the scene beforehand,

**Comment by awjuliani** [comment]
Hi @anktplwl91, 

As @eagleEggs mentioned, you may be getting this error because you are attempting to launch an environment which doesn't have a Brain set to external within it. In order to use the python api, your environment needs at least one brain to be set to "external." https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball#building-unity-environment. Please let me know if that works for you.

**Comment by anktplwl91** [comment]
I changed the value of socket.settimeout(30) to socket.settimeout(60) and that seems to have solved the problem.

**Comment by vincentpierre** [comment]
@anktplwl91 You should not need to change the `socket.settimeout(30)` line. This just defines how long python will wait for the Unity Environment to respond in seconds. If the Unity environment did not respond after 30 seconds, there is little hope it will respond after a minute.
