### ISSUE TITLE
Discrete actions in continuous control

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#170]
Hello everybody,

I'm working on a pretty simple environment where a cannon (agent) has to shoot comets in order to get not hit. Two actions are available: rotate (continuous) and shoot (discrete). The agent is rewarded for destroying comets (+1) and punished for getting hit (-1). The agent's inputs rely on multiple raycasts which sense the distance to comets (picture below). Also the agent knows its current rotation. The rays are affected by the agent's rotation.

![inputs](https://user-images.githubusercontent.com/6996955/33841327-b7246ea6-de97-11e7-90bd-02a5765cd467.png)

So far I'm treating both actions continuously. Well, all of them could be discrete, but there are scenarios which likely encounter the usage of discrete and continuous actions. For example imagine an agent controlling a computer mouse. The mouse movement is obviously continuous but a mouse click is discrete.

This is what the implementation looks like:

```
        // External control
        if(brain.brainType.Equals(BrainType.External))
        {
            // Agent's rotation
            float zRotation = Mathf.Clamp(action[0], -5, 5);
            transform.Rotate(new Vector3(0, 0, zRotation));

            // Shoot
            float shootAction = Mathf.Clamp(action[1], 0, 1);
            if(shootAction <= 0.8f)
            {
                // Don't shoot
            }
            else if(shootAction > 0.8f)
            {
                Shoot();
            }
        }
```

As suggested by the docs, I'm clamping the outputs. I don't like the solution above somehow. How would you guys try to solve this problem?

I could imagine to let two agents control the cannon. One is in charge of the rotation and another one does the discrete shooting.

**Comment by awjuliani** [comment]
Hi @MarcoMeter,

The mixing of discrete and continuous is something that is technically possible, but would require a relatively large reworking of our current PPO implementation. The issue being that they are represented as two different kinds of distributions within the neural network. For a problem like yours, I actually think you may have the most success using discrete control, and having three actions (rotate left, rotate right, and shoot). If you need more fine-tuned rotation, then you could add multiple rotation intensities. You could also have mixed rotate-left-and-shoot type actions. In most cases discrete action problems will be easier to solve, since they represent a simpler underlying distribution to model.

**Comment by MarcoMeter** [comment]
The purpose of the cannon environment is to provide a low scale example concerning discrete plus continuous control.

I'll give the multi-agent approach a try.
