### ISSUE TITLE
How can I use the custom parameters in Academy.cs?

### ISSUE THREAD

**Issue by qqadssp** [Unity-Technologies/ml-agents#1707]
In academy.cs I can set some parameters using 'Reset Parameters', but how can I use it? 

For example, I want to set the position of the agent according to those parameters, but I don't know how to get it in agent.cs, and there is not example code.

If anyone know how to do it, please tell me, thanks so much!

**Comment by MarcoMeter** [comment]
Any Academy object has the public field "resetParameters". So your agent has to get a reference to its academy in order to access that field.

There are numerous solutions to let your agent class get a reference to the academy. The most intuitive one is referencing via the inspector:

- Create a member field in your agent class:

```
public YourAcademy academy;

or

[SerializedField]
private YourAcademy academy;
```

"SerializedField" or public will make your Academy field visible in the inspector on the agent.

- The next step is to drag and drop the academy into this new property field of your agent's GameObject.

**Comment by awjuliani** [comment]
Hi @qqadssp,

As @MarcoMeter mentioned, you can use reset parameters. For an example of this, see our `GridWorld` environment. Here is the line where we read the parameter and use it to set the size of the grid: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/GridWorld/Scripts/GridAcademy.cs#L35

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
