### ISSUE TITLE
PPO for single agent training or multi-agent training?

### ISSUE THREAD

**Issue by vxgu86** [Unity-Technologies/ml-agents#1717]
After seeing PPO on OpenAI, I got a question, is PPO born for single agent training or multi-agent training? 
In unity, it's trained at the same time even with different agents, is there any interaction between different agents with different BRAINS?

**Comment by TashaSkyUp** [comment]
In my experience ppo works well with multi agent training... Have the brain
attached to multiple agents in multiple situations so that it can learn to
generalize.. If that is what your looking for.

As far as brain to brain communication? There is nothing built-in for this
but you might be able to create it in a variety of ways depending on your
desired outcome.

**Comment by awjuliani** [comment]
Hi @vxgu86 

While PPO is not optimized specifically for multi-agent learning, it is possible to use it to train multi-agents scenarios, assuming the agents do not interact too much in a critical way.

As for how agents can interact, that is up to the creator of the environment. For example, it is possible for agents to send messages to one another, or to change the environment for other agents. For a simple example of this, see our `BananaCollector` environment, in which agents can freeze each other.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.

**Comment by YuhangSong** [comment]
Self-play and other techniques can address non-stationary learning to some degree. See our implementations https://sites.google.com/view/arena-home/home
