### ISSUE TITLE
Std of Reward always 0

### ISSUE THREAD

**Issue by rafvasq** [Unity-Technologies/ml-agents#1814]
Wondering why training always outputs a standard deviation of 0.000. Maybe I don't understand what it is well enough (the spread around the mean reward?), I assume that since the mean reward is clearly varying, std should be something other than zero? Why could this be?

```
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 19000. Mean Reward: -57.270. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 20000. Mean Reward: -80.738. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 21000. Mean Reward: -63.218. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 22000. Mean Reward: -39.685. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 23000. Mean Reward: -38.835. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 24000. No episode was completed since last summary. Training.
INFO:mlagents.trainers: PPOTest-0: NewLearner: Step: 25000. Mean Reward: -28.323. Std of Reward: 0.000. Training.
```

**Comment by harperj** [comment]
Hi @rafvasq -- yes, it's the spread around the mean reward for the episodes within the steps since the last printed summary.  I noticed you had no episode completed between step 23000-24000 here.  This makes me think you may only have at most a single episode happening within each 1000 steps.  In that case, it would make sense that the standard deviation is zero.

**Comment by rafvasq** [comment]
That makes sense! Thanks for the help.
