### ISSUE TITLE
Fixed Random Policy

### ISSUE THREAD

**Issue by JaAlSaDev** [Unity-Technologies/ml-agents#1831]
I’m a Computer Science student at King Abdulaziz University, and I’m testing the training modes of ML-Agents as part of my senior project.  I created a competitive plus cooperative multiagent training scenario, where a team of learning agents must learn how to defeat a group of heuristic agents. The learning agents have the same brain. I want to train the learning agents using different training techniques and compare the results via TensorBoard. Here is what my environment looks like:

![image](https://user-images.githubusercontent.com/46474223/54490535-8fd05e00-48c7-11e9-92a1-4927d775003a.png)

I read in your reference paper that you compared the performance of different training techniques for the sample environments, and I’d like to know how Fixed Random Policy was implemented. Do I ignore the values in vectorAction and use a random number generator? Do I change the values of the hyperparameters? I want to keep the learning agents' action random while recording the cumulative reward.

![image](https://user-images.githubusercontent.com/46474223/54490564-ec337d80-48c7-11e9-8dc4-3e6e3c31e4ec.png)

**Comment by ervteng** [comment]
Hi @JaAlSaDev, this is a fantastic project and I'd be very interested in how it turns out. As for your question about random decisions, you can use a Heuristic Brain. Normally, you'd either have a Learning Brain (ties to Python) or a PlayerBrain. If you look in the 3DBall example, there is a "3DBallHeuristic" brain that uses the RandomDecision.cs script (https://github.com/Unity-Technologies/ml-agents/UnitySDK/Assets/ML-Agents/Examples/SharedAssets/Scripts/RandomDecision.cs) to make random decisions. However, this will run in-game but not connect to the Python side of things. You could log the reward using Debug.Log or showing it on the screen. 

If you still want to use the Python side of the code, I would just replace AgentAction() with a random number generator, and ignore the vector action, as you suggested earlier.

**Comment by JaAlSaDev** [comment]
Thank you for responding @ervteng ! I read the RandomDecision.cs file, and it covers part of what i need (randomization), but i still need to record everything and compare results via TensorBoard.

I guess confusing the brain by ignoring its output (vectorAction) and replacing its values with randomly generated values should do the trick for my senior project.

I included randomization as part of my project because:

1. I think of it as a worst case scenario (no learning happens), but the agents may make correct/incorrect decisions by accident, and i would like that to be recorded.
1. As starting point for comparison (how would the other techniques compare to purely random decisions).
