### ISSUE TITLE
BroadcastHub brain list resets upon build

### ISSUE THREAD

**Issue by joabim** [Unity-Technologies/ml-agents#1866]
When building or running custom scenes in the editor the brain list in `Academy.BroadcastHub` seems to reset in some situations (Unity version 2018.3.7f1 on linux). Current reproduction steps: add one LearningBrain and one HeuristicBrain to the BroadcastHub as well as check the `control` checkbox for the former. When pressing play or building, the list reverts to containing only the LearningBrain and the control checkbox is unchecked. 

Is this an expected fallback for any faulty script present in the MLAgents stack? There are no console exceptions and the `Editor.log` does not give any clues.

**Comment by awjuliani** [comment]
Hi @joabim 

Thanks for bringing this up. In our own tests we haven't run into this issue, but we will try to investigate it, as it definitely sounds like some kind of bug.

**Comment by vincentpierre** [comment]
I am unable to reproduce this bug. Maybe someone from the community can confirm if this is a consistent issue. I am wondering if this is because you are trying to edit the Hub while in Play Mode (Upon exiting Play Mode, all inspector properties are reset to what they were before entering Play Mode). Can you try to look at the debug inspector when adding brains to the hub ? (In the top left corner of the inspector next to the lock select debug instead of normal)

**Comment by joabim** [comment]
@vincentpierre I see your concern but I am not altering the Hub through the inspector whilst in play mode. The reason I noticed the issue was that `UnityEnvironment` indicated that no external brains were available on the python side even though at least one of them should have been a controllable LearningBrain. Interesting - when using the inspector in debug mode, the changes actually saved between builds. I still feel like something may be awry with my current Unity setup, but until I have more information you can close this issue for now. It feels like it may be related to https://github.com/Unity-Technologies/ml-agents/issues/1712 - the solution didn't work for me though.
