### ISSUE TITLE
BC offline training - Teacher agent doesn't move and training is very slow.

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1906]
I made a demo file and loaded and started training.

During the training, the teacher agent doesn't move because I use the player brain for the teacher agent.

Is this right way to train?

Also, the training speed is so slow compared to using the normal training.

I've seen some people have the same issue with me but I don't know they solved this problem or not.

https://github.com/Unity-Technologies/ml-agents/issues/1608

https://github.com/Unity-Technologies/ml-agents/issues/1561

https://github.com/Unity-Technologies/ml-agents/issues/1422

**Comment by awjuliani** [comment]
Hello @moonsh 

Currently the slow speed is because most of the time is spent updating the model, rather than moving in the environment. This is the expected behavior. As for the learning brain, this is not needed when using offline BC. Instead you should create a demonstration file beforehand and use that.

**Comment by moonsh** [comment]
@awjuliani Thank you.
