### ISSUE TITLE
Why do you make neural networks so complicated ?

### ISSUE THREAD

**Issue by rt974** [Unity-Technologies/ml-agents#1954]
You could just write a neural network library in compute shaders, and provide a few utility cs files to manipulate the neural network to your users.

What the hell is this workflow, with docker, python, gym, lol do you really expect me to use that.

Whats next? download gentoo and compile my os from scratch ? No thanks.

When you dont want to do something, just dont do anything, all this looks like redneck machine learning patch.

**Comment by harperj** [comment]
Hi @rt974 -- sorry to hear the ML-Agents workflow doesn't work for you. We use Python because of the wealth of tools for training NN models for deep RL (e.g. Tensorflow) which simply don't exist in C#.  We do provide support for executing our Tensorflow models via compute shaders if you'd like to deploy them after training.

We always welcome constructive feedback on how to improve ML-Agents, and welcome contributions from the community to improve it.  At this time the ML-Agents project is the best solution we have seen for training RL agents for Unity games. If you're focused on C#, you may want to look into using our C# SDK and developing your own training solution.

Since this issue isn't actionable, I'm going to close it -- but as I mentioned we welcome specific suggestions for improvement and contributions to improve the project.
