### ISSUE TITLE
v0.8 - Can't access brain parameters

### ISSUE THREAD

**Issue by louis030195** [Unity-Technologies/ml-agents#1969]
I had this issue migrating from 0.6 -> 0.8, tried with fresh project following new instructions, same error

![Peek 2019-04-22 18-44](https://user-images.githubusercontent.com/25003283/56512097-b325a300-652e-11e9-86d2-db740decd178.gif)

Ubuntu 18.04
Unity editor 2018.3.9f1
ml-agents 0.8

**Comment by vincentpierre** [comment]
Hi @louis030195 
I am not sure how the Ubuntu editor is different from the Mac and Windows editor. Are there any compilation errors showing in the console ? Have you tried restarting the editor? Are you able to access the Brain parameters on a new project / in a new Brain ?

**Comment by louis030195** [comment]
No error, and yes i tried with new project as i said, new brain etc
Even installed latest Linux editor 2019.1.0f2, still same ...

**Comment by vincentpierre** [comment]
I am not sure how I can help since I cannot reproduce this with my setup. I think this is a bug on the Linux Editor. Can you try the debug mode of the inspector ? In an inspector window, there is a button next to the lock on the top right corner. Here you can select `debug` and it will allow you to see hidden fields. 
I suspect there is an error in [this file](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Editor/BrainParametersDrawer.cs) can you commenting it all out ?

**Comment by louis030195** [comment]
I had this error at some point
`Socket: bind failed, error: Address already in use(98)`

But thanks, indeed debug mode works, not normal mode though

**Normal**
![Peek 2019-04-25 08-22](https://user-images.githubusercontent.com/25003283/56713911-71197e80-6733-11e9-8f15-7fcf1c83ee3f.gif)

**Debug**
![Peek 2019-04-25 08-23](https://user-images.githubusercontent.com/25003283/56713893-66f78000-6733-11e9-9b4b-8a29c9279224.gif)
