### ISSUE TITLE
mlagents.envs.exception.UnityEnvironmentException when num-envs >1

### ISSUE THREAD

**Issue by DannyFriky** [Unity-Technologies/ml-agents#1984]
Just updated to 0.8.1 version and i'm trying the new features, but when i tried to use more than 1 training environment i get that error:

> mlagents.envs.exception.UnityEnvironmentException: If the environment name is None, the worker-id must be 0 in order to connect with the Editor.

on every environment greater than 1.

I tried to find if i did something wrong when trying to train with more than 1 environment but didn't find anything.

I used :  ` mlagents-learn config/config.yaml --run-id=name --num-envs=2 --train` to train

Do I need to do something new to go from training with 1 environment to train with several?
I am practically new working with ml-agents and with some changes I am somewhat lost, thanks for the help

**Comment by ScriptBono** [comment]
To use the new feature I had to use an executable environment. Means you have to build the simulation first and when you start the training with the command you also have to specify `--env=YourEnv`. Hope this helps!

**Comment by DannyFriky** [comment]
hi, @ScriptBono, thanks for your help, but i need 1 executable for every environment that i want, or 1 regardless the nun-env?

**Comment by harperj** [comment]
Hi @DannyFriky -- yes, it looks like you're trying to train using the Unity Editor.  Since the `num-envs` argument needs to open multiple instances of your environment, it needs a build/executable to run.  So if you make a build of your game and point `mlagents-learn` to it using the `env` argument it should work correctly.

Hope this works for you.  On our end, I think it would be good to provide a more useful error message :-)

**Comment by DannyFriky** [comment]
it works with that, thank you very much
