### ISSUE TITLE
documentation + use clarification

### ISSUE THREAD

**Issue by sterlingcrispin** [Unity-Technologies/ml-agents#20]
I'm trying to implement my own agent and environment and I'm a little unclear about a few things:

The implementations of CollectState() for Ball3DAgent and TennisAgent both seem to be roughly normalizing the floats they are returning. Is this a requirement, or just a best practice? 

What's the range of values that can be expected from the float array **act** in AgentStep ?

MemorySize argument in the Brain, do you define it in the same way you do with the State and Actions ? If so where? Is that only for Heuristic brains?

**Comment by awjuliani** [comment]
Hi @sterlingcrispin,

Normalizing the state isn't necessarily a requirement, but does go a long way toward ensuring that the algorithm will train smoothly/reliably. I will add instructions to the wiki ensuring people are aware of that.

As the designer of the environment, you get control of what kinds of values you want to expect through act. There are some best practices though. If you are using continuous control, then you likely want to clip the act values if they are outside the range you expect for your agent. For example with your spider agent (which looks quite cool by the way), actions may correspond to the angles of the joints. You may want those to not exceed something like (-5, 5), or otherwise the agent will simply flail around. For discrete control it is a little easier, since you simply define number of possible actions, and the value of `act[0]` corresponds to the chosen action.  

MemorySize is used for recurrent networks which might have an LSTM cell that needs values to be carried over from one step to the next. It works the same way actions would. As long as the state that you provide to your agent tell it everything it needs to know to take good actions at that moment, then you shouldn't need memory.

Hope all of that is helpful as clarification. I will go through the wiki and make each of these points more clear. If you have additional questions, please don't hesitate to ask!

**Comment by sterlingcrispin** [comment]
Ah alright thanks!

So just to be sure, there's no centralized place to define the min and max act values because the network gives a random guess and its up to me as the developer to filter them in AgentStep?

**Comment by awjuliani** [comment]
Currently that is the case. It would be possible to provide an inspector interface for this, but in the case of dozens of actions, I expect it would get unruly to manually change each of those from a GUI. Definitely open to any suggestions or ideas though which would improve ease-of-use.

**Comment by sterlingcrispin** [comment]
@awjuliani I think just knowing that goes a long way, but in the future maybe a solution could be defining a class called Act that has Value , Min, Max properties to replace the current float array, and just changing them via code in the InitializeAgent() function
