### ISSUE TITLE
About evaluate and update method

### ISSUE THREAD

**Issue by seaswander** [Unity-Technologies/ml-agents#2010]
I found that evaluate and update methods are not called equally in different scenes. 
In 3DBallHard, 
Evaluate Count: 1001, Update Count: 0
Evaluate Count: 2001, Update Count: 30
Evaluate Count: 3001, Update Count: 60
...
In 3DBall,
Evaluate Count: 1001, Update Count: 0
Evaluate Count: 2001, Update Count: 3003
Evaluate Count: 3001, Update Count: 6003
...
Why is update called so differently? I noticed 3DBall uses curiosity and the other one doesn't. Is update called to update ICM inner model?
And how is advantage in buffer calculated?

**Comment by ervteng** [comment]
Hi @seaswander, neither 3DBall nor 3DBallHard requires curiosity - you can turn it off and 3DBall should still learn. The update count and evaluate count are probably differing because of the vastly different batch sizes for both of these. So for a fixed buffer size, one will perform many more (smaller) updates than the other. 

Where are you seeing this output? Is it on the ml-agents CLI?

**Comment by seaswander** [comment]
Thanks for your explanation. The output is a usage count I add to the code.
