### ISSUE TITLE
How can i limit training time using relative training time?

### ISSUE THREAD

**Issue by oseq** [Unity-Technologies/ml-agents#2019]
Hello guys i am doing some study on my agent i need to compare some training sesions.
I know i can limit my trainig time using max_setps parameter in config file. But is it possible to limit training not by setps but with training time duration.  For example if i want to train model only 30 minutes.

**Comment by roboserg** [comment]
You can do basic math by measuring how many seconds are in 100 steps and do the math from there.

**Comment by oseq** [comment]
Yeah, but time of 1 step is not constant and it depend on many configuration aspects. However o already came up with solution that is maybe not the best but it works, i measure the time on Unity side using unscaled time and call:
`  UnityEditor.EditorApplication.ExecuteMenuItem("Edit/Play");`

... when it extends maximum time.

**Comment by roboserg** [comment]
wait, how are steps not constant? They should be constant. An agent takes action every X steps. You can set max_steps = 100 and calculate how long with an episode take at maximum.

**Comment by oseq** [comment]
I mean that time of one step can vary between different training sessions due to different parameters of training i.e. decision interval.

**Comment by roboserg** [comment]
how do we know that for certain? I'd think the steps would be constant.

**Comment by oseq** [comment]
@roboserg i used to think same as you. I am analiysing training summaries for different training sessions using tensorboard. Changing some paramterers usualy makes relative small difference, but if you f.e. swtich between PPO and BD the difference is huge.

**Comment by ervteng** [comment]
Hi @oseq, you are right, training time could be vastly different depending on how fast samples are gathered from the Unity executable. BC is an entirely different beast as well, since it trains purely from .demo files and doesn't really use the Unity game for training. 

Since we now keep track of the time elapsed, you could add a check for time as well as max steps in `trainer.py` ([here](https://github.com/Unity-Technologies/ml-agents/blob/37d139af636e4a2351751fbf0f2fca5a9ed7457f/ml-agents/mlagents/trainers/trainer_controller.py#L215)). If you get it to work, we'd definitely welcome a PR!

**Comment by roboserg** [comment]
@ervteng Arent steps itself, constantly in time?

**Comment by harperj** [comment]
Thanks for submitting this request.  I’ve shared it with the team, so I’m going to close this issue for now.
