### ISSUE TITLE
Load model with curriculum

### ISSUE THREAD

**Issue by vkakerbeck** [Unity-Technologies/ml-agents#2070]
Hi,

I am training an agent with ppo and curriculum learning. Sometimes I have to stop the training and restart it at some later point in time by calling --train --load. This all works fine and the agent loads what it has already learned. The only problem is that it always starts back in lesson 0 after loading the model, even if the agent is already good enough to complete more difficult lessons. Is it possible to use --load and start back at the lesson where I left off?

Thanks for your help!

**Comment by ScriptBono** [comment]
Hi yes it is possible with the `--lesson=<n>` parameter.

**Comment by vkakerbeck** [comment]
Thank you for your fast reply! That is exactly what I was looking for but somehow it doesn't really seem to work for me yet. 
When I specify a higher lesson while loading, the model starts out with a bad performance again. If I start learning from lesson 0, the model also starts out with a worse performance (better than loading with higher lesson) and then improves very fast and catches up to the lesson it was in after a few epochs. 

Also when running inference on the saved model the performance seems to be a lot worse then what is displayed during training.  Do you have any idea where this problem could come from? I am not sure if it is a curriculum learning problem but I didn't have it before I used a curriculum (I also started using parallel environments so that could also be the cause maybe?)

**Comment by vincentpierre** [comment]
The performance being bad and then good again after a few summaries can be due to the way we reports the cumulative rewards. If the cumulative reward reaches the same level it was at before, I would not worry too much about that.

Inference performing differently than training can have multiple causes, usually, it is because the game is not the same at low and high time scales. The fact that you did not have it before you used curriculum is strange, it could be that the last lesson of the curriculum and the one you are doing inference with are not the same. (The reset parameters are different or the training did not go all the way to the last lesson)

**Comment by vkakerbeck** [comment]
Hi @vincentpierre,
thank you for your quick help and tips! After some more testing I figured out that the problem was originating from some parameters not being reset over the course of the curriculum so the agent would never actually train on some settings. I explained it in a bit more detail here https://github.com/Unity-Technologies/obstacle-tower-env/issues/98 but it seems not to be an issue with ml-agents itself since most of the parameters are reset correctly. Thank you!
