### ISSUE TITLE
[CustomProtobufMessages]make_for_win.bat does not work

### ISSUE THREAD

**Issue by Lights999** [Unity-Technologies/ml-agents#2103]
Hi, I've tried make_for_win.bat but it didn't work well.
There are two problems I've found:

1. Can not find `protoc`
Because it needs set path firstly

2. python3 didn't work 
Only command of `python` can be executed on my windows

**Comment by unityjeffrey** [comment]
hi @Lights999 - for #1 - can you comment a bit more here?  did you install the right prereq's listed [here](https://github.com/Unity-Technologies/ml-agents/tree/master/protobuf-definitions)?

for #2 - you can use python instead of python3, as long as your version of python is version 3.  If calling python uses version 2, then you need to install python version 3.

**Comment by Lights999** [comment]
I've installed protoc and by the doc of `Unity ML-Agents Protobuf Definitions` :
![image](https://user-images.githubusercontent.com/3608281/58845256-11f14700-86ad-11e9-9771-a925131087e7.png)

After run make_for_win.bat, it will stuck at line[24-25] and it said that `protoc` can not be found:
![image](https://user-images.githubusercontent.com/3608281/58845446-c0958780-86ad-11e9-8043-ee53af1c295f.png)


If I set path before run `protoc`, it will work well, like this below:
```
set ROOT_PATH=%~dp0
set GRPC_PATH=%ROOT_PATH%%COMPILER%
path=%path%;%GRPC_PATH%
```

I think other people will have the same problem.

**Comment by xiaomaogy** [comment]
Hi @Lights999 , the reason you can't  run protoc is because you didn't finish the setup in https://github.com/Unity-Technologies/ml-agents/tree/master/protobuf-definitions#installing-protobuf-compiler, protoc is the protobuf compiler.

**Comment by Lights999** [comment]
@xiaomaogy Thank you so much
