### ISSUE TITLE
Why do you use Multinomial distribution ?

### ISSUE THREAD

**Issue by odannis** [Unity-Technologies/ml-agents#2112]
Hi,

after using barracuda to obtain the output of the brain network (action_prob), the loop DecidedAction() calls multinomial.Eval(inputTensor, outputTensor) in the public void Apply(Tensor tensor, Dictionary<Agent, AgentInfo> agentInfo) of the public class DiscreteActionOutputApplier : TensorApplier.Applier.

Why are you using a multinomial distribution ? Why don't you just take the action with the biggest probability in the vector action_prob ?

Thank you for your answer

**Comment by harperj** [comment]
Hi @odannis -- this is because our PPO policy is stochastic.  The policy is intended to provide probabilities and be sampled according to those probabilities.  We could use the policy in a deterministic way (picking the highest prob as you suggest), but it wouldn't be a correct or optimal way to use the policy.  For one, having some randomness in the policy means we don't get stuck in some of the ways that traditional policies get stuck (e.g. getting stuck against the wall constantly moving forward with no chance of ever turning in a maze-type environment).

There are other reasons I won't get into here, but I hope this clears it up a bit.

**Comment by odannis** [comment]
Thank you for your response
