### ISSUE TITLE
Best way for agent to choose floats on a range.

### ISSUE THREAD

**Issue by elanrosen** [Unity-Technologies/ml-agents#221]
I understand that the agent generates floats, but I am finding trouble with how to program in the AgentStep for the agent to choose a float on a range of [-1, 1]. Similar to how you would get player input in the form of an axis. still learning this agent stuff

Thanks

**Comment by MarcoMeter** [comment]
Hey @elanrosen 
are you referring to discrete actions, continuous actions or the input space?

**Comment by elanrosen** [comment]
continuous actions

**Comment by MarcoMeter** [comment]
The float array, which is passed into the AgentStep() function represents the output from the neural net. Each element of that array is related to one action. Before executing actions, each output value should be clamped ([-1, +1] or [0, +1]). After that you can make use of it. For example for movement or rotations. You are not choosing the values yourself. The PPO model does it.

I hope this information is helpful, otherwise try to ask a more concrete question.

**Comment by rogangriffin** [comment]
I don't understand how clamping the values helps. In my case the values I am receiving in the actions are between -10 and 10. If I clamp to -1 to 1, I get extremely linear movement from my agents because their values are almost always only -1 and 1. If I want smooth motion I multiply by 0.1 instead of clamping.
Is there something I am missing about a benefit of clamping?

**Comment by rogangriffin** [comment]
I answered my own question. By not clamping rotation my agent was swinging back and forth trying to find the right rotation to face the target. As soon as I clamped the action value before applying it it could find the right orientation immediately without swinging back and forth.

**Comment by elanrosen** [comment]
@rogangriffin What was your code to clamp the floats?

**Comment by rogangriffin** [comment]
```
//Rotate y
float action_rotate = Mathf.Clamp(act[1], -1f, 1f);
transform.Rotate(0, action_rotate, 0, Space.Self);
```

**Comment by awjuliani** [comment]
As mentioned above, our PPO implementation outputs unbounded floating point numbers, to keep them in a desired range, the solution is to clamp them as described above.
