### ISSUE TITLE
Descriptions of action spaces and observation spaces for Crawler environment

### ISSUE THREAD

**Issue by adipandas** [Unity-Technologies/ml-agents#2246]
Do descriptions of Crawler environment's action spaces & observation spaces exist anywhere? 
If there are 8 links in total, which should make the action space of 8 dimensions. But the environment is describing it as 20-D. Even with the action space as 20-D vector that presumably maps to different body parts, but are these numbers torques, angles, etc.?
Same goes with the observation space - a brief description of what the 117 dimensions correspond to would be incredibly useful to know.

I only get the following description of the available Crawler environment from [this link](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#crawler)

> Set-up: A creature with 4 arms and 4 forearms.
Goal: The agents must move its body toward the goal direction without falling.
CrawlerStaticTarget - Goal direction is always forward.
CrawlerDynamicTarget- Goal direction is randomized.
Agents: The environment contains 3 agent linked to a single Brain.
Agent Reward Function (independent):
+0.03 times body velocity in the goal direction.
+0.01 times body direction alignment with goal direction.
Brains: One Brain with the following observation/action space.
Vector Observation space: 117 variables corresponding to position, rotation, velocity, and angular velocities of each limb plus the acceleration and angular acceleration of the body.
Vector Action space: (Continuous) Size of 20, corresponding to target rotations for joints.
Visual Observations: None.
Reset Parameters: None
Benchmark Mean Reward for CrawlerStaticTarget: 2000
Benchmark Mean Reward for CrawlerDynamicTarget: 400

Thank you for help in advance.

**Comment by unityjeffrey** [comment]
CC: @awjuliani

**Comment by awjuliani** [comment]
Hi @adipandas 

Please see the code here for a description of the observation space of Crawler: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/Crawler/Scripts/CrawlerAgent.cs#L106. 

See here for the action space: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/Crawler/Scripts/CrawlerAgent.cs#L186. 

The reason the sizes are so large is because in observations we are using position, rotation, velocity, and angular velocity information for each of the parts of the crawler. 

The action space corresponds to setting the target joint velocity and strength to each of the joints in the crawler.

The Walker agent uses a very similar system, and can be found here: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/Walker/Scripts/WalkerAgent.cs

**Comment by adipandas** [comment]
Hello @awjuliani 
Thank you for pointing me to the code.
I have used the nomenclature as below:

- L - Left
- R - Right
- B - Back
- F - Front
- Up - Upper
- Lo - Lower
- x, y, z - axis labels
- trot - target rotation angle
- T - torque

For the crawler action space vector, the following is the order of actions I understood:

```
[LB_Up_x_trot, LB_Up_y_trot,
RB_Up_x_trot, RB_Up_y_trot,
RF_Up_x_trot, RF_Up_y_trot,
LF_Up_x_trot, LF_Up_y_trot,
LB_Lo_x_trot,
RB_Lo_x_trot,
RF_Lo_x_trot,
LF_Lo_x_trot, 
LB_Up_T,
RB_Up_T,
RF_Up_T,
LF_Up_T,
LB_Lo_T,
RB_Lo_T,
RF_Lo_T,
LF_Lo_T]
```

Please correct me if I am wrong.
