### ISSUE TITLE
what is the difference between BarracudaWorkerFactory.Type's elements?

### ISSUE THREAD

**Issue by DeusExMachina1993** [Unity-Technologies/ml-agents#2262]
types is:
 BarracudaWorkerFactory.Type.CSharp,
BarracudaWorkerFactory.Type.CSharpFast,
BarracudaWorkerFactory.Type.Compute,
BarracudaWorkerFactory.Type.ComputeFast

Shall I consider anything before using barracuda in the Android game?

**Comment by unityjeffrey** [comment]
cc: @mantasp

**Comment by mantasp** [comment]
BarracudaWorkerFactory.Type.CSharpFast <- fast CPU path
BarracudaWorkerFactory.Type.CSharp <- slow reference CPU implementation, useful for debugging
BarracudaWorkerFactory.Type.ComputeFast <- fast GPU path
BarracudaWorkerFactory.Type.Compute <- slow reference GPU implementation, useful for debugging

if your model uses visual inputs, then ComputeFast is good choice, otherwise for small ML Agents models CSharpFast should be best choice.

P.S. starting with ML Agents v0.8.2, it comes with Barracuda 0.2.x, which changed definitions of the worker types.
