### ISSUE TITLE
Inference mode for mlagents-learn causes problems with TensorBoard

### ISSUE THREAD

**Issue by roboserg** [Unity-Technologies/ml-agents#2349]
**1.** I am training a model. I stop the training and run mlagents-learn without `--train` to just benchmark the agent. It causes problems with TensorBoard where the graph jumps to the beginning of the training, see picture below.

Maybe training data should not be saved for the model if the model is run in a inference mode to not confuse Tensorboard?

![SnippingTool_2019-07-27_04-17-36](https://user-images.githubusercontent.com/4758917/61988733-ab8e0280-b025-11e9-8dc2-95a833a5860d.png)

**2.** Also I am getting .csv files in the summaries folder. These files are only created with `--debug`, but I am not using `--debug`. Why are these files are still created if I am not using the debug flag?

**Comment by harperj** [comment]
@roboserg case 1) is because you're running with the same `run-id`.  If you pass a new run-id with the `--run-id` flag you should be able to avoid adding the datapoints to the same graph.

For 2) the intention was always that these `.csv` files should be created whether or not you use `--debug`.  The goal of these files is to provide a plaintext summary (vs. the Tensorflow binary format) which you can use to monitor the performance of your training session.

**Comment by ervteng** [comment]
Thank you for submitting this request. We’ve added it to our internal tracker with the ID MLA-77. I’m going to close this issue for now, but we’ll ping back with any updates.

**Comment by ervteng** [comment]
This has been fixed since release 0.14.0. Now when running inference it will continue to log from where you last started. Feel free to reopen the issue if you're still having issues.
