### ISSUE TITLE
No "Scripting Runtime Version" in Unity's "Other Settings" menu?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#2509]
**Describe the bug**

In the [basic guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md), step 5 .ii the instruction is to:
Select Scripting Runtime Version to Experimental (.NET 4.6 Equivalent or .NET 4.x Equivalent)
However, I don't see the Scripting Runtime Version in my Project settings. 

<img width="611" alt="screenshot 3" src="https://user-images.githubusercontent.com/16321685/64488379-8c4edb80-d247-11e9-9a7f-c88e6feb53b2.png">

**To Reproduce**
In Unity, 
Go to Edit > Project Settings > Player
For each of the platforms you target (PC, Mac and Linux Standalone, iOS or Android):
Expand the Other Settings section.
Select Scripting Runtime Version to Experimental (.NET 4.6 Equivalent or .NET 4.x Equivalent)

**Environment (please complete the following information):**
- MacOS Mojave, Unity Version 2019.2.4f1 Personal
- _ML-Agents version_:  latest branch from source

Thanks for the help!

**Comment by chriselion** [comment]
Hi @MarkTension 
It looks like some of the Player settings have changed since that part of the documentation was written (That settings appears in the 2019.1 documentation https://docs.unity3d.com/2019.1/Documentation/Manual/class-PlayerSettingsStandalone.html but was apparently removed in 2019.2). You should be fine ignoring that setting for now; we'll update the documentation to be clearer.

**Comment by chriselion** [comment]
I've added a request to update the documentation around this to our internal tracker with the ID MLA-18. I’m going to close this issue for now, but we’ll ping back with any updates
