### ISSUE TITLE
NN model not behaving like agent during training (Curriculum Learning).

### ISSUE THREAD

**Issue by SimonNordon** [Unity-Technologies/ml-agents#2560]
I've been training an agent to get better at navigating a series of mazes, by giving it harder mazes to complete via curriculum training. After 500K steps it was passing the hardest maze fairly well:

![image](https://user-images.githubusercontent.com/33815844/64919010-17504880-d7e9-11e9-95e0-d15dea84f55b.png)

You can see before it hit max steps it was doing quite well. However when I get the saved model and plug it in to the agent brain, it behaves not as well, and acts quite dumb in comparison. It NEVER completes the hardest maze with the nn model. 

It's definitely from the same run ID. 

![image](https://user-images.githubusercontent.com/33815844/64919031-7c0ba300-d7e9-11e9-9c79-ab044a8fe842.png)

Here's the full graph from the training. 

`{
    "measure" : "reward",
    "thresholds" : [0.8, 0.8,0.8],
    "min_lesson_length": 100,
    "signal_smoothing" : true, 
    "parameters" : 
    {
        "level" : [0.0, 1.0, 2.0,3.0]
    }
}`

Here is the curriculum. Any help is appreciated.

**Comment by awjuliani** [comment]
Hi @SimonNordon 

Differences in performance between training and testing can be due to differences in the training and inference settings in the academy. I would recommend looking there to ensure that things such as visual quality aren't being changed (In the case that your agent is learning from visual observations).
