### ISSUE TITLE
Anaconda in startup documentation

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#2561]
While I understand the advantages of Anaconda envs, they can create unnecessary complexity when automating or debugging ml-agents. ml-agents work very well with a direct installation of python and it is easier to automate training. Does anyone else feel that the process in the startup documentation could be changed to have a "simple" installation?

**Comment by awjuliani** [comment]
Hi @mnsmuts 

Thanks for this feedback. Many of us on the development team for ML-Agents actually just use direct (or virtual env) python installations and environments. We choose Anaconda instructions to help game developer users who may be less familiar with python tools. We will take this feedback into consideration as we think through documentation improvements in the future.

**Comment by nick-morhun** [comment]
Well, I can't seem to setup the environment even with anaconda due to package version conflicts. I know little about Python and not sure where do I get the ancient Tensorflow 1.7.1 nowadays, since pip says it doesn't have it.
Is there some way to just create some shared Anaconda environment config or a Docker image?
