### ISSUE TITLE
[Question] Observations

### ISSUE THREAD

**Issue by ZephyrRaine** [Unity-Technologies/ml-agents#257]
Hello people who made or have experimented with this :)

It might be a bit of a "lazy" question but before diving into implementation I would love to have some advice on this.

I'm making a grid based game with a variable number of elements (units/buildings). I was wondering if there was any difference between giving the Brain a state list containing all grid cells info (1 for obstruction, 0 for no obstruction, 2 for unit for example) and giving it an observation camera tuned so each cell is one pixel? 

Cheers and thanks in advance :)

**Comment by gerardsimons** [comment]
Generally speaking, it will just be a bit slower to learn, as the convolutional network will need to learn about the representation of each color pixel, otherwise it will be pretty much the same. Added value of an observation-based method is that you can easily extend / change the game, without explicitly having to change the state list. It will learn what reward changes these new pixels will amount to.

**Comment by ZephyrRaine** [comment]
Thanks! <3
