### ISSUE TITLE
Convert .pb file to .nn file

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/ml-agents#2603]
Hi, 

I have created a model with tensorflow and I saved it to a .pb file. Is there any way to convert the .pb file to the .nn file required by Unity?

**Comment by weizhuang-93** [comment]
Hi @SestoAle ,

i tried using tensorflow_to_barracuda to convert to .nn but to no success. maybe u can try:
[https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md](url)

incase i posted my issue here.. would be glad if you could tell me if u succeeded
[#2483](https://github.com/Unity-Technologies/ml-agents/issues/2483)

**Comment by chriselion** [comment]
@SestoAle - the  [tensorflow_to_barracuda](https://github.com/Unity-Technologies/ml-agents/blob/develop/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py) script is used to convert .pb files to .nn files. You can see where this is used here: https://github.com/Unity-Technologies/ml-agents/blob/3a189a00afe170bab1c630a101cff2f3294f286d/ml-agents/mlagents/trainers/tf_policy.py#L230

However, we can only guarantee support for models that were generated by ML-Agents. Since you created you model on your own, the script may or may not work.
