### ISSUE TITLE
Behaviour when multi-environment process dies

### ISSUE THREAD

**Issue by sebjf** [Unity-Technologies/ml-agents#2641]
Hi, I am making some [modifications](https://github.com/sebjf/ml-agents/tree/develop-clustertraining) to allow training across multiple machines. 

(Since the environment makes the connection and not vice-versa, this is mainly removing checks to allow multiple `UnityEnvironment`s to be created without starting their own processes, and enabling the environment communicator to take a remote host along with a port number.)

In tests, I have noticed that training can stall, and it appears to be after one of the remote environments dies. I am not sure how the process fails. The log files don't show anything. But it vanishes from the process list and `learn` hangs. 

I have tried to recreate the issue by killing a process in a VM. On ending training I get exceptions when the close signal is sent to the dead environment, and the (python) process talking to it hangs around until I forcibly close it to get the port back. However, between killing the environment and then, training continues normally with the remaining environments.

Does anyone have any thoughts on this? What happens when one of the training environments dies? Why might it eventually stall a trainer entirely?

**Comment by chriselion** [comment]
Hi @sebjf ,
I made a fix recently around environment shutdown that might be helpful:
https://github.com/Unity-Technologies/ml-agents/pull/2600
It sounds like it might be related to your situation; python processes would hang on shutdown until any pending step date was popped from the queue. Calling `cancel_join_thread() from the worker fixed this.

https://github.com/Unity-Technologies/ml-agents/pull/2620 is something else to be aware of (although probably not directly related). I changed `subprocess.Popen` to pass `start_new_session`, so that signals to the parent wouldn't be sent to the child process (the goal being to stop SIGINT from killing the environment before it had a chance to shutdown). If that's not desirable behavior, let me know and we can add command line switch to toggle it.

Can you let me know if the `cancel_join_thread()` fixes your problem; if not we can try to dig into it more.

**Comment by sebjf** [comment]
Thanks @chriselion. 

I have integrated the latest develop with those changes, however the behaviour re-occurs. 

This time, I noticed that all the UnityEnvWorker child processes were running, as well as actual environment processes on the other machine, but when I terminated the training, the UnityEnvWorker processes exited but the environment processes continued even though the shutdown messages were supposedly sent. 

This suggests the connection between one or more of the worker child processes and the environments has been lost, perhaps.

Is such a thing possible? The RpcCommunicator created by the UnityEnvironment created by the env_factory uses grpc I see, but I don't know much about this (e.g. what protocol it uses underneath).

**Comment by sebjf** [comment]
I have now started training on our local cluster. I've only had a couple of sessions of 10 million steps with 20 instances, but all have completed without issue. No modifications were made since my last post, other than to propagate the timeout param in case the cluster takes a few moments to allocate. The issue was repeatable with AWS, so I expect it is to do with AWS itself or some strangeness over the public internet. I can't connect to our cluster from outside to test, but I might find some spare machines to see if I can re-create separately.

**Comment by chriselion** [comment]
hi @sebjf,
Sorry for the delay on this. I believe the behavior for dead/hung got better with this PR https://github.com/Unity-Technologies/ml-agents/pull/2812, which is also in the 0.11.0 release.
