### ISSUE TITLE
Is Deterministic behaviour on trained models possible? 

### ISSUE THREAD

**Issue by CaptainPineapple** [Unity-Technologies/ml-agents#2643]
Hello there,

I'm currently working on a project including ml-agents. This has lead me to a point where i ran a learned model in inference with 16 agents with the exact same starting conditions. While expecting that every agent should choose the exact same actions since all startconditions are equal and there should be no random influence in there, not all of them behaved exactly the same. In some instances some agents decide for other actions than the majority of agents.

This kind of made me wonder: Is this wanted behaviour? Am i doing something wrong here? Is this only a sign that the agent has not explored the action space to it's fullest and is still trying to take a few peeks here and there? (Though this should not happen since i am not learning anyway) Do i have to expect random behaviour in case the agent encounters a state where there are mutliple equally good actions available?

I can't seem to find any information on this topic in the documentation provided along the ml-agents repository or the paper on ml-agents. I also can't seem to find any information if a learnt NN-Model is tweakable or modifiable (especially regarding random actions) after the learning process has been finished.
If someone can shed some light on this i'd be very grateful.

---

Some info on my Setup: The agent learns moving on a grid with discreticed action space. (6 actions - one for moving one step along each axis) no visual observations, only an observation vector. This contains the last action taken and 10 values containing information on distances to the next walls in all movement directions.

**Comment by chriselion** [comment]
Hi @CaptainPineapple,
This sounds like the expected behavior for multiple agents using the same brain. All the "random" decisions at inference time should come from
https://github.com/Unity-Technologies/ml-agents/blob/99e997c811176b163908f7c619b8aa9947e7e9b7/UnitySDK/Assets/ML-Agents/Scripts/InferenceBrain/Utils/Multinomial.cs#L23 and
https://github.com/Unity-Technologies/ml-agents/blob/99e997c811176b163908f7c619b8aa9947e7e9b7/UnitySDK/Assets/ML-Agents/Scripts/InferenceBrain/Utils/RandomNormal.cs#L21 - each has its own (pseudo) random number generator which is seeded by the LearningBrain initialization: https://github.com/Unity-Technologies/ml-agents/blob/99e997c811176b163908f7c619b8aa9947e7e9b7/UnitySDK/Assets/ML-Agents/Scripts/LearningBrain.cs#L76

However, since inference is run for all the agents corresponding corresponding to the brain in a batch, we'll make sequential calls (once for each agent) to these random number generators, providing different results for each agent. 

If you really want identical behavior for each agent, I think you can accomplish this by creating a different brain (using the same model) for each one.

Note that since the generators are seeded identically, I would expect the agents (as a group) to behave identically across multiple executions (assuming everything else in the environment is deterministic also). At the moment we don't have any tests to enforce this, though.

> I also can't seem to find any information if a learnt NN-Model is tweakable or modifiable (especially regarding random actions) after the learning process has been finished.

There's nothing supported out of the box for this.

**Comment by CaptainPineapple** [comment]
Hey @chriselion,

thank you for your support on this. 

So by forcing the same random seed i can ensure the same behaviour for parallel running agents.
What i do not understand so far is why there even is random behaviour at all. From my understanding an Agent in reinforcement learning chooses the best action for it's current state based on its observations. So shouldn't the exact same observation vector always lead to the same action beeing chosen in inference? If there is still random behaviour in there this basically means i cannot ensure optimal behaviour for an agent.

Or does the random behaviour only come into action if there are multiple actions whos expected future reward is almost identical?

**Comment by chriselion** [comment]
Hi @CaptainPineapple,
Here's an answer to a very similar question about randomness (from someone who's better at RL than I am): https://github.com/Unity-Technologies/ml-agents/issues/2112

Does that help address your concerns?

**Comment by CaptainPineapple** [comment]
Hi @chriselion,

even though i do not really like it. Yes that basically answers the question why there is randomness :/
Sorry for missing that issue. Should have come up when i researched this.

The last thing that results as a question for me now: Is there a way to manipulate how often a random action is chosen instead of an optimal one? Like is that directly related to the policies entropy given on tensorboard while training? 

Does this belong here or would you rather have me reopen issue 2112 for this?

**Comment by chriselion** [comment]
Hi,
I think it's a reasonable request for something we should provide (with the caveats that it might perform sub-optimally). Besides the issue I linked to before, it has come up a few other times in the past.

I added the request to our internal tracker with the ID MLA-88. I’ll ping back with any updates (but no timeline yet)...
