### ISSUE TITLE
Difference between maxSteps in unity editor and number of steps being counted in the command prompt while training

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2736]
Hello all,
I wanted to know the difference between number of steps being calculated for agent reset after the maxSteps are reached and the steps which are shown in the command prompt where the training takes place. I believe the steps in the unity editor are calculated lot faster than in the command prompt. Kindly clarify.

Thanks in advance

**Comment by FlimFlamm** [comment]
I would like some clarification on this as well.

In the past I've had straight up bugs with constant decision rates (cross wiring between agents being run in the same environment), and recently ive seen some strange behavior when using variable decision rate.

When i use the same looping timer to trigger decisions for all the agents in a scene (which share a brain),meaning they all make a decision at the same time,  agent steps will accumulate at a familiar rate in the  cmd prompt summaries. But, when i allowed agents to set their own next decision delay, agent steps started accumulating about 20 times faster (and there were about 20 agents in the scene).

This implies that when a brain makes a decision for multiple agents in a single update, it only counts it as a single decision. I need to do some testing to confirm this theory, but I have long suspected it. 

The in-game results of training -appear- to be unaffected by this issue, so it might just be a bug in the diagnostic outputs, but it may also point toward a deeper root cause. This might also explain why using recurrence with multiple unique agents in the same scene tends to throw the value-key error (i've never tried running recurrent agents on different fixed updates to see if it fixes the error, but that would definitely be confirmation)....

**Comment by FlimFlamm** [comment]
So i just offset the timers in my multi agent environment, and my suspicion proved correct: when a single brain-multi agent setup makes decisions for more than one agent in a single FixedUpdate() (at least for variable decisions) it is only counted as a single agent step for the brain.

Offsetting the decision timers for each agent has multiplied agent step accumulation by the number of agents in the scene. In the time it has taken to write this follow-up post, the agents have already accumulated a collective total of 9k steps in 200 seconds
