### ISSUE TITLE
I want to apply deep learning to racing games as well.

### ISSUE THREAD

**Issue by WannyWanny** [Unity-Technologies/ml-agents#2760]
Although it is not an environment that I have made myself, I appreciate it if you reply.
I made a racing game using a template provided by Unity.
I want the cart to finish on its own. The brain and academy were added. What method should be added within the script?

**Comment by chriselion** [comment]
You should look through some of the beginning documentation. I think https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md is a good place to start, since it covers what you need to add to an existing "game". In particular, you'll need to add an Agent class and get it to collection observations and respond to actions; see the "Implement an Agent" section for more information.
