### ISSUE TITLE
Input bug of agent

### ISSUE THREAD

**Issue by Hongsungchan** [Unity-Technologies/ml-agents#2792]
![K-011](https://user-images.githubusercontent.com/43347736/67473774-441c3900-f68e-11e9-956b-e027ce4645ac.png)

![K-009](https://user-images.githubusercontent.com/43347736/67473730-349cf000-f68e-11e9-915f-3ec83e9181f3.png)

![K-010](https://user-images.githubusercontent.com/43347736/67473732-35358680-f68e-11e9-82de-888bec06bd2b.png)

      if (WS == 1)
        {
            VC.Agent_V = 1F;
            //1
        }
        else if (WS == 2)
        {
            VC.Agent_V = -1F;
            //-1
        }
        else if (WS == 0)
        {
            VC.Agent_V = 0;
        }

        if (AD == 1)
        {
            VC.Agent_H = 1F;
            //1
        }
        else if (AD == 2)
        {
            VC.Agent_H = -1F;
        }
        else if (AD == 0)
        {
            VC.Agent_H = 0;
        }

        if (Click == 0)
        {
            VC.agentClick = false;

        }
        else if (Click == 1)
        {
            VC.agentClick = true;

        }

The WS and AD inputs for the agent should only show 0,1,2, but are entering 3.

Click and Use_Skillpoint should only have 0,1.

It seems to happen after the agent reset.

So I ended the agent's learning and brought up the agent's learning again.

As soon as the agent starts learning again 

the agent input 3 again

**Comment by surfnerd** [comment]
Hi @Hongsungchan,
Thank you for reporting your issue.  I’m not sure I completely understand what problem it is you are having.  Is this custom code you have?  From the inspector I might guess that WS and AD return 3 since they are set to three, but I don’t have enough information to know what’s happening in your code.  Would you be willing to create a small reproduction project that highlights this bug?  Thanks for your time and interest in ML-Agents.
