### ISSUE TITLE
How do I train my own models in unity rather than use prebuilt ml-agents models?

### ISSUE THREAD

**Issue by georgechen1** [Unity-Technologies/ml-agents#2831]
I would like to train my own models, which I saw before you could do using a ppo.ipynb file.
I want to learn about the models rather than just use the prebuilt ones.
I am also really confused on how the inference engine works. What exactly is an inference engine and why is it significant that the unity one is being used rather than one built in tensorflow sharp as before?

**Comment by harperj** [comment]
About the inference engine: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Unity-Inference-Engine.md

We wrote this so that we can execute models within Unity.  TensorflowSharp wouldn't allow us to execute the models on all of the platforms we would like to support.  By using the Barracuda inference engine we can execute on all of the platforms Unity supports.

You can see the [basic guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#after-training) for instructions on how to take the model (`.nn` file) after training an environment and use it for inference.

**Comment by Esther2013** [comment]
@harperj As I know, [TensorFlowSharp](https://github.com/migueldeicaza/TensorFlowSharp) is retired by [Miguel](https://github.com/migueldeicaza), he recommends [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET) as an alternative. 

TensorFlow.NET is built on top of .net standard 2.0 that is cross-platform ([One library to rule them all](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)). So could you tell what platform doesn't support?

**Comment by harperj** [comment]
@Esther2013 an example is generation of single-binary executables for inference on game consoles.  We decided to retire our use of TensorFlowSharp a while ago and are keeping an eye on Tensorflow.NET but haven't decided to adopt it at this time.

**Comment by georgechen1** [comment]
Ok so in that case how would I train my own model then?
