### ISSUE TITLE
Why was the Conda installation readme removed?

### ISSUE THREAD

**Issue by devedse** [Unity-Technologies/ml-agents#2854]
I saw that the windows installation readme was removed:
https://github.com/Unity-Technologies/ml-agents/pull/2833/commits/426a2dda02f7c8b020dc99a480885d5dc0b19187#diff-74908b38dd56d6ffc4669038c7ef9339

It was really handy to have this readme in place as a lot of windows users are using Conda to work with Python.

Is there any specific reason why we should use Virtualenv instead of conda?

**Comment by DVonk** [comment]
I would like to know this as well. Am I not supposed to use Anaconda anymore? I find the installation instructions for virtual environments under Windows to be pretty confusing as they assume that you already know how to get a working Python installation and Tensorflow on your machine. 

The Anaconda step-by-step instructions were just right - what happened to them?

**Comment by harperj** [comment]
Hi @devedse / @DVonk -- we decided it would be simpler to help people through the setup process if we only had a single recommended path in our docs.  You're welcome to continue using Anaconda, and we aren't trying to discourage anyone from using the tools that work best for them.

**Comment by DVonk** [comment]
@harperj Okay. So, have you tried setting up ML-Agents on a clean Windows installation according to the instructions? I'm regularly supervising projects that use ML-Agents at university and it was really easy to set up thank to the step-by-step Anaconda instructions. For the newest project I've had so many questions from students that don't have any experience with Python and I wondered why - until I noticed that the Conda readme was gone.

I really think you should do this from the point of view of someone coming directly from Unity, with no Python experience whatsoever. There is a lot of missing information, or things that are just glanced over that threw my students off. 

There are also some things that flat out didn't work when I tried following the readme, e.g.:

- > In order to use ML-Agents toolkit, you need Python 3.6.1 or higher. Download and install the latest version of Python if you do not already have it.

Yet the newest version (3.8) does not work. I'm getting version mismatches for Tensorflow which prevent installation entirely. 3.7.3 works for some reason.

- > To create a new environment named sample-env execute $ python3 -m venv python-envs\sample-env

Doesn't work. It only works with "python' instead of "python3", otherwise absolutely nothing happens.

- When following with Python 3.6.8 (the newest one I've found an .exe installer for) I get this error, which makes tensorboard unusable:
 tensorboard 1.15.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.6.2 which is incompatible.


I agree that a universal way of installation is the way to go, but I definitely don't think this is the way to do it.

**Comment by sonicviz** [comment]
I think this was a bad decision to remove the Anaconda install instructions. 
I just started working with the ML kit and have been scratching my head as to why there were not any instructions for Anaconda, which is a pretty standard way of managing Python environments on Win.

**Comment by unityjeffrey** [comment]
hi @sonicviz, @DVonk, @devedse - thank you for your feedback, very helpful for us to understand the needs for conda in Windows.  For now, please refer to the previous instructions (it should be the same steps).  https://github.com/Unity-Technologies/ml-agents/blob/0.10.1/docs/Installation-Windows.md

Will keep you posted on next steps on Anaconda instructuions for Windows.

**Comment by DVonk** [comment]
@unityjeffrey Thank you. Is it still correct to install Python 3.6 and Tensorflow 1.7.1 or should I use a newer version? Because with Tensorflow 1.14 and 1.15 I get a lot of warnings for deprecated TF functions when training.

**Comment by harperj** [comment]
@DVonk either Python 3.6 or 3.7 will work, and Tensorflow 1.7.x - 1.15.x.

The warnings are (mostly) related to the transition to Tensorflow 2.0.  We're currently working on migrating to the new APIs.

**Comment by sonicviz** [comment]
@unityjeffrey ty!

**Comment by walterellisfun** [comment]
> 
> 
> hi @sonicviz, @DVonk, @devedse - thank you for your feedback, very helpful for us to understand the needs for conda in Windows. For now, please refer to the previous instructions (it should be the same steps). https://github.com/Unity-Technologies/ml-agents/blob/0.10.1/docs/Installation-Windows.md
> 
> Will keep you posted on next steps on Anaconda instructuions for Windows.

Hi, I found this on the third day of trying to set up ML Agents on my setup. First try worked with this guide.
Note: I installed tensorflow-gpu and got it working using the guide, except for one issue that was solved by changing a line in "setup.py" according to this thread: https://github.com/Unity-Technologies/ml-agents/issues/1534

I couldn't get things set up without this guide, because some of the info was not available anywhere else.

**Comment by devedse** [comment]
Should this issue be closed as @unityjeffrey said he'll keep us posted? I think we should leave it open untill a final decision has been made.

**Comment by unityjeffrey** [comment]
hi @devedse - we put the Conda instructions back in since the last release.  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md
