### ISSUE TITLE
Logging Std of Reward to Tensorboard

### ISSUE THREAD

**Issue by AsadJeewa** [Unity-Technologies/ml-agents#2903]
Is there an option to display the std of reward in Tensorboard? Please advise on the fastest way to isolate this value

**Comment by ervteng** [comment]
Not currently but it would be trivial to add. In `ml-agents/mlagents/trainers/trainer.py` there is a line that reads `stat_mean = float(np.mean(self.stats[key]))` followed by `summary.value.add()`. You can just add another summary value add with np.std instead of np.mean.

**Comment by AsadJeewa** [comment]
Thank you. When I add code to trainer.py, nothing happens. As a sanity check, I changed some of the text in Logger.info but it does not change. This is incredibly frustrating and very weird. Any advice?

**Comment by AsadJeewa** [comment]
Thank you. It works. 
Please advise on why there are 2 trainer.py files?
One is the github clone and one is part of the site-packages in anaconda. I originally changed the wrong file. Was a frustrating process.

**Comment by ervteng** [comment]
Hi @AsadJeewa, if you're planning on modifying `trainer.py`, install ml-agents with `pip install -e ./` in the ml-agents-envs and ml-agents directories, rather than `pip install mlagents`, this will force `mlagents-learn` to point to the files in your github clone. The duplication has to do with how pip works - it makes a copy of the file in the site-packages folder.

**Comment by AsadJeewa** [comment]
Thank you. Much appreciated
