### ISSUE TITLE
Reset Academy - mlagents 0.11.0

### ISSUE THREAD

**Issue by BlonskiP** [Unity-Technologies/ml-agents#2996]
Hello, 
I would like to reset env each 10k steps. In 0.10 version there were academy paremeter for that, in new one i don't see it. I should I do it properly?

**Comment by DogInLake** [comment]
Just in general, I'm not really sure how resetting works since 0.10. I'm currently using an agent to reset after a certain number of steps. However, I'm unsure at the difference between resetting your environment vs having Tensorflow understand that an 'episode' is complete. The only way I can get episodes to complete and output their values to tensorboard is when a reset happens automatically through an agent.

Preferably there would be some way to make sure that both the in-unity environment is reset for the next run and the episode is marked as complete at the same time, especially as I'm using an RNN and I don't want it to learn that the whole game will randomly reset sometimes. Currently my environment resets and episode resets are decoupled, which I think is causing some weird behavior. For example, my agents are clearly trying to finish the game as quickly as possible, even if it means making bad moves, because the more often the environment resets during one episode, the greater total reward they can earn.
