### ISSUE TITLE
Unresolved import mlagents.envs.environment

### ISSUE THREAD

**Issue by thomasdingemanse** [Unity-Technologies/ml-agents#3026]
**Describe the bug**
After installing mlagents 0.11.0 and trying to import mlagents, I get an error message indicating that there is no module with that name. I'm using an Anaconda environment with Python 3.7.3. I have activated this environment, installed tensorflow and mlagents and tried to run the below commands.

If I run ```pip3 list``` it does show ```mlagents 0.11.0```. Calling ```mlagents-learn``` from the command line seems to work fine as well.

**To Reproduce**
1. Create and activate a new Anaconda environment.
2. ```pip3 install mlagents==0.11.0```
3. ```conda install keras```.
4. Create a python file containing ```from mlagents.envs.environment import UnityEnvironment```.
5. Run the file.
6. See error.

**Console logs / stack traces**
```
Traceback (most recent call last):
  File "d:/Development/test.py", line 1, in <module>
    from mlagents.envs.environment import UnityEnvironment
ModuleNotFoundError: No module named 'mlagents'
```

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v0.11.0
- _TensorFlow version_: 1.15.0
- _Environment_: UnityEnvironment

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by chriselion** [comment]
Hi @thomasdingemanse,
The error message makes it sound like it can't find mlagents at all (not just mlagents.envs.environment). 

I'm not an anaconda expert, but based on https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment and https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md#step-3-install-required-python-packages, I think you might need `pip` instead of `pip3` - my guess is that `pip3` is the "system" pip, so it's installing things outside of your conda environment.

If you run `pip debug` (and `pip3 debug`) that should list the path of the executable, which might give more information.

**Comment by thomasdingemanse** [comment]
I think that's it, thanks! I haven't resolved the issue yet, but I know where to look now (Anaconda/pip). In any case, it doesn't seem to be a bug in mlagents so I'll close this bug report.
