### ISSUE TITLE
Confused about what is an "Ephisode" in ML-Agents

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#3061]
I am confused about what is the definition of an _Episode_ in ML-Agents and what triggers the end of an episode. Related question: Is the end of an episode demarked by Agent.Done" or by "Academy.Reset"? Looking through the code it appears that sometimes ML-Agents considers an episode to be the span between Agent.Reset and Agent.Done and other times it is the span between the start and end of a ciriculum stage. The ML-Agents documentation suggests an episode is related to a batch/policy-update. 

From the internet: _All states that come in between an initial-state and a terminal-state; for example: one game of Chess. The Agent’s goal it to maximize the total reward it receives during an episode._ IMO this suggests that a single _ephisode_ should be the steps for a single agent between Agent.Reset and Agent.Done.

From the ML-Agents Documentation: _Implement an AcademyReset() function to alter the environment at the start of each episode. For example, you might want to reset an Agent to its starting position or move a goal to a random position. An environment resets when the reset() method is called on the Python UnityEnvironment._ This paragraph suggests that AcademyReset is coupled with an _ephisode_ and is related to a batch being completed and the policy updating. This is something that happens less frequently than AgentReset/Agent.Done. A single agent can do Agent.Reset/Done many times between AcademyResets.

From the code: When using cirriculum learning it appears that AccademyReset only happens at the beginning of each curriculum stage. There are many AgentReset/Agent.Done's that happen during a single cirriculum stage. Is a single cirriculum-stage defined to be an episode?

From the code: The python code that keeps track of stats and some of the comments it suggests that an _episode_ is a single agent between AgentReset and AgentDone.

Questions:

How are AcademyReset and Episodes related?
How are Agent.Reset-to-Agent.Done and Episodes related?
How are curriculum stages and Episodes related?
How are batches/policy update and Ephisodes related?
For a single agent, how many Agent.Resets-to-Agent.Dones are there per ephisode?
Is the "Agent’s goal it to maximize the total reward it receives during an episode" or between Agent.Reset and Agent.Done?
What is the criteria for triggering AcademyReset?

**Comment by ervteng** [comment]
Hi @Phong13, thank you for the in-depth investigation!

AcademyReset is the global reset function - it's not meant for "normal" use. This is because within one scene, there are many Agents, and each Agent could end their episode at different times. We wouldn't want to reset all the agents if only one is finished! 

An episode with respect to the trainer is between an Agent.Reset and an Agent.Done. In most training scenarios using our trainer codebase, AcademyReset is never called since the agents just run until Done and reset themselves. An AcademyReset is used only when the Python code needs to force-reset all the agents (such as, need to change the environment parameters for the sampler or the next lesson in the curriculum), or in the case of the OpenAI gym wrapper, where the algorithm needs to call reset(). 

For your use case, I'd recommend doing the generalization randomization in the AgentReset, or simply using the sampler. Hopefully that helps!

**Comment by Phong13** [comment]
Thanks for the clarification! This is helpful. IMO it would be useful to have this definition in the documentation.

**Comment by Phong13** [comment]
Hmmm, it seems that the UnitySDK and Python trainer are using different definitions for an Episode:

Here is the code from the UnitySDK.Academy.EnvironmentReset:

        void EnvironmentReset()
        {
            m_StepCount = 0;
            m_EpisodeCount++;
            AcademyReset();
        }

You can see that m_EpisodeCount is being incremented with AcademyReset. The UnitySDK obviously considers an Episode to be the steps between AcademyResets.

However, from what you said, and from the python code it appears that the python trainer considers an Episode to be the steps between AgentReset and Done.

It would be nice if the UnitySDK and the python Trainers agreed on the definition of an Episode.
