### ISSUE TITLE
Learning-Environment-Create-New more detailed description

### ISSUE THREAD

**Issue by sonfiree** [Unity-Technologies/ml-agents#3090]
Agent is completely different from other agents in the examples.
And on the basis of this tool, I can’t start the project.

**Comment by chriselion** [comment]
Please make sure you're looking at the right version of the documentation for the code that you're using. The version on the master branch may have changed since the last release. 

You can get the version from the most recent release here: https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Create-New.md
or for example for the 0.12.1 release here https://github.com/Unity-Technologies/ml-agents/blob/0.12.1/docs/Learning-Environment-Create-New.md
