### ISSUE TITLE
Number of agents limit

### ISSUE THREAD

**Issue by jonboh** [Unity-Technologies/ml-agents#311]
I've found that if I put enough agents linked to the same Brain (around 64 agents), the training exits abrutly with the following error in the PPO notebook:
[WinError 10054] An existing connection was forcibly closed by the remote host.

I've tried to get the Error in the .exe but I'm not sure how to write to a file the console output before it closes.

Any idea if this is related to a limitation of ml-agents?

**Comment by vincentpierre** [comment]
Hi, thank you for pushing ML-Agents to its limits. I would recommend looking into [the log files](https://docs.unity3d.com/Manual/LogFiles.html) that Unity generates when running, This could give you an idea of why the crash happened. If Unity did not encounter an error, it could be due to a limitation on the amount of data Unity and Python can exchange and I am not sure how we could solve this.

**Comment by mmattar** [comment]
Hi @jonboh - we've also since released v0.3 of ML-Agents which includes a number of enhancements. I'll close this issue, but feel free to create a new one if you run into any additional problems.
