### ISSUE TITLE
[Help] Problems with Python API Interacting with Executable Environment

### ISSUE THREAD

**Issue by Pabmyster** [Unity-Technologies/ml-agents#3110]
I am having trouble following these guides for getting the Python API working with a Unity Executable. As a Python beginner I feel as though I am missing something obvious, but I cannot find where the guides tell me to define the environment name as seen in these pictures. There are no files specified anywhere in these guides, and oftentimes I have found that names of files or directories have been changed from what the guide says. Am I supposed to create a new Python script from where I interact with my environment? Any help is very much appreciated.

The guides in question are:
https://github.com/Unity-Technologies/ml-agents/blob/master/notebooks/getting-started.ipynb
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md

![env_params](https://user-images.githubusercontent.com/49291804/71269482-77411880-231d-11ea-830d-0facc80ed4e7.png)
![env_params2](https://user-images.githubusercontent.com/49291804/71269484-77411880-231d-11ea-8cbc-d71b2c908a39.png)
![executable_env](https://user-images.githubusercontent.com/49291804/71269485-77411880-231d-11ea-9aa3-931712053ef5.png)

**Comment by andrewcoh** [comment]
Hi @Pabmyster,

My first recommendation is to check the docs of the latest_release tag here: https://github.com/Unity-Technologies/ml-agents/tree/latest_release

Were you able to create the build following the directions in the section "Build the 3DBall environment" of https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Executable.md ?

If you were able to create the build, the simplest way to run is to use the --env flag to specify the path to your build i.e. in envs.  (See https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Executable.md#training-the-environment)

Otherwise, let me know where you got stuck.

**Comment by valentinmace** [comment]
I am not sure to get your question but if it can help:

- Build your game in Unity (I recomend you to start with provided examples, say 3DBall)
- Create a python script where you want
- In your script, define env_name as the absolute path of your built game, for me it looks like
`env_name = "D:/Users/Valentin/Desktop/test/ml-agents/UnitySDK/Builds/ball.exe"
`
- Instantiate a UnityEnvironment with your env_name (don't forget to import what you need)
`env = UnityEnvironment(base_port = 5006, file_name=env_name, seed=1)
`
- Executing this little script should launch your game, then you can start working on interacting with it

Hope this helps

**Comment by andrewcoh** [comment]
Were you able to create the executable following all the instructions here https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Executable.md#building-the-3dball-environment ?
