### ISSUE TITLE
Outdated Windows setup instructions

### ISSUE THREAD

**Issue by aaronflippo** [Unity-Technologies/ml-agents#313]
The current documentation links to this blog post for setup on Windows:
https://unity3d.college/2017/10/25/machine-learning-in-unity3d-setting-up-the-environment-tensorflow-for-agentml-on-windows-10/

However, this document seems to be outdated. The latest Tensorflow seems to require Cuda version 9.0, not 8.0. Following this blog posts resulted in python errors about missing .dlls.

Would it be possible to get updated instructions for Windows setup?

**Comment by MarcoMeter** [comment]
`pip install -I tensorflow-gpu==1.4.0` 

That's the only modification which I'd make to the guide. Thus sticking to Cuda Toolkit v8.0 and cudnn 6. I guess updating to tensorflow 1.5 might break some functionality, like using TensorflowSharp.

**Comment by aaronflippo** [comment]
Thanks, that makes sense. Do you think there would be value in internalizing these setup instructions to the github page so they can be kept up to date? As a beginner to these libraries and technologies, I spent quite a bit of time fighting with this setup and trying to figure out why it was spitting out errors.

**Comment by MarcoMeter** [comment]
It's up to the devs. I don't know how they treat this in general. But someone is doing work on the documentation branch of this repository. Maybe that's worth checking out. Otherwise, I guess the devs are pretty busy on implementing the next set of features. Keeping a documentation up-to-date frequently is quite an effort (especially if there are multiple operating systems to be supported).

**Comment by sterlingcrispin** [comment]
@aaronflippo @MarcoMeter hey thanks for posting this, I ran into the same issue and just created a PR , in the future its always helpful to hit the edit button and add that in 😄 👍 

I installed 1.4 do you know if there's any major advantage to 1.4.1?

**Comment by MarcoMeter** [comment]
> I installed 1.4 do you know if there's any major advantage to 1.4.1?

It's just that v1.5 is not supported due to TensorFlowSharp.

**Comment by mmattar** [comment]
A few updates:
- We've since released v0.3 of ML-Agents which include additional enhancements.
- Part of the release is an updated Windows installation guide: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md
- We currently only support TensorFlow 1.4, but working to expand to 1.5 in the near future.

Closing this issue, but feel free to create a new one for any additional questions.
