### ISSUE TITLE
Development-0.3 Branch: Default Banana Example Brain Errors

### ISSUE THREAD

**Issue by HappySlice** [Unity-Technologies/ml-agents#327]
When I try to run the Banana example with the included "Banana-fight" brain, I get this error:

> UnityAgentsException: The number of states does not match for agent Agent (2):
>     Was expecting 204 continuous states but received 206.
> Brain.CollectStates () (at Assets/ML-Agents/Scripts/Brain.cs:279)
> CoreBrainInternal.SendState () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:169)
> Brain.SendState () (at Assets/ML-Agents/Scripts/Brain.cs:425)
> Academy.Step () (at Assets/ML-Agents/Scripts/Academy.cs:226)
> Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:351)
> Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:271)
> 

Then I get 3 more errors where it receives 208, 210, and 212 continuous states.
The Brain has a state size of 51 and a Stacked States value of 4, so expecting 204 states seems to make sense.

**Comment by Fallscout** [comment]
I looked into this. The BananaAgent builds a state vector of size 53, but in the inspector it specifies a state size of 51. However, if you set the state size in the inspector to 53, the pre-trained model doesn't work, because it was trained with a state vector of size 51 I assume.

You can get it to work by removing two states from the list that is generated in the CollectState function of the BananaAgent. If you remove the two lines
> state.Add(System.Convert.ToInt32(frozen));
> state.Add(System.Convert.ToInt32(shoot));

it will work. Alternatively you would have to train a new model with a state size of 53.
