### ISSUE TITLE
Training frozen when setting Enlighten threads (+ Segfault)

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#3279]
I am training an agent with `mlagents-learn` with PPO from a compiled binary environment with the `--no-graphics` flag, logging the results both in terminal and in Tensorflow. After 1 hour and half, I saw that the data in Tensorflow wasn't updated anymore. I opened the terminal and I saw that the training is stuck in the summary
```
INFO:mlagents.trainers: ppo: My Behavior: Step: 550172. Time Elapsed: 5195.779 s Mean Reward: -0.400. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: ppo: My Behavior: Step: 550573. Time Elapsed: 5197.894 s Mean Reward: -0.400. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: ppo: My Behavior: Step: 550974. Time Elapsed: 5200.003 s Mean Reward: -0.400. Std of Reward: 0.000. Training. 
Setting up 4 worker threads for Enlighten.
  Thread -> id: 7f042a3fa700 -> priority: 1
  Thread -> id: 7f0429bf9700 -> priority: 1
  Thread -> id: 7f04293f8700 -> priority: 1
  Thread -> id: 7f0428bf7700 -> priority: 1

```
As you can see, each summary should take a few seconds, but the training has been stuck for at least 20 minutes. I don't know if the Enlighten threads have something to do with this. I am using a fixed maximum time for episodes therefore that can't be the problem.

**Comment by fedetask** [comment]
Update: since it wase definetly stuck, I terminated using `CTRL-C`, and I obtained a segfault error.
```
INFO:mlagents.trainers:Learning was interrupted. Please wait while the graph is generated.
Segmentation fault (core dumped)
```
I'll follow up with more information if this happens again. Trainings are long but I'll try to keep you updated.

**Comment by vincentpierre** [comment]
Hi, I am not familiar with Enlighten threads. Could you try without the Enlighten threads and see if you are able to train then?

**Comment by fedetask** [comment]
I am not very familiar with them too. I'll try. However, the issue hasn't happened again, not even with Enligthen threads enabled. If I'll have news I'll post here

**Comment by robinerd** [comment]
I'm having the same issue it seems, usually happens after say 10-20 hours of training with 30 environments.
It's strange because we're using 2D only. We are using 2D lights but that has nothing to do with enlighten as far as I understand.
I will try to change our lighting settings and see if it helps. Will post here when I know more.

**Comment by vincentpierre** [comment]
I think this is an issue with Enlighten threads and not with ML-Agents. It would help me if you tried to run 30 environments **without ML-Agents** for 10-20 hours. Depending on wether the error happens or not, we will know if it is a ML-Agents issue or not.

**Comment by robinerd** [comment]
After trying to also run this locally I'm suspecting that the enlighten threads message is not the cause. I think it appears just before closing the process, maybe only in server builds. Since when I'm running a server build locally on windows the process freezes and as soon as I stop it with ctrl+C I get the Enlighen threads message.
I still have no idea why the training was crashing but it's probably something different. I think from our part we can drop this issue for now. I will let you know if I find anything new.
