### ISSUE TITLE
RayPerceptionSensorComponent3D does not function as expected when the agent's scale is not 1.

### ISSUE THREAD

**Issue by WanNJ** [Unity-Technologies/ml-agents#3321]
All the agents in the example scenes have a scale of 1. However, if changed the scale to other numbers, the Debug gizmo would also scale, resulting in the wrong rays drawn in the editor.

I haven't checked whether the observed values are correct yet. Presumably, it may have the same issue.

- ML-Agents v0.13.0
- TensorFlow v2.0
- Environment_: Change any of the agent's scale to not equal to 1.

To reproduce this bug, just change the scale of the agent of WallJump example and run using the trained model. You will see that the rays drawn in the editor is wrong.

**Comment by chriselion** [comment]
I'll look into this tomorrow.

Can you explain more what are you seeing and what do you expect? I would expect that when the scale changes, the length of the rays also increase.

**Comment by WanNJ** [comment]
> I'll look into this tomorrow.
> 
> Can you explain more what are you seeing and what do you expect? I would expect that when the scale changes, the length of the rays also increase.

The expected: the red sphere drawn representing the hit point should be the actual hitpoint. However, when the scale changes, the red sphere is drawn to somewhere else, scaling with the scale of the agent. However, I don't know if the observation feed into the RL component is corrent or not.
<img width="1440" alt="Screen Shot 2020-01-30 at 10 59 42" src="https://user-images.githubusercontent.com/17922409/73466369-c718f380-434f-11ea-85c8-debe2693be59.png">

**Comment by chriselion** [comment]
Thanks, the screenshot helps a lot. Looking into it now, I get the feeling the scale is being applied twice somehow.

**Comment by chriselion** [comment]
OK, I think I know what's going on. I believe this is just a visual bug, but it's definitely something we should fix.
When we do the raycasting here:
https://github.com/Unity-Technologies/ml-agents/blob/4ba8b973369435fc76fc67b32a753536d2f126c9/com.unity.ml-agents/Runtime/Sensor/RayPerceptionSensor.cs#L219-L228
we cast up to `rayLength` units, and save the hit fraction. This fraction is based on `rayLength` units.

When doing the gizmo drawing here
https://github.com/Unity-Technologies/ml-agents/blob/4ba8b973369435fc76fc67b32a753536d2f126c9/com.unity.ml-agents/Runtime/Sensor/RayPerceptionSensorComponentBase.cs#L127-L128
We try to use the hit fraction to interpolate between the start and end points. Since these start and end points are affected by the scale, they won't necessarily be `rayLength` units apart. So we'd need to scale the hit fraction (for display only) by `rayLength / rayDirection.magnitude`.

I think a cleaner fix would be to use the scaled ray length (`rayDirection.magnitude`) instead of `rayLength` for raycasting and hit fraction determination in PerceiveStatic. This means that the effective length of the rays would change with the scale; the downside is that this would break existing trained models.

I'll have a PR for this tomorrow or early next week. In the meantime, I'm pretty confident that training with a RayPerceptionSensor and scale will still work.

**Comment by WanNJ** [comment]
Thanks, Chris. Ml-agents is such an awesome project because of developers like you.

**Comment by chriselion** [comment]
This was fixed in https://github.com/Unity-Technologies/ml-agents/pull/3334
