### ISSUE TITLE
Burst Package Error w/ Unity 2019_3 +

### ISSUE THREAD

**Issue by LewisSim** [Unity-Technologies/ml-agents#3397]
**Describe the bug**
Using Unity version 2019_3 or higher gives a bug with burst. 

**To Reproduce**
1. Go to 'Any version of Unity higher or including 2019_3'
2. Install ML-Agents
3. See error

**Console logs / stack traces**
```
Library\PackageCache\com.unity.burst@1.1.1\Editor\BurstAotCompiler.cs(441,127): error CS0117: 'AssembliesType' does not contain a definition for 'PlayerWithoutTestAssemblies'
 ```

```
#if UNITY_2019_3_OR_NEWER
                return CompilationPipeline.GetAssemblies(shouldIncludeTestAssemblies ? AssembliesType.Player : AssembliesType.PlayerWithoutTestAssemblies);
 ```

**Screenshots**

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents 0.13
- _Environment_: Any

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by jli98dan** [comment]
I also run into the same problem. some one please help. I have been trying to figure this out for days....

**Comment by surfnerd** [comment]
Hi @LewisSim,
Could you give a specific version of Unity that you are using and other details about your setup?  We are testing against Unity 2019.3 on every commit with no issues.  

Could you try to delete your `Library` folder under your Unity project directory to see if that helps.  It's not ideal, but sometimes that helps fix things like this.

**Comment by JDONAL201** [comment]
I was receiving the same error messages , then started receiving no definition for ML-Agents.

- Unity 2019.3.0.f6
- Barracuda 0.6.0
- ML-Agents 0.13.1

Issue resolved after manually installing the new required package.

window->package manager -> + -> (package located in ml-agents folder) com.unity.ml-agents

Instructions found in installation section.

Hopefully this also resolves the issue for you as well.

**Comment by jli98dan** [comment]
Hi Chris,
I am using Unity 2019 3.0a5 version. For the project that I am working on
right now, we are told to use this specific version of unity.
This error occurred while I was following the tutorial for making a new
learning environment. I tried deleting the library folder like you said,
however I am still unable to run my project.
Thanks a lot for your help!
Best,
Danielle Li

Get Outlook for iOS <https://aka.ms/o0ukef>
------------------------------
*From:* Chris Goy <notifications@github.com>
*Sent:* Monday, February 10, 2020 1:02:15 PM
*To:* Unity-Technologies/ml-agents <ml-agents@noreply.github.com>
*Cc:* jli98dan <jli98dan@terpmail.umd.edu>; Comment <
comment@noreply.github.com>
*Subject:* Re: [Unity-Technologies/ml-agents] Burst Package Error w/ Unity
2019_3 + (#3397)


Hi @LewisSim <https://github.com/LewisSim>,
Could you give a specific version of Unity that you are using and other
details about your setup? We are testing against Unity 2019.3 on every
commit with no issues.

Could you try to delete your Library folder under your Unity project
directory to see if that helps. It's not ideal, but sometimes that helps
fix things like this.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Unity-Technologies/ml-agents/issues/3397?email_source=notifications&email_token=AOOBRJAMB3LIDZTUCOL5MF3RCGJCPA5CNFSM4KR2W7KKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELJP26Q#issuecomment-584252794>,
or unsubscribe

**Comment by surfnerd** [comment]
Hi @jli98dan,
Could you provide the version of ML-Agents you are using?  Please give us all the information you can when making a request.

**Comment by jli98dan** [comment]
Hi,
I have ML-Agents 0.14.0 version installed. I retrieved the library folder
and now I am not even able to add the package.JSON file when I select the
"Add package from disk" button under package management.
Thank you so much for your help and time!
Best,
Danielle Li

**Comment by surfnerd** [comment]
Hi @jli98dan, 
The version of Unity you are using is an alpha version of a tech release.  An alpha version means it's unstable, and having bugs is an expectation.  I recommend you upgrade to the actual release of 2019.3.  Please let me know if that helps you.
