### ISSUE TITLE
Self-play - Remember the ELO when --load-ing trainer

### ISSUE THREAD

**Issue by AcelisWeaven** [Unity-Technologies/ml-agents#3410]
**Is your feature request related to a problem? Please describe.**
When a self-play training session is interrupted then reloaded, the ELO graph starts back at 1200 (default ELO value).

**Describe the solution you'd like**
It may be better if the last ELO value was remembered, to avoid cliffs in the graphs.
I don't know about the technical side, but it may be possible to store the last value in a file alongside the checkpoint file, in the model, or getting it directly from the summaries.

**Comment by ervteng** [comment]
Hi @AcelisWeaven, thanks for the suggestion, I'll bring it up with the team and perhaps we can figure out how to do this cleanly. Glad the self-play feature is working for you!

**Comment by AcelisWeaven** [comment]
Thanks @ervteng !
I've got another question regarding self-play, should I make a question issue or post on the forums?

**Comment by ervteng** [comment]
Hi @AcelisWeaven, if it seems like a bug feel free to post it here - otherwise forums would be the best place so others can see it too.

**Comment by Ed1ezac** [comment]
I'm using ML-Agents v1.7.2 (Dec. 23 preview) which has the same issue.. The ELO self play rating always seems to revert back to the default 1200 when resuming training.. I doubt this has any effect on the learning progress of the agent though because it always seems to recover quickly but it would be nice to have a consistent value when resuming training

**Comment by ervteng** [comment]
This has been fixed - feel free to repost the issue if you're still having issues.
