### ISSUE TITLE
Recording imitation learning session at runtime

### ISSUE THREAD

**Issue by Fax3D** [Unity-Technologies/ml-agents#3486]
I would like to know if it's possibile, now or in the future, to record a session of imitation learning and use that record to train an agent during the "gameplay".

Image this scenario:
Users play a game recording a session to train an agent, the agent learn with imitation learning (in a separate, even long, background process) and then it can play. 
All this stuff is done during gameplay, because every user must be auto-capable of traing its agent AI.

Is this scenario possible? Or it will be in the future?

Thanks

**Comment by Fax3D** [comment]
Any news?

**Comment by vincentpierre** [comment]
I logged this request as MLA-1942.

**Comment by Ro-tico** [comment]
Is this current possible or still in developing stage?

**Comment by vincentpierre** [comment]
We will investigate at some point recoding demonstrations from built executables rather than the editor for imitation learning in Python. Regarding training at runtime, we currently rely on Python to perform training and do not have plans to support training within a built executable in C#. I do not know what this "separate, even long, background process" could look like. Maybe this would work if the user was willing to launch a Python learning process but I doubt it. 
Learning from real time data might be excruciatingly slow for a user to manage, I believe a difficulty adjustment setting would provide the same results for a fraction of the complexity.
