### ISSUE TITLE
The training speed in the 3DBall .

### ISSUE THREAD

**Issue by Johnzdh** [Unity-Technologies/ml-agents#365]
It takes me 1 hours to train the agent 50000 steps by tensorflow-GPU(1080TI * 4), but it only takes me 0.5 hour to train the agent 500000 steps by tensorflow-CPU(i7-6800K). It is too weird. Can somebody explain this?

**Comment by vincentpierre** [comment]
PPO is not optimized for GPU.

**Comment by awjuliani** [comment]
Hi @Johnzdh,

As Vince mentioned, our implementation is PPO is not well optimized for GPU. Unfortunately it is generally the case that on-policy RL algorithms are not very efficient from a GPU utilization perspective, since they have to wait for new batches of experience to be generated before those batches can be used for training. This is something we are aware of, and hope to have more optimized algorithms going forward, as better techniques come along.
