### ISSUE TITLE
The type or namespace name 'Sensor' does not exist in the namespace 'MLAgents' (error CS0234)

### ISSUE THREAD

**Issue by Blueeyesjt1** [Unity-Technologies/ml-agents#3668]
**error CS0234: The type or namespace name 'Sensor' does not exist in the namespace 'MLAgents' (are you missing an assembly reference?)**

I recently got a new computer and have tried to get MLAgents to work on this new one again. I have had experience with MLAgents so I know how to install Barracuda, Python, Anaconda, the 'pip install' items, and etc. I've noticed you guys switched to a package system now! Awesome. But for some reason, Unity is not registering the info in my script. **It also doesn't recognize "Agent" or "CollectObservations"** so it's clearly somehow disconnected. Yet, it DOES allow me to add the behavior parameters and such into the inspector.  Anyone got any idea of what the fix is? I've looked around- can't seem to find my solution online. Thanks! Am I still supposed to have some type of SDK in my assets folder? If so, I don't know where to find it.

* Using MLAgents v0.15.0
* Barracuda is updated to its latest version.

![image](https://user-images.githubusercontent.com/59098194/77321863-37594b00-6ce9-11ea-93d0-3095a1cb2e08.png)

![image](https://user-images.githubusercontent.com/59098194/77321922-4c35de80-6ce9-11ea-8e4d-03d829b00434.png)

![image](https://user-images.githubusercontent.com/59098194/77322004-6ec7f780-6ce9-11ea-995b-7a7c0b537243.png)

**Comment by chriselion** [comment]
Hi @Blueeyesjt1,

> Am I still supposed to have some type of SDK in my assets folder? 

No, you shouldn't need anything except for the package.

Couple of questions:
Can you confirm that you're on the 0.15.0 release of ml-agents? That was tagged with `0.15.0` in github, and the SHA (from running `git log`) should be `7507a5d3f5515ae7877eb3a3e9abaa2e2a270930`

Does your project's manifest.json have something like `"com.unity.ml-agents": "file:../../com.unity.ml-agents",`  in it? (the exact path might obviously be different).

Are there any other compiler errors? From the screenshot you posted, it looks like the ML-Agents assemblies might not have been compiled yet.

Can you try right clicking on the `ML Agents` package and click "reimport" (or right click anywhere in the explorer and try "Reimport All")?

You mentioned installing Barracuda, but this shouldn't be necessary anymore since it's a dependency of the ML-Agents package.

One other possible solution is to delete the Library folder from your project, just in case something is stale there.

**Comment by Blueeyesjt1** [comment]
> Hi @Blueeyesjt1,
> 
> > Am I still supposed to have some type of SDK in my assets folder?
> 
> No, you shouldn't need anything except for the package.
> 
> Couple of questions:
> Can you confirm that you're on the 0.15.0 release of ml-agents? That was tagged with `0.15.0` in github, and the SHA (from running `git log`) should be `7507a5d3f5515ae7877eb3a3e9abaa2e2a270930`
> 
> Does your project's manifest.json have something like `"com.unity.ml-agents": "file:../../com.unity.ml-agents",` in it? (the exact path might obviously be different).
> 
> Are there any other compiler errors? From the screenshot you posted, it looks like the ML-Agents assemblies might not have been compiled yet.
> 
> Can you try right clicking on the `ML Agents` package and click "reimport" (or right click anywhere in the explorer and try "Reimport All")?
> 
> You mentioned installing Barracuda, but this shouldn't be necessary anymore since it's a dependency of the ML-Agents package.
> 
> One other possible solution is to delete the Library folder from your project, just in case something is stale there.

Thanks for the response. I apologize for my own late reply. I, unfortunately, switched back to v13 prior to your response because of just my knowledge in using it. Once another version comes out- which I believe is version 1, I'll try to update again. Thank you.
