### ISSUE TITLE
Ability to Train networks on Jetson family of devices via TCP

### ISSUE THREAD

**Issue by ugurkanates** [Unity-Technologies/ml-agents#3720]
So I have a interesting scenario here. I have a lying TX2 at home with 8GB VRAM on it.
Instead of running simulations on cloud I thought why not do it via TX2 . My laptop has 2GB CUDA enabled  Ubuntu system (x86 64). It can run simulations fairly along with trained networks along side it. ( I did inference on unreal + 2 neural nets real time was 15-20fps)

So my plan was to somehow using ML agent to get frame of game and transfer via TCP and feed into neural net over there(Jetson) and predict some output , transfer it back and apply on simulation running on local laptop. 
I was thinking about a simple TCP server- connection structure about these connections.
But I have no idea if such a idea feasible or would it actually help the training or would latency prevent such improvement? But since more GPU memory available on Jetson I thought it would be more efficient ?

I also thought about sending a Gray scale or pre processed feature vector here for fast transfer (less data , more speed?) 

Also please think about ARM64 for Jetson support in future since why not , there is already ARM64 builds for android

Thanks & stay safe

**Comment by awjuliani** [comment]
Hi @ugurkanates 

This is an interesting idea. Given what you've shared though, it sounds more like a general question about Unity's capabilities, rather than an ML-Agents specific feature. It may be best to post this on our forum, where other users can discuss and share their ideas.

https://forum.unity.com/forums/ml-agents.453/

 Just from what you've described, I would imagine that sending image data over TCP to another device would likely reduce many of the gains you would expect from the extra processing power on that device.

I am going to close this issue here, but please feel free to re-open it on our forums.
