### ISSUE TITLE
pip install mlagent force install tensorflow-cpu

### ISSUE THREAD

**Issue by Wang-Tianyu** [Unity-Technologies/ml-agents#3729]
I already have tensorflow-gpu installed on my computer.
Installing mlagent via pip installs tensorflow-cpu on my computer and hide tensorflow-gpu from my system, which forces me to uninstall all tensorflow and reinstall the gpu version.

**Comment by awjuliani** [comment]
Hi @FinnickWang 

We recommend using a python virtual environment when installing and using ML-Agents because of conflicting dependency issues such as this. If you are new to virtual envs, we have a guide in our documentation here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Virtual-Environment.md
