### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.

### ISSUE THREAD

**Issue by yuta0306** [Unity-Technologies/ml-agents#4015]
**Describe the bug**
when I play 3Dball or RollerBall example, has error ->
Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.

**To Reproduce**
1. mlagents-learn config/trainer_config.yaml --run-id=exampleID
2. click play button

**Console logs / stack traces**
Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.
UnityEngine.Debug:Log(Object)
Unity.MLAgents.Academy:InitializeEnvironment() (at 

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: Unity 2019.3.14.f1
- OS + version: Mac 10.15.4
- _ML-Agents version_: ml-agents-release_2
- _TensorFlow version_: 2.2.0
- _Environment_: Anaconda virtual environment, installed all necessary package
-_python version_: 3.7.7

**NOTE:** 
I tried runing the mlagents-learn script, then clicked play button but it did not work.
I ran the mlagents-learn script at correct directory.

**Comment by egedursun** [comment]
Having the same issue on the same version of Mac OSx. Still couldn't manage to solve it.

**Comment by yuta0306** [comment]
Rebuilding the same environment, it works well. but the logs message is remained.

**Comment by egedursun** [comment]
I couldn't really understand. Did you rebuild the anaconda environment?

**Comment by yuta0306** [comment]
Yes. 
I destroyed the ml-agents environment, then build it again.

**Comment by unityjeffrey** [comment]
hi @yuta0306 - can you copy / paste the screenshot when you run mlagents-learn from the command line?

**Comment by unityjeffrey** [comment]
also - are you able to get training going?  is this message just popping up when you open the project?

**Comment by yuta0306** [comment]
<img width="1440" alt="スクリーンショット 2020-06-02 11 58 05" src="https://user-images.githubusercontent.com/54519381/83475209-d314ed80-a4c8-11ea-8269-e33da8a4641f.png">
<img width="1440" alt="スクリーンショット 2020-06-02 12 00 15" src="https://user-images.githubusercontent.com/54519381/83475224-dc9e5580-a4c8-11ea-9d8a-9a174b8a79e6.png">

I got training going and there is no error message on my console. I couldn't understand why the log disappeared.

My issue is resolved.

**Comment by Ugur0855** [comment]
ı have a same issue anyone??

**Comment by GcodeHub** [comment]
I have the same issue and I can't get to solve it

**Comment by AMGMNPLK** [comment]
Same problem.

**Comment by Lu-jiang** [comment]
THE same question， i cannot.....

**Comment by jdp1g09** [comment]
Also hitting the same issue: `Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.`.

Tried to rebuild my conda environment by removing from existing one, and then doing a fresh `pip install mlagents` - but still hitting the same problem.

The only other message I see that may be related, when pressing `Play` on the Unity Environment, I see: `"libgrpc_csharp_ext.x64.bundle" cannot be opened because the developer cannot be verified`. This seems to be another issues (raised [here](https://github.com/Unity-Technologies/ml-agents/issues/2306)). Not sure this is affecting anything here though, as I see no actual errors at runtime, but the Log described above regarding API version 1.0.0.

**Comment by jdp1g09** [comment]
For what it's worth - it seems that the `"libgrpc_csharp_ext.x64.bundle" cannot be opened because the developer cannot be verified` was in fact my problem. You can remove this error by following the instructions here: https://github.com/Cysharp/MagicOnion/issues/212

I then had to restart the `mlagents-learn` command with a new `run-id` and restart the Unity environment, and after that, it's training perfectly.

**Comment by orenong** [comment]
Same problem.
