### ISSUE TITLE
Python client freezes if exception is occured in game

### ISSUE THREAD

**Issue by SSS135** [Unity-Technologies/ml-agents#41]
Hi,
If exception is raised in C# code (at Agent.Step in my case), python client freezes at env.step() function. It would be nice to catch an exception, send it to python client, and raise it there. Or at least check for timeout in python client and raise an exception.
Curretnly timeout is disabled because of [```self._conn.setblocking(1)```](https://github.com/Unity-Technologies/ml-agents/blob/dc6480e80cd9f5c0c6aa564106cbaac492cd5c8d/python/unityagents/environment.py#L86) line. If it's replaced by ```self._conn.settimeout(10)```, timeout occurs as it should do.
Tested on Python 3.6 / Jupyter / Windows 10 x64.

**Comment by vincentpierre** [comment]
Hi, thank you for this feedback. We originally had  `self._conn.setblocking(1) ` replaced with `self._conn.settimeout(10)` but this cause other issues (mostly because the connection needs to be blocking). If you need to debug the C# code, you can:
 * Build a `development build` to see errors as they are raised. 
 * Use `Debug.LogError()` instead of `Debug.Log` to see errors in development build
 * Look for the [logfiles](https://docs.unity3d.com/Manual/LogFiles.html) on your machine to get C# errors at runtime
