### ISSUE TITLE
com.unity.ml-agents versioning inconsistent

### ISSUE THREAD

**Issue by DVonk** [Unity-Technologies/ml-agents#4114]
In the Package Manager there are a few preview versions, but the only one that isn't is 1.0.2. From what I understand the newest one to be used with Release 3 is 1.1.0, which is in preview.

I've also noticed that the dependency for 1.0.2 is Barracuda 1.0.0 and the dependency for 1.1.0 seems to have gone back to 0.7.1. I don't really get this versioning - which one should be used right now?

**Comment by chriselion** [comment]
Hi @DVonk,
This has to do with Unity's package process. ML-Agents v1.0.2 will be a verified package in the Unity 2020.2 release, which is why we dropped the "preview" suffix there. Any bug fixes between now and then can also be put into new patch releases, for example v1.0.3. We will continue to release new features and improvements as 1.x.y-preview packages (roughly once a month).

For the Barracuda dependency, verified packages aren't allowed to depend on preview packages, so Barracuda will also be a verified package in 2020.2. This is why ML-Agents 1.0.2 depends on Barracuda 1.0.0.

The fact that ML-Agents 1.1.0 depends on Barracuda 0.7.1 is an oversight; we should have updated the dependency before we released. If we do a patch release (1.1.1), we'll update the dependency there; otherwise 1.2.0 will depend on the latest Barracuda release at the time.
