### ISSUE TITLE
Tensorflow.NET integration

### ISSUE THREAD

**Issue by flo-wolf** [Unity-Technologies/ml-agents#4185]
**Is your feature request related to a problem? Please describe.**
I am unable to train agents during runtime _inside_ my builds, due to the python dependency. Currently ml-agents is Editor only.

**Describe the solution you'd like**
Tensorflow.NET integration, creating full C# training support, allowing for runtime (live) training in builds.

**Describe alternatives you've considered**
Bundling python into the build, which is very convoluted and creates a unnessessarily complex pipeline, which .NET integration would prevent.

**Additional context**
Since Tensorflow.NET mimics all the possibilities you get from the python tensorflow, there would be no drawbacks in terms of features. Tensorflow.NET even includes its own version of NumPy fully translated into C#. I don't understand why this isn't considered. If it's possible to stick with only C#, why not go for it?

**Comment by lostmsu** [comment]
@flo-wolf you can try [LostTech.TensorFlow](https://ml.blogs.losttech.software/TF-1.15-Release-Candidate/) that I just released. We have a [ML Agents demo](https://ml.blogs.losttech.software/Reinforcement-Learning-With-Unity-ML-Agents/).

However, TensorFlow does not do well with `AppDomain` unloading and reloading, that Unity editor uses extensively. So you can use it in your game, but trying to use it in the editor will simply crash the editor. The demo I mentioned connects to the editor from outside - that works fine, and, honestly, easier to set up, since you can use NuGet to reference the necessary packages.
