### ISSUE TITLE
Would it be possible to automatically adjust the Vector Space Size based on the number of received observations?

### ISSUE THREAD

**Issue by HPRIOR** [Unity-Technologies/ml-agents#4281]
It would be nice to be able to opt in to the automatic configuration of the observation space size.

**Comment by chriselion** [comment]
Hi @HPRIOR 
That's a reasonable request; it's come up before internally, but I'm not sure if we have it logged in our tracker anywhere.

Just to be clear, you would still need to have the same number of observations every step, and for all Agents with the same behavior name.

One possible downside is that it would make checking that a barracuda model was the right size for the Agent, since we wouldn't know the observation size in advance.

If keeping track of the the observation size is annoying, I have two suggestions:
1) Use SensorComponents and ISensors. These are responsible for determining their own size, so any changes in their settings don't require changes to the BehaviorParameters. The RayPerceptionSensor and RayPerceptionSensorComponent3D are good examples of this.
2) Set it too large, start training, and there will be a warning telling you the actual number of observations written (I'm not too proud to admit that I did this recently because I was too lazy to add up the number of AddObservation calls).

**Comment by chriselion** [comment]
This is now logged as MLA-1214 in our internal tracker.
