### ISSUE TITLE
[Resolved] Move object with movement * Time.deltaTime ?

### ISSUE THREAD

**Issue by Fangh** [Unity-Technologies/ml-agents#444]
Hello.
I have a moving object that move with transform.Translate(myVector3 * Time.deltaTime);
and I want to train my ML to flee this object.

But when I launch the training with my parameters like this : 
![image](https://user-images.githubusercontent.com/6020679/37338205-0bd2ac62-26b7-11e8-8ba6-5ca4267a1e27.png)
it is so different than 
![image](https://user-images.githubusercontent.com/6020679/37338222-16c49202-26b7-11e8-8e30-78543740bedf.png)

because in the first case, my moving object goes WAY OFF my screen, like it has a really high speed. Or maybe it's the contrary, because the time is not "normal".
But in the first case, to finish the training, it take WAY less time.

The only solution I found is to train my AI with the second case parameters (60FPS, TimeScale = 1) but it seems to be a bad idea because it seems to be WAY too much time to train my ML.

What should I do to train my ML in a correct amount of time ?

**Comment by ruanrothmann** [comment]
You should put all of your game logic in FixedUpdate.

**Comment by Fangh** [comment]
I just read this doc : https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Organizing-the-Scene.md

And I think I should put my game Logic in AcademyStep().

What is the correct way to do ?

**Comment by ruanrothmann** [comment]
They mean that if you want to modify the training setup, you should do it in academystep. Modifying the game world should happen in fixedupdate. Time.deltatime in FixedUpdate is always the same (equal the the setting under Project Settings -> Time) where Time.deltaTime in Update is equal to ( real world time since last update) * Time.timescale. 

Simply use FixedUpdate instead of Update in all your game logic classes and everything should work as expected :)

**Comment by Fangh** [comment]
Thank you !

**Comment by Fangh** [comment]
oh yeah the "official" answer is right here : https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Limitations-&-Common-Issues.md
