### ISSUE TITLE
Make everything in C# and HLSL and train after building game!

### ISSUE THREAD

**Issue by SabRango** [Unity-Technologies/ml-agents#4528]
Currently I am trying to custom brain, and I noticed that It's kinda possible to reach advanced  system after training days, weeks!
So there is great demand for create system in C# and HLSL, all brain model and training system are together in Unity,  and build the game for a hardware. Then teach the model for weeks, month, years that will never stop from learning!!!

That would be great if all of the learning system created in C#,HLSL, and  make a game that never stops from learning!!

**Comment by hvpeteet** [comment]
Thanks for taking interest in the project, there have been other posts as well that took an interest in runtime-learning. While I think we all agree that this would be awesome it is not currently a priority due to the large scope of the problem. For the purposes of long-term interest tracking I am including our internal tracking info, but this is not something that we have any plans to work on in the foreseeable future.

runtime-learning: MLA-1445

**Comment by karolwieczorek** [comment]
I don't think that writing everything in c# is the solution but I would also like to have ability to train custom brain at runtime. So that I can let players train their own custom brains. 
+1 for runtime-learning: MLA-1445
