### ISSUE TITLE
Runtime Learning! And Drop Python Dependency All Together Please.

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#4541]
The Installation Procedures are still not clear for windows, what are the dependencies? please update and clarify the documentation. Also, any progress on runtime learning? I want to make a pet app that constantly learns?

**Comment by hvpeteet** [comment]
Thanks for reaching out, do you have any specific install issues (where our instructions don't work for windows)?

While it would be amazing to have these features (runtime learning and removing python install pain) they are not feasible at this time. I am including internal tracking numbers for both below so that we can track interest long-term.

runtime-learning:  MLA-1445
simplifying ml-agents install: MLA-1446

**Comment by RedTachyon** [comment]
I installed ml-agents on Windows just a couple days ago without many problems and everything works well, so I think it's alright? I believe pip install + adding the Unity package inside of Unity works perfectly.
