### ISSUE TITLE
Need help with reward function

### ISSUE THREAD

**Issue by tschmidt64** [Unity-Technologies/ml-agents#455]
I have a flight simulator, and I'm trying to do a simple RL proof of concept to get the plane to stay within a certain velocity range. I'm having a lot of issues with even the simple concept though. Could anyone help?

The 3 available discrete actions I've given the plane are ['increase throttle', 'decrease throttle', 'none'] which each adjust the throttle value along the range [0,1] by a certain value. 

The seven continuous state variables I'm providing are the current velocity (each dimension individually, normalized to [0,1]), the previous velocity (each dimension individually, normalized to [0,1]) and the current value of the throttle. 

My reward function is roughly:
```
if velocity is within desired range:
    reward = 0.5
elif velocity below desired range:
    if velocity is increasing:
        reward = 0.1
    else:
        reward = -0.1
elif velocity above desired range:
    if velocity is decreasing:
        reward = 0.1
    else:
        reward = -0.1
```

I have made sure the episode ends after 500 steps, so I want to maximize reward within the 500 step limit.
I also have it terminate if the velocity goes above 100, so that I know the min/max velocities so I can normalize the state input velocities.

I thought this would be a simple proof of concept, but I'm not having any luck training. I've tried adjusting the parameters per the [best practices](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/best-practices-ppo.md) page, but I've had no luck. My cumulative reward doesn't seem to trend in any particular direction
![rewards_ppo_009](https://user-images.githubusercontent.com/5597930/37375128-41d4478c-26ec-11e8-8305-6a6536719dc3.PNG)

**Comment by CowboyCoderForever** [comment]
I've been trying some basic "stay at velocity" concepts as well, with partial success. Here are some tips:
-  ensure *you* can actually do the task. Set the Brain Type to player and watch your reward values as you play the scenario.
-  It seems the less state variables you give it, the easier it learns.
-  Are you sure 500 steps is enough?

I was able to get a cube spinning to a targeted angular velocity pretty easily by supplying just one state variable (the [-1,1] difference between current and the target velocity, normalized). The reward is +0.1 when the velocity is in range, -0.1 otherwise. I set the agent Max Step of 5000 and used one continuous action (the throttle). And I never set done=true. ::shrug::

Hope this helps
-Erik

**Comment by tschmidt64** [comment]
You never set done = true? How does that work? Is the training just one long episode then?

**Comment by CowboyCoderForever** [comment]
You know, I'm a little confused by that as well. The Academy has a maxSteps and the Agent has a maxStep.

As I understand it, the Agent will automatically be "done" if Agent.maxStep is set to something other than zero. Otherwise, you have to manually set done=true at some point.

In my test case, I was having troubles calculating when the agent should be done so I just ran it for some fixed number of agent steps.

**Comment by UsaidPro** [comment]
Doing done=true tells the python script to reset the environment. Doing a max_step forcibly sets the done = True in my experience. The Academy's max_steps is how long the environment would run before calling its reset. The Agent's max_steps is how long the agent runs before calling *its* reset. So if you have multiple agents, using the agent's reset is better and the academy reset is for restarting everything.

**Comment by mushketer888** [comment]
I have the same problem with autonomous quadcopter  simulation...
My reward function:
`if (WrapAngle(transform.rotation.eulerAngles.x) > 30 || WrapAngle(transform.rotation.eulerAngles.z) > 30) { AddReward(-1f);Done(); } //bad angle of coptor

        float dist = Vector3.Distance(goal.transform.position, transform.position);
        dist = Mathf.Abs(dist);

        float bonus;
        bonus = (olddist - dist) / olddist;//olddist is distance to goal on InitializeAgent
      
        Monitor.Log("Bonus", Mathf.Clamp(bonus, 0, 1), MonitorType.slider, transform);
        AddReward(Mathf.Clamp(bonus, 0, 1) * 0.5f);
        AddReward(-0.00001f);

       //do i need it?
        //if (GetStepCount() > 500 && transform.position.y < 6.5) { SetReward(-1f);  }

        //if too far
        if (bonus < -0.3) { SetReward(-1f); Done(); }
`
Is my reward function OK?

**Comment by mushketer888** [comment]
I get this
![screenshot_2](https://user-images.githubusercontent.com/2189038/37786807-38e3945e-2e06-11e8-9a2c-b07f96ca3a02.png)
