### ISSUE TITLE
Lags with Sac+demo_path+camerasensor (Object.wrapper_native)

### ISSUE THREAD

**Issue by M1raclee** [Unity-Technologies/ml-agents#4564]
**Describe the bug**
When i'm training my agent with SAC trainer (GAIL) and Camera Sensor (optional, without this there are lags too, but a little less) i'm getting lags with CPU > 10.000 ms. Last item in profiler stack trace is "Object.wrapper_native_0x16442edf0()" with largest self ms.
The more agents on the stage, the more CPU time need.
For this test i'm using 5 agents on scene.
If i'm using ppo trainer - i can put more 40 agents on scene without lags.

**To Reproduce**
1. Select SAC trainer with my config
2. Create agent and attach "Camera Sensor Component" (default settings) and Decision requester(period - 10) - agent for training
3. Record any demo for 1-2 min
4. Place 3-5 agents on scene.
5. Enable training.
6. See profiler with enabled "Deep Profile" button (lags start in 10-15 seconds)

**Console logs / stack traces**
Main params:
```
hyperparameters:
batch_size: 256
buffer_size: 250000
learning_rate: 0.0003
tau: 0.005
network_settings:
normalize: true
hidden_units: 128
num_layers: 2
gail:
gamma:0.99
strength:0.01
encoding_size: 128
learning_rate: 0.0003
use_actions:true
demo_path: your/demo/path
```

**Screenshots**
<img width="1320" alt="lags" src="https://user-images.githubusercontent.com/49681421/95948123-a36fdd80-0df8-11eb-95cb-d84fbdb7c653.png">

**Environment (please complete the following information):**
- Unity Version: 2019.2.17f1
- OS + version: macOS 10.15.7 (iMac 27-inch, 2019)
- _ML-Agents version_: v1.4.0-preview
- _TensorFlow version_: 2.3.1

**Comment by vincentpierre** [comment]
Hi,

SAC can be computationally more expensive than PPO because it does back-propagation more frequently (since it can use old data, the buffer is not emptied and many more updates are performed). 
You can alleviate this to some extent by increasing the [steps_per_update](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Configuration-File.md#sac-specific-configurations) hyperparameter. ([See this configuration for example](https://github.com/Unity-Technologies/ml-agents/blob/master/config/sac/3DBall.yaml#L11))
