### ISSUE TITLE
Please implement running Barracuda inference models as an asynchronous operation

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#4577]
**Is your feature request related to a problem? Please describe.**

In ModelRunner.cs, running a model appears to be implemented as a blocking operation.
```
        public void DecideBatch()
        {
            ...
            m_Engine.Execute(inputs);
            ...
        }
```

If the model is large (512x3 layers), this blocks the main thread for several milliseconds while the model is executed.

**Describe the solution you'd like**
Please implement this so that the model is executed Asynchronously. As I understand it, if the inference device is set to GPU, then the CPU is essentially sitting idle waiting for the GPU to do its work. The CPU should be available to do other tasks while the GPU is doing its work.

**Describe alternatives you've considered**

**Additional context**
On my powerful desktop machine, a 512x3 layers model takes blocks for 3 milliseconds waiting for the GPU to execute.

**Comment by vincentpierre** [comment]
Hi,

We logged this request as MLA-1478 and we will prioritize when appropriate. I think this would be a super cool feature, but it would require changing the API quite a bit since currently, there is no room for user code (one the main thread) between the data being sent to barracuda and the actions being received by the Agents. I think that would require a more flexible API than the one we currently have (and that we will be working on). I also see this as being useful during training since Unity is blocked between sending observations and receiving actions as well.

**Comment by Phong13** [comment]
Thanks for the super fast response :).
