### ISSUE TITLE
MemoryError during training when allocating an Observation matrix

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#4601]
Hi there!

**Describe the bug**
During training, after a certain amount of time (and timesteps), a MemoryError message is raised:
```
[...]
2020-10-23 07:53:08 INFO [stats.py:118] AgentBehaviour. Step: 434000. Time Elapsed: 7228.941 s. Mean Reward: -3.797. Std of Reward: 0.500. Training.
2020-10-23 07:53:12 INFO [stats.py:118] AgentBehaviour. Step: 435000. Time Elapsed: 7232.077 s. Mean Reward: -4.296. Std of Reward: 0.000. Training.
2020-10-23 07:55:08 INFO [stats.py:118] AgentBehaviour. Step: 436000. Time Elapsed: 7348.387 s. Mean Reward: -5.296. Std of Reward: 0.000. Training.
2020-10-23 07:55:14 INFO [stats.py:118] AgentBehaviour. Step: 437000. Time Elapsed: 7354.295 s. Mean Reward: -5.296. Std of Reward: 0.000. Training.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\users\Dastyn\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\Dastyn\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 296, in trainer_update_func
    trainer.advance()
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\trainer\rl_trainer.py", line 319, in advance
    if self._update_policy():
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents_envs\timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\sac\trainer.py", line 218, in _update_policy
    self._update_reward_signals()
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\sac\trainer.py", line 372, in _update_reward_signals
    reward_signal_minibatches, n_sequences
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\sac\optimizer_tf.py", line 557, in update_reward_signals
    update_vals = self._execute_model(feed_dict, update_dict)
  File "c:\users\Dastyn\anaconda3\lib\site-packages\mlagents\trainers\optimizer\tf_optimizer.py", line 158, in _execute_model
    network_out = self.sess.run(list(out_dict.values()), feed_dict=feed_dict)
  File "c:\users\Dastyn\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)
  File "c:\users\Dastyn\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1150, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\users\Dastyn\AppData\Roaming\Python\Python37\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError: Unable to allocate 14.6 MiB for an array with shape (128, 50, 50, 12) and data type float32
```

**Environment:**
- Unity Version: Unity 2019.4.12f1
- OS + version: Windows 10
- ml-agents: 0.21.0,
- ml-agents-envs: 0.21.0,
- Communicator API: 1.2.0,
- TensorFlow: 2.2.0
- package version 1.5.0-preview and communication version 1.2.0

**Question(s):**
I did several tries on this and got the same issue.
Downsizing the observation shape is not an option at this time.
Downsizing the batch_size (within the yaml configuration file) could be more an option, but before trying again for hours, I would like the instrument the SAC trainer code with some kind of psutil (so under Linux this time) at the right place.
Could you please give me some hints to track down this issue, in that way or another, and find out where some garbage collection (?) might not be done correctly? 
Thanks in advance for any help!

**Comment by chriselion** [comment]
Hi @Dastyn 
Reducing the `buffer_size` might help too.

14.6 MiB isn't _that_ big, so I'm assuming something else is eating up all your memory. We've had leaks in python before, but there are no known problems at the moment. It could also be coming from your Unity environment.

If you want to add some tracking with psutil, a good way to do this would be to add it as a stat so that it appears in tensorboard; that way we can see how it changes over time. A simple place you could add this is bu using a `stats_reporter` around here:
https://github.com/Unity-Technologies/ml-agents/blob/b7d2b808de1072dc563b6da70cbf2b8fa6a365bc/ml-agents/mlagents/trainers/trainer_controller.py#L245

I've heard that https://mg.pov.lt/objgraph/ is good for debugging these sorts of python leaks, but I've never used it myself.

Can you also attach the config file that you're using? If you can reproduce the behavior using that config and one of example environments, that would help us debug it more easily.

Thanks!

**Comment by Dastyn** [comment]
Thank you @chriselion for your help.
These are some complements and results.

First, this is below the config.yaml file used for the tests:
```
behaviors:
  AgentBehaviour:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.005
      learning_rate_schedule: constant
      batch_size: 128 
      buffer_size: 512000
      buffer_init_steps: 1000
      tau: 0.01
      steps_per_update: 100
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    behavioral_cloning:
      demo_path: agent.demo
      strength: 0.5
      steps: 50000
      num_epoch: 10
      batch_size: 128
    reward_signals:
      curiosity:
       strength: 0.2
       gamma: 0.99
       encoding_size: 256
       learning_rate: 1e-5 
      extrinsic:
        gamma: 0.995
        strength: 0.9
      gail:
        gamma: 0.99
        strength: 0.1
        encoding_size: 256
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: agent.demo
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 1000
    threaded: true
```

My case study uses visual observations, thanks to an ISensor (called by a SensorComponent) writing visual observations with shape = (50,50,12), for ('simple') CNN encoding.

Then, this is the screenshot of available virtual memory, as provided by psutil, on my case study, just before the same crash as described above:
![Capture](https://user-images.githubusercontent.com/36076511/97080086-22cf8f00-15f9-11eb-9d91-b16f694b637d.PNG)
Available virtual memory is captured in sac / trainer.py, in functions: _process_trajectory(), update_reward_signal(), and update_sac_policy().

Last, I did not succeed in recording demos of VisualPyramids example (which should share many important features with my own case study), due to some crashes as soon as 'play' button is pressed into the Editor. I did not investigate this point so far.
Note that the demo file provided with the Examples does not correspond to (not the same observation shape, or not for the Visual version of the example indeed).
This said, the executable VisualPyramids version does not raise the same issue.
But as there was no demo file available, the yaml config file used here did not contain BC and GAIL sections.
Then, not so representative ...

I will go on testing, but any thoughts in the meantime about this issue will be very welcome!
Thanks in advance.

**Comment by sebastianulm** [comment]
I have the same Probem, I guess? 

Currently just starting out with MLAgents I keep running into memory leaks when doing ANYTHING with visual observation. So I checked out master, opened the GridWorld example and increased the Render Texture (and camera sensor) size to 480x255. 
After about a Minute the mlagents-learn process consumes 12+ Gigabytes of ram and still increases by about 200+ mb every few seconds. 

Yes, thats a "bit larger" image, but my current solution (homebrew) just eats it fine. So I cannot imagine that this should not be possible. Same as above guy, reducing this is not an option.
 
Using Unity 2019.4.4f1 on 5.9.1-2-MANJARO (Linux) but its likely the same on Windows.

**Comment by chriselion** [comment]
Hi folks,
Sorry for the delay; there's a lot going on here.

> I did not succeed in recording demos of VisualPyramids example (which should share many important features with my own case study), due to some crashes as soon as 'play' button is pressed into the Editor. 

Do you have a stack trace for this? Pressing play in VisualPyramids works for me (although the agent falls back to keyboard control since there's no model), and I was able to add a DemonstrationRecorder and save demonstrations.

---

As for memory: the buffer that stores the observations is going to dominate the memory usage. My back of the envelope math says that we need
`(buffer size) * (height * width * channels floats) * (4 bytes per float)`
bytes to store the visual observations.

@Dastyn In your case, that's 512000 * 50 * 50 * 12 * 4 = 61.44 gigabytes. I'm guessing the reason the virtual memory levels off around 250K steps is that it starts spilling to swap.

@sebastianulm You didn't say what trainer you're using. For SAC, with the buffer size in the GridWorld config file, that's 50000 * 480 * 255 * 3 * 4 = 73.44 gigabytes.

If you're passing float observations (which it sounds like @Dastyn is), I don't think quantizing them to save space would be a good choice. For observations that arrive as PNGs, we currently store them as uncompressed numpy float32 arrays, which is inefficient (we should either keep the compressed or as uint8 arrays). I'll log a feature request to handle that better.

In the meantime, if you're not able to reduce the size of your observations, I think you'll either need to shrink the buffers and/or use PPO instead of SAC.

**Comment by chriselion** [comment]
I added MLA-1518 to our internal tracker to explore how to reduce the memory from compressed observations in the buffer.

**Comment by Dastyn** [comment]
Hi @chriselion,

I reduced the batch_size and the buffersize: it works now with SAC (PPO does not yield good results at first glance, on my case study).
As you mentioned, reducing the memory from compressed observations would be welcome.

Thank you for your help,
Dastyn

P.S. : W.r.t. VisualPyramids, I finally succeeded in launching DemoRecorder on the game (I don't know what went wrong before!). I will spend a bit of computation time to see if it makes crash the memory.
