### ISSUE TITLE
Configurable info for python and gym interface

### ISSUE THREAD

**Issue by ShirelJosef** [Unity-Technologies/ml-agents#4619]
**Is your feature request related to a problem? Please describe.**
It can be difficult to debug complex behaviors without receiving more output from the environment other than the agent observation. For example, in a racing game with only visual input to the network, I still want to be able to get info about the cars locations, speed and so for debug purposes.

**Describe the solution you'd like**
For the python interface of the environment and Gym interface, it would be nice if from each step call, you can receive configurable output (by the user) from the environment.

**Describe alternatives you've considered**
None

**Comment by ervteng** [comment]
Hi @ShirelJosef, it's a bit harder with the Gym interface because gym is much more limited in what you can pass. 
If you're using the Python-API, there is a stats_side_channel that you can instantiate on the Python side and call to get stats. 

Then on the C# side you can add stats following this here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Tensorboard.md#custom-metrics-from-unity

You can also make your own side channels: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Custom-SideChannels.md
