### ISSUE TITLE
Group `agent_id`s by training area

### ISSUE THREAD

**Issue by tomtung** [Unity-Technologies/ml-agents#4660]
**Is your feature request related to a problem? Please describe.**
Methods like [MADDPG](https://arxiv.org/abs/1706.02275) and [COMA](https://arxiv.org/abs/1705.08926) requires access to observations and actions from all agents in the same training area. However, for multi-agent environments with multiple parallel training areas (e.g. Tennis), it seems like there's no reliable way to tell which agents are playing with / against which other agents, so only localized observations and individual actions of each agent are separately accessible.

**Describe the solution you'd like**
It's probably sufficient to have a method called something like `agent_ids_grouped_by_training_area() -> List[List[AgentId]]` in the `UnityEnvironment` class.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dongruoping** [comment]
Yes I agree that would be something useful for multi-agent training, thanks for raising this.
This is something on our roadmap and I'll bring this up with the team.

**Comment by dongruoping** [comment]
Update: The latest ML-Agents [Release 15](https://github.com/Unity-Technologies/ml-agents/tree/release_15) has offered new API `MultiAgentGroup` to achieve this and our new trainer supports cooperative behaviors training.
Please refer to our [documentation](https://github.com/Unity-Technologies/ml-agents/blob/release_15_docs/docs/Learning-Environment-Design-Agents.md#groups-for-cooperative-scenarios) or checkout the new example environments: [Cooperative Push Block](https://github.com/Unity-Technologies/ml-agents/blob/release_15_docs/docs/Learning-Environment-Examples.md#cooperative-push-block) and [Dungeon Escape](https://github.com/Unity-Technologies/ml-agents/blob/release_15_docs/docs/Learning-Environment-Examples.md#dungeon-escape).

Closing this issue since it has been resolved.
