### ISSUE TITLE
Walkthrough of PPO

### ISSUE THREAD

**Issue by Lakrix** [Unity-Technologies/ml-agents#467]
Hi @awjuliani,

Thanks for the awesome work with ml agents in unity. I'm curious if you are planning to do a similar explanation post about the PPO algorithm in detail like you did with A3C on medium? 

Cheers

**Comment by awjuliani** [comment]
Hi @Lakrix,

I am glad to hear that you've appreciated some of my other blog posts. I currently don't have a plan to do one on PPO, as it is very similar to A3C, except that includes a special loss term to encourage more stable training. It also isn't parallel like A3C, but otherwise there aren't enough differences to warrant a full post. I'd recommend checking out OpenAI's blog on the topic, if you are interested to learn more: https://blog.openai.com/openai-baselines-ppo/
