### ISSUE TITLE
Display steps per second

### ISSUE THREAD

**Issue by CubeMD** [Unity-Technologies/ml-agents#4683]
**Is your feature request related to a problem? Please describe.**
Time is a valuable resource when working with ML-Agents. One of the things which influence the speed of training is the speed at which new steps are being generated. There are a few ways described in the documentation to increase this metric, such as making multiple environments within a single executable, adding num-envs parameter, and changing time scale. Playing around with these values before starting a long run might save time, especially if there will be several long runs. To achieve the best performance, this needs to be done per machine as the results highly depend on the hardware configuration.

At the moment the only way to figure out the quality of the setup is to make the calculation manually.

**Describe the solution you'd like**
It would be nice if this value was either printed in the cmd along with other information or even better tracked in tensorboard (I occasionally saw fluctuations in this value, which indicated that errors were generated), as cmd is getting quite busy.

**Describe alternatives you've considered**
It would be amazing if the number of environments and time scale were adjusted automatically to achieve the best performance. But I think this feature would require enormous amounts of work.

**Comment by Ihsees** [comment]
I agree. 

I have thought about this feature as well and realized that there are many different metrics to track which all correlate to each other, but are dependent on "--num-envs", the number of agents in one scene, and even the "Decision Period".

From the top of my head I can think of
FixedUpdateSteps / s in Unity
AcademySteps / s  in Unity (same as FixedUpdateSteps?)
AgentSteps / s in Unity (which is different than "AcademySteps", depending on the number of Agents per Scene, and the Decision Period)
Decisions / s in Python (which is higher than "AgentSteps", depending on "--num-envs")
Observations / s in Python (this should be the same as "Decisions / s")

Having said that, if there was a way to track Python-"Decisions / s" in Tensorboard, this would really help me as well (I'm currently sitting here tracking these manually)

**Comment by CubeMD** [comment]
@ihsees Hi, thank you for bothering with a bump. I think that decisions per second is more descriptive than my steps or any of other metrics you mentioned.

**Comment by andrewcoh** [comment]
Thanks for the thread @CubeMD @Ihsees .

Just to be sure we are all on the same page, 1 step in python corresponds to 1 decision period for one agent in C# and the decision period is the number of fixed updates between decisions.

As to tracking these things manually, you can add your own stats to Tensorboard from C# https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Tensorboard.md#custom-metrics-from-unity (unless that's what you're already doing).

I don't think there's a way to optimize this in general since it will be highly dependent on each individual problem.

As far as alternative stats to measure step throughput, I can share some of your ideas with the team.
