### ISSUE TITLE
Training on server build with visual observations and multiple GPUs

### ISSUE THREAD

**Issue by KevinWu57** [Unity-Technologies/ml-agents#4874]
I am running my custom mlagents environment on a server with a Unity server build. However, I have some problems with this server build that hope to be answered:

- I am using visual observations in my environment. However, the server has no monitor therefore it is not able to render the images. If I build in a headless mode, there will no visual output. Is there anyway that I could run it in a headless server with visual observations? I have been stuck in this for several days and any help or suggestions will be greatly appreciated!
- I have multiple GPUs (4 RTX 2080) on my server and I am wondering if mlagents can configure to use all or part of them. Since I have heavy visual inputs, and I changed your CNN to a more complex MobileNet, I may need to use multiple GPUs. If not, is there another way you might have to realize this?

Thank you!

**Comment by KevinWu57** [comment]
If I build the environment without headless mode, it will always output `UnityTimeOutException` on the server.
![image](https://user-images.githubusercontent.com/46989361/105245116-4b96f000-5b26-11eb-9e8c-65fcb85d1b37.png)

**Comment by chriselion** [comment]
Hi,
You'll need something like `xvfb` to do visual observations on a remote machine. There's an example of setting this up in the collab notebook [here](https://colab.research.google.com/drive/1Qg6E5kmf9n4G8rc5lXHIM_cQzMUFGH-g#forceEdit=true&sandboxMode=true&scrollTo=htb-p1hSNX7D) (under the "setup" section).

We don't currently support multiple GPUs for training. We have a request for this logged already as MLA-662 in our internal tracker, but there's no timeline for implementing it.

Torch will use a single GPU as long as its set up correctly. You’ll need to install a torch version that is compatible with your CUDA version, though - otherwise it won’t detect your GPU devices and will run on CPU instead.

**Comment by chriselion** [comment]
Discussion migrated to https://forum.unity.com/threads/ml-agent-server-build-headless-with-visual-observations-and-multiple-gpus.1042456/
