### ISSUE TITLE
Build with multiple scenes

### ISSUE THREAD

**Issue by qiwu57kevin** [Unity-Technologies/ml-agents#4875]
Hi! I am just wondering if you have a plan to support a Unity build with multiple scenes. MLAgents currently can only build with one scene selected, where you may have duplicate environments (like the example games) and agents. However, sometimes building with multiple scenes can be helpful when you want to access a specific environment, e.g. from Python scripts, and you can still train with different scenes.

I am building multiple complex environments for some embodied navigation tasks. I work around the request mentioned above by either activate/deactivate gameobjects in the scene or destroy/instantiate prefabs from Assets. For now it looks good, but I still want to know if you may support building with multiple scenes or you have done something to address this. Thank you!

**Comment by chriselion** [comment]
Hi @KevinWu57,
There's nothing in ML-Agents that prevents you from using multiple scenes. For some of our internal tests, we build with all of the example scenes, then use command-line args to switch to the desired scene using [this script](https://github.com/Unity-Technologies/ml-agents/blob/release_12/Project/Assets/ML-Agents/Examples/Startup/Scripts/Startup.cs).

**Comment by KevinWu57** [comment]
Hi @chriselion ! Thanks for your response!

I see what you mean here. If I understand correctly, you build a startup scene where you have [this script](https://github.com/Unity-Technologies/ml-agents/blob/release_12/Project/Assets/ML-Agents/Examples/Startup/Scripts/Startup.cs) attached. You pass scene name from command line and this script will load the scene with the `Awake` function call.

I have a question here about switching between scenes in the build: if I want to switch between scenes during training, say at the new episode. Does it mean that I need to call `LoadScene` from each scene `OnEpisodeBegin()` so that a new scene can be loaded?

**Comment by chriselion** [comment]
> If I understand correctly, you build a startup scene where you have this script attached. You pass scene name from command line and this script will load the scene with the Awake function call.

Yeah, we add all the example scenes to the build, along with [this scene](https://github.com/Unity-Technologies/ml-agents/blob/release_12/Project/Assets/ML-Agents/Examples/Startup/Startup.unity) as the first scene.

> I have a question here about switching between scenes in the build: if I want to switch between scenes during training, say at the new episode. Does it mean that I need to call LoadScene from each scene OnEpisodeBegin() so that a new scene can be loaded?

I'm not that experienced with Unity's scene management. I think what you described is fine, as long as it doesn't destroy the Agent as a side effect (since that will end the episode for the Agent again). Regardless, I don't think there's anything ML-Agents-specific about scene management.

---

Historical note: in old versions of ML-Agents, the Academy was an abstract class that you had to have an instance of in the scene, and _that_ was problematic for multiple scenes. But the Academy has been a singleton since early 2020.

**Comment by KevinWu57** [comment]
@chriselion I tried to switch scenes from OnEpisodeBegin and it works fine. The only problem is that, OnEpisodeBegin will be called at the start of each episode to initialize the agent, therefore I need to avoid switching scenes recursively.

As you mentioned, the Academy is not a singleton therefore there is not need to create an instance. For Academy's `OnEnvironmentReset` delegate, does it mean that this action will be called at the begining of each episode, regardless of single scene or multiple scenes? I think I can also add an action to switch scenes to `OnEnvironmentReset`.

**Comment by chriselion** [comment]
OnEnvironmentReset() is only at the the very beginning of training and when the trainer issues a full reset, which doesn't happen under normal circumstances (only when using curriculum).

Instead of triggering the scene change from an Agent's OnEpisodeBegin, I'd recommend you do something like destroying the Agent when it's done, triggering the scene change, and then instantiating a new Agent. That should handle the problem you described about switching recursively.

**Comment by KevinWu57** [comment]
@chriselion Ok I see. That explains why the environment didn't change at the beginning of each episode when I add a reset function to OnEnvironmentReset().

I would take your recommendations by destroying the agent and triggering the scene change there (e.g., from OnDisabled()?). Hope that can solve this recursive issue.

**Comment by miguelalonsojr** [comment]
Please post this on our forums if you still need help. https://forum.unity.com/forums/ml-agents.453/
