### ISSUE TITLE
Multi-cpu setup

### ISSUE THREAD

**Issue by Remi-Niel** [Unity-Technologies/ml-agents#4902]
I'm looking into setting up a machine specifically for training an agent in a complex environment. To this end I was wondering how well ml-agents scales when running on multiple CPUs.  

1 option would be a dual 64 core AMD EPYC setup, my questions would then be: 

- How well can the python side of the equation handle communicating with 128+ envs? 
- How well can ml agents handle the situation of a unity instances running on CPUs?

Does anyone have experience running ml-agents at this kind of scale? And if so what kind of problems did you encounter?

**Comment by awjuliani** [comment]
Hi @Remi-Niel 

Because it is not a feature request or bug, I think you may find a better audience for your question on the official forums: https://forum.unity.com/forums/ml-agents.453//. 

That being said, depending on the specifics of your environment, you should find that having more cores on your machine will allow you to run more instances of the environment, and thus collect more observations per second. One potential bottleneck however may be rendering. Especially if you are using visual observations, there may be less than ideal scaling with the number of cores. That being said, concurrent environments are run in parallel on the python side, so there are no inherent bottlenecks to the kind of scaling you are interested in.

**Comment by dongruoping** [comment]
Closing this issue and please feel free to open up a post in forum if you have further question.
