### ISSUE TITLE
Use a namedtuple (or something similar) for distinct sensors in the Python API

### ISSUE THREAD

**Issue by RedTachyon** [Unity-Technologies/ml-agents#5011]
**Is your feature request related to a problem? Please describe.**
This is more of a quality-of-life request, but also to prevent possible errors because it's not clear to me what to expect.

When you call `.get_steps(...)`, you get the decision and terminal steps. Let's focus on decision steps (although it applies to both). Under that, you get `decisions.obs` which stores the observations collected by the agent(s). These observations are stored in a list, where each entry corresponds to one sensor, one of them being the "main sensor" filled with CollectObservations on the C# side.

The problem with this - I don't know what order they're in, or how to control that. From experimentation, I figured out that the main sensor is the last entry in the list. Other sensors are somewhere earlier in the list. If you just want to concatenate everything, it's not a problem, but e.g. to run a convolution on ray perception sensors and then connect it with the normal observations, you need to keep them separate and know which is which.

**Describe the solution you'd like**
I think a namedtuple would be the ideal structure for this, with fields named after the sensors used in the agent. Since it's a tuple, it will be compatible with the current list-based version, i.e. you can index into it or iterate over it. Since it's named, you can make sure you're grabbing the right sensor.

**Describe alternatives you've considered**
The alternative is to suck it up, trust that the order of sensors is invariant, and just hard-code it, at least until you want to change the sensors and then you have to rewrite the environment wrapper.

**Comment by chriselion** [comment]
Sorry for the delay on this.

In the latest release, BehaviorSpec changed to have a list of ObservationSpec NamedTuple on it ([source](https://github.com/Unity-Technologies/ml-agents/blob/dd4fd79a059fbedc9149566acf1c99a71d50a9cf/ml-agents-envs/mlagents_envs/base_env.py#L477-L504)); these correspond 1:1 with the observations at runtime. It sounds like if we add the name to this, you'll be able to do what you want, right?

> From experimentation, I figured out that the main sensor is the last entry in the list.

Sensors are sorted alphabetically by name on the C# side. The agent's VectorSensor will get the name `$"VectorSensor_size{observationSize}"` (where `observationSize` is the Agent's observation space size). So that's *probably* the last one in the list, but not necessarily :)

**Comment by RedTachyon** [comment]
Yes, I actually came across the BehaviorSpecs a bit later, but I figured trying to match the dimensions is a level of insanity I'm not ready for. Anyways, yes, adding the name would certainly work!

**Comment by chriselion** [comment]
Sounds good. I'll need to discuss it with some folks, but I think it's pretty easy to add. I have this logged as MLA-1823 in our internal tracker.

**Comment by chriselion** [comment]
Hi @RedTachyon - this was implemented in https://github.com/Unity-Technologies/ml-agents/pull/5036 and will be in the next release (tentatively next week).
