### ISSUE TITLE
Running Examplar Scene

### ISSUE THREAD

**Issue by ataerabi** [Unity-Technologies/ml-agents#5050]
I am new to unity and ml-agent. I downloaded the examplar scene of the 3D Ball. Everytime I try to run it, the following shows up. I 
![image](https://user-images.githubusercontent.com/58849033/110211485-a72afc00-7e8e-11eb-93f5-955845b60fda.png)

I have tried different version of unity and ML-Agent however i still always get the exact same error.

**Comment by vincentpierre** [comment]
Hi @ataerabi 
Please use the template for submitting issues, there are instructions on how to write an issue in a way that is reproducible to us. My guess on your issue is that you are using the wrong version of ML-Agents. You maybe got the package from the Unity Package manager (version 1.0.6) while using the examples from the master branch of github (version 1.8.1-preview). I would advise you to clone the whole github repo if you are trying to use the master branch or use the examples from version 1.0.6 on this branch : https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.0.6
If the error persists, please submit an issue with you complete setup so we can reproduce the error.
