### ISSUE TITLE
Sorter with Attention: 

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#5087]
Hi All,

When training the Sorter environment using Attention mechanism, the yaml configuration file output on the console, when the training starts, contains an unexpected _network_settings_ subsection in the _extrinsinc_ section:
```	reward_signals:	
	  extrinsic:	
	    gamma:	0.99
	    strength:	1
	    network_settings:	
	      normalize:	False
	      hidden_units:	128
	      num_layers:	2
	      vis_encode_type:	simple
	      memory:	None
```
Is this is a bug? If not, what is the meaning of this new subsection in extrinsic?

I also noticed that the number of _hidden_units_ in the regular network_settings must be a multiple of 4 (apparently due to input reshaping intended for Attention computations).
IMO, this should be checked for as soon as possible by the yaml parser as the exception raised in the case it is not a multiple of 4 is a bit unclear.

Thanks in advance for any help.

```
Environment:
Unity Version: Unity 2019.4.12f1
OS + version: Linux 64b
ML-Agents version: **commit 22a45cc14**
ml-agents: 0.25.0.dev0,
ml-agents-envs: 0.25.0.dev0,
Communicator API: 1.5.0,
PyTorch: 1.7.1
Environment: Sorter
```

**Comment by awjuliani** [comment]
Hi @Dastyn 

The `network_settings` you see there is because a number of the reward signals (like GAIL and RND) use neural networks, and this allows those network to be modified. In this case, the extrinsic signal does not use them, so they can be safely ignored. 

Thanks for bringing up the multiple of 4 issue. We will add this too the backlog to have a better error message raised in the future.

**Comment by miguelalonsojr** [comment]
Please post this on our forums: https://forum.unity.com/forums/ml-agents.453/
