### ISSUE TITLE
Possible to include the 'Frogger' sample project?

### ISSUE THREAD

**Issue by eagleEggs** [Unity-Technologies/ml-agents#51]
Would it be possible to include the frogger-like demo from https://blogs.unity3d.com/2017/09/19/introducing-unity-machine-learning-agents/ within the project?

Specifically this video: https://youtu.be/fiQsmdwEGT8

Thanks!

**Comment by awjuliani** [comment]
Hi @eagleEggs,

That video was one of the earliest demos I put together for the project, and as such isn't compatible with the current toolkit. It also uses a number of custom textures and models which I'd rather not include in the repository. The plan going forward is to include many more example environments, but to keep them all as lightweight as possible, so that the repository doesn't become unwieldy. I am currently working on a new set of platforming environments to add right now: https://twitter.com/awjuliani/status/914326970875363328 which could probably be easily modified to provide a similar task as the "Chicken" environment.
