### ISSUE TITLE
Proper Way to Use additional_args in Python UnityEnvironment call

### ISSUE THREAD

**Issue by ohernpaul** [Unity-Technologies/ml-agents#5137]
**Is your feature request related to a problem? Please describe.**
The basic request is to be able to launch training through python that achieves the exact same functions as mlagents-learn from the command line.

I'm having issues understanding how to use a yaml config file (with environment parameters) while utilizing the python lowlevel api to launch binary for training. As far as I can tell, you can control most configurations through the EngineConfigurationChannel, and or EnvironmentParametersChannel - notably the time scale, and resolution of window. Though, I cannot figure out how to launch training using a predefined configuration file and change the run-id; rather than defining environment parameters 1 by 1 in the EnvironmentParametersChannel.

My vision is to be able to:

- control the environment parameters as well as model parameters through a hyper parameter search
- launch with a config file via a list of config files (for multi session training)

**Describe the solution you'd like**
I would simply like to be able to define new run-ids and config files to use when instantiating either the Channels or while instantiating the UnityEnvironment. I'm aware that I could define all of the things listed in "my vision" via a text/json file, but that defeats the purpose of already having these yaml files defined.

**Describe alternatives you've considered**
I have looked at the googlecollab example and am not seeing any example of how to change run-id and use a yaml config file. 

I have also [posted ](https://forum.unity.com/threads/proper-way-to-use-additional_args-in-python-unityenvironment-call.1076348/)in the mlagents forum. 

```
engine_config_channel = EngineConfigurationChannel()

env_parameters = EnvironmentParametersChannel()

learn_args = ['config\\some_config.yaml', '--run-id=python_test'']

env = UnityEnvironment(file_name=env_path, 

                        seed=1337,

                        additional_args=learn_args,

                        side_channels=[env_parameters, engine_config_channel]

                        )
```

Also tried using os.system to launch:

```
learn_args = ['mlagents-learn', 'config\\gentrack_thresh_ppo_cur_somple.yaml', '--run-id=py_test',
              '--env=builds\\gentrack_sinple', '--num-envs=2', '--no-graphics',
              '--quality-level=1', '--height=1500', '--width=1500']

os.system(" ".join(learn_args))
```

**Comment by surfnerd** [comment]
Hi @ohernpaul,
I believe I responded to you in the forums.  Since your question is phrased slightly differently here, I'll respond slightly differently and post my response to you in the forums below.

The UnityEnvironment API is what mlagents-learn is built on top of.  It is intended for you to be able to build your own algorithms to train a unity environment.  mlagents-learn is _our_ implementation of training using the UnityEnvironment API.  The UnityEnvironment API is not intended to be a way for you to invoke mlagents-learn through python.  

I have reached out to the research team to chime in to see if they answer your questions more specifically.

**From the forums:**
The resolution and quality settings actually go into the engine_config_channel.

I don't think setting a config file is the intention of using the UnityEnvironment API. I believe that it is for more low-level interactions with a Unity binary, where you may want to use the API to design your own reinforcement learning algorithms, inspect the simulation from python, or other low-level tasks. Please read the Interacting With A Unity Environment documentation for more information.

**Comment by surfnerd** [comment]
the additional args like `--no-graphics` would go into the `additional_args` parameter.

**Comment by surfnerd** [comment]
Hi @ohernpaul,
I heard back from a colleague on our research team.  What they said was there isn’t a supported way to do this, but you can do some of it by importing the `run_training()` method (from `mlagents.trainers.learn import run_training`), constructing a `RunOptions` object (defined in `settings.py`), and calling `run_training` with this object. That’ll let you configure hyperparameters. Configuring the `EnvironmentParameters` will require a deeper modification, however.

I have logged this request internally as  MLA-1867 and we will update you on this issue when we make progress on the request. 

Thanks for your feedback and for your interest in ML-Agents.
