### ISSUE TITLE
Python low level API: any examples?

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#5248]
**Is your feature request related to a problem? Please describe.**
There are awesome examples of using ML-Agents in Unity on the C# side, using `mlagents-learn`.  I don't see much information or examples of using the Python low level API though.  Is it possible to create some examples which parallel the C# examples?  I've seen the jupyter notebook and the openAI gym pages and those are great.  But having more examples would be even better, of course -- especially a full end-to-end example.

**Describe the solution you'd like**
It would be nice if there were jupyter notebooks showing the same examples as the ones used on the C# side.  But any examples would be fine.

**Describe alternatives you've considered**
Right now, just messing around and exploring the python API.  But would be super helpful to see a full end-to-end example!

**Additional context**
If there are any tips or suggestions on getting started with the low level API, that would be also appreciated.

**Comment by andrewcoh** [comment]
Hi @zako42 

Just to clarify, you've seen these [colab examples?](https://github.com/Unity-Technologies/ml-agents/tree/main/docs#python-tutorial-with-google-colab) Can you elaborate on what more you'd like beyond what's contained in the colab?

**Comment by schmiJo** [comment]
@andrewcoh  Thank you this helped me a lot

**Comment by Ademord** [comment]
@andrewcoh we should have a collab for adapting an external algorithm into the UE API if there will be no efforts to push the gym_wrapper to be fully compatible with gym. And special emphasis on not using a multi-branch approach when creating an environemnt should be done *somewhere*, since adapting an external algorithm to use MutliDiscrete is too much overhead, and flatten_branched is returning 27 instead of 9 for me (3 discrete branches with 3 possible values).
