### ISSUE TITLE
After I increase the number of robots and the area of the ground in PushBlock, the task can't be finished

### ISSUE THREAD

**Issue by GMIL-lab** [Unity-Technologies/ml-agents#5266]
1. In PushBlock, the number of agents is 1 and the area of ground is 0.01. 
2.  **Experient 1**: After I change the area to 0.03 and keep the number of agents. I can use **imitation/Pushblock.yaml** to finish the task. 
3. **Experient 2**: But after I change the area to 0.03 and increase the number of agents to 3. I can't use **imitation/Pushblock.yaml** to finish the task. 
4.  I check the **extrinsic reward** and **GAIL reward**. The GAIL reward is similar. But in **Experient 2**, the **extrinsic reward** is always low. 
5. What should I do to complete  **Experient 2**?
Here the experient data.
![Screenshot from 2021-04-15 13-40-18](https://user-images.githubusercontent.com/49852992/114815155-9efc9f80-9df0-11eb-8b8d-8cdb425912bb.png)
![Screenshot from 2021-04-15 13-30-28](https://user-images.githubusercontent.com/49852992/114815168-a58b1700-9df0-11eb-85ec-967620c0c139.png)
![Screenshot from 2021-04-15 13-30-54](https://user-images.githubusercontent.com/49852992/114815172-a7ed7100-9df0-11eb-9ce0-10ab0f235eb1.png)
![Screenshot from 2021-04-15 13-31-47](https://user-images.githubusercontent.com/49852992/114815177-aa4fcb00-9df0-11eb-951c-900a19cd5879.png)

**Comment by dongruoping** [comment]
Hi,

Since it is not a feature request or bug, I think you may find a better place for discussion on our official forums: https://forum.unity.com/forums/ml-agents.453//.

That being said, by changing the number of agents in the field you're changing the task and the training might not behave the same as before. From your description I'm not sure if you have recorded new demos for new settings, changed the reward function, or made any other changes. The training will not work by just applying the single-agent demo files to multi-agent since the new environment is also depends on other agent's actions. Also if you have three agent but only one block then only one agent will get positive reward and thus the mean rewards are not comparable.

I'll close this issue, but feel free to open a post on our forum for more discussions.

**Comment by GMIL-lab** [comment]
Thank you for your reply


Ruo-Ping Dong ***@***.***> 于 2021年4月16日周五 02:31写道：
