### ISSUE TITLE
My observation and onactionreceived are not working

### ISSUE THREAD

**Issue by invincibledinku** [Unity-Technologies/ml-agents#5332]
**My observation and onactionreceived are not working.** 

_Hence my Player cube (green) is not moving at all._

    This is to train the green cube to reach the red cube.

The player's movement is based upon the VectorObservation size and continuous action as given in the tutorial (documentation).

**[https://github.com/Unity-Technologies/ml-agents/blob/release_17_docs/docs/Learning-Environment-Create-New.md](url)**

    When I start my training, my mean reward and standard rewards are all 0.**

    **Packages Installed :**

        I'm using: Release 17
        Python package: 0.26.0
        ML agents - 2.0.0
        MLagents extension - 0.3.1
        UNITY - 2020.3.6f1

    **### Here is my code:**

    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    using Unity.MLAgents;
    using Unity.MLAgents.Actuators;
    using Unity.MLAgents.Sensors;

    public class playerscript: Agent
    {
    Rigidbody rBody;
    public Transform Target;
    public float forceMultiplier = 10;
    public Vector3 playerpos;
    public override void Initialize()
    {
    rBody = GetComponent<Rigidbody>();
    playerpos = transform.position;
    }
    public override void OnEpisodeBegin()
    {
    // Move the target to a new spot
    transform.position = playerpos;
    Target.localPosition = new Vector3(Random.Range(-1, 4), 0.51f, 14.54f);
    // this.rBody.velocity = new Vector3(0, 0.5f, 1.5f);
    }

    public override void CollectObservations(VectorSensor sensor)
    {
    // Target and Agent positions
    sensor.AddObservation(Target.localPosition);
    sensor.AddObservation(this.transform.localPosition);

    // Agent velocity
    sensor.AddObservation(rBody.velocity.x);
    sensor.AddObservation(rBody.velocity.z);
    }

    public override void OnActionReceived(ActionBuffers actionBuffers)
    {

    Vector3 controlSignal = Vector3.zero;
    controlSignal.x = actionBuffers.ContinuousActions[0];
    controlSignal.z = actionBuffers.ContinuousActions[1];
    this.rBody.velocity= new Vector3(controlSignal.x, 0, controlSignal.z);

    print("onaction x: " + controlSignal.x);
    print("onaction z: " + controlSignal.z);
    // Rewards

    float distanceToTarget = Vector3.Distance(this.transform.localPosition, Target.localPosition);

    // Reached target
    if (distanceToTarget < 1.42f)
    {
    SetReward(1.0f);
    EndEpisode();
    }

    // Fell off platform
    else if (this.transform.localPosition.y < 0)
    {
    EndEpisode();
    }
    }

    public override void Heuristic(in ActionBuffers actionsOut)
    {
    var continuousActionsOut = actionsOut.ContinuousActions;
    continuousActionsOut[0] = Input.GetAxis("Horizontal");
    continuousActionsOut[1] = Input.GetAxis("Vertical");
    }
    }

    Here are my screenshots, Codes and error messages.
 
![error1](https://user-images.githubusercontent.com/6459572/116688824-dcf2e980-a9d4-11eb-8919-fae214499d4c.png)
![error2](https://user-images.githubusercontent.com/6459572/116688833-e0867080-a9d4-11eb-8314-7de4ee3c997f.png)
![error3](https://user-images.githubusercontent.com/6459572/116688835-e1b79d80-a9d4-11eb-8614-f8309f3bcd9b.png)
![error4](https://user-images.githubusercontent.com/6459572/116688837-e2503400-a9d4-11eb-8bed-55362c2894f4.png)

**Comment by vincentpierre** [comment]
Hi @invincibledinku,
Are you able to train on the example environments? If yes, this type of issue is more suitable for a forum question.
Are you able to solve the task when using the mode `Heuristic Only` in the `Behavior Parameters` window? I suspect your issue is that the force applied to the agent is not high enough to move the cube and this can be diagnosed with the Heuristic Only mode. It is also possible that in order to move towards the goal, the agent has to maintain a direction for a long time before moving. This type of behavior can be very hard for an agent to solve. 
How long have you been running the training for? This could be an exploration problem and it might be solved with some intermediate rewards.

**Comment by invincibledinku** [comment]
Thanks for the Response.

The cube is not moving even in the Heuristic only mode. These are the codes I just used from the *Creating new environment* section of unity docs.

**Comment by invincibledinku** [comment]
@vincentpierre,

I could able to train the example environments. I have just now trained 3DBall example. It trains fine with increasing mean and standard rewards.
![error5](https://user-images.githubusercontent.com/6459572/116769538-8e882e00-aa5a-11eb-944b-89da7df40c94.png)

**Comment by invincibledinku** [comment]
Can someone help me here?

**Comment by vincentpierre** [comment]
> The cube is not moving even in the Heuristic only mode.

Well this is your issue. If you cannot move the cube at all, then the agent would be unable to as well. This is probably why the agent always had a reward of 0.

>These are the codes I just used from the Creating new environment section of unity docs.

```
this.rBody.velocity= new Vector3(controlSignal.x, 0, controlSignal.z);
```
This does not look like the proper way to modify the velocity of a rigidbody, I think you need to use `AddForce`

```
public float forceMultiplier = 10;
```
This float is not used anywhere in your code, I think this might be one of the causes of the problem.

Let me know if you manage to get it to work. This tutorial is central for our users, so I need to make sure it actually works.

**Comment by invincibledinku** [comment]
hi, thanks for the response.

I updated my code and tried it too. Still the same result. The cube is not moving at all.
[gameassets.zip](https://github.com/Unity-Technologies/ml-agents/files/6410114/gameassets.zip)

**Comment by vincentpierre** [comment]
I cannot open this gameassets.zip file. Can you try using a `.unitypackage` format?
As long as you cannot make the agent move using heuristic mode, the agent will stand no chance. Does this line 
```
print("onaction x: " + controlSignal.x);
```
get called? Are you sure OnActionReceived is called? Can you try manually applying a force to the object until the object moves? What is the mass of the rigidbody of the Agent (If it is too high, it might prevent it from moving)?

You seem to be able to run the example environment properly, so I think the issue is in your code. Either there is something preventing the agent from moving or not enough force is applied to it.
