### ISSUE TITLE
Rendering Unity Environment using OpenAI Gym Wrapper

### ISSUE THREAD

**Issue by sarmientoj24** [Unity-Technologies/ml-agents#5380]
How do I render the Unity Environment when using OpenAI Gym Wrapper?
The document does not say anything and using `env.render()` doesn't really do anything.

I am also using Linux.

**Comment by dongruoping** [comment]
Hi,

Please follow our issue template to report an issue, since we need the information to help look into your issue.
Can you provide your ML-Agents version and the environment you are using (our example environment/your own project)?

Also are you using visual observations? It will be helpful if you can provide the details and step by step command for us to reproduce the problem.

When you say env.render() doesn't really do anything, are you talking about the scene rendering on your screen or env.render() didn't return what you want?

**Comment by dongruoping** [comment]
Some update notes after talking to other folks on the team: We don't currently support display rendering for Gym Wrapper. This is something we're aware of but haven't gotten to it yet. 

To fix this it will require a rather bigger change in the code and we don't have a timeline on that. But for now I'll update the documents to clear the confusion.
