### ISSUE TITLE
Can't train parallelly using multiple instances  when use --num-envs > 0 

### ISSUE THREAD

**Issue by 1095678630** [Unity-Technologies/ml-agents#5381]
As the question, I can not train using multiple instances. Here is my command:
**mlagents-learn config/ppo/3DBall.yaml --env=./Excutable_Test/3DBall --run-id=firstRun  --num-envs=2 --resume**
and this is the result:
![image](https://user-images.githubusercontent.com/47738954/119340476-24635180-bcc5-11eb-8276-4e0717742131.png)
It just block without any reactions and there are no any errors. Addtionally, I can input ctrl+c to interrupt the command as following:
![image](https://user-images.githubusercontent.com/47738954/119341004-dd299080-bcc5-11eb-8bcb-35dd3b4eb2c8.png)

I train succussful using the same command except the --num-envs equals 1. 
Can anybody help me? :)

**Comment by dongruoping** [comment]
Hi,

Please follow our issue template to report an issue, since we need the information to help look into your issue.

Can you provide your Unity Version, OS, and ML-Agents version?

Also just to clarify, you are using our 3dball example, and the same command works with num-envs=1 but doesn't work with --num-envs=2, is that correct?
When it's blocked, did you see two Unity game instances being launched?

**Comment by 1095678630** [comment]
Oh, sorry for not using the correct templete! 
But I find it works successfully now! Maybe cause I reboot the computer.
Anyway, thank for your reply! 
But I also find some problems in efficiency. The following pics are corresponding to the --num-envs equals 1,2,3,4:
![image](https://user-images.githubusercontent.com/47738954/119432012-192f1680-bd03-11eb-8844-5a92f7e70307.png)
![image](https://user-images.githubusercontent.com/47738954/119432024-1f24f780-bd03-11eb-8c64-5fc36b21629b.png)
![image](https://user-images.githubusercontent.com/47738954/119432031-23e9ab80-bd03-11eb-9876-6aca9e0f474a.png)
![image](https://user-images.githubusercontent.com/47738954/119432044-2946f600-bd03-11eb-8533-41d6b1608a90.png)

Well....I just want to ask why their training efficiency seem not to improve obviously? Can you plz give some advice for improve training speed in --num-envs?
Also, I find whatever num I choose, the CPU working rate seems to not change (I use CPU for training). Does the training can only use limited CPU resources?
![image](https://user-images.githubusercontent.com/47738954/119433268-72984500-bd05-11eb-9331-aa75346b3285.png)


My Unity version is 2020.2.6f1c1, OS is win10 and the ml-agents versions is 0.26.0.
Thanks your relpy again. : )

**Comment by dongruoping** [comment]
The training time is spent on two parts, running inference and updating model. Running more parallel instance helps speed up the inference part. As you speed up more and more on one part, the other will become the main bottleneck and you'll no longer getting more speed up. You can look at the `timers.json` file in your results folder to see where the training time is bottlenecked on. 

As for the CPU utilization, it really varies with different machine specifications and the environment you run. We are actively working on looking into resource utilizations and how to improve that, in order to give a better guide on how to improve training speed.

Since your original issue has been resolved, I'll close this issue. If you have any more questions, [our forum](https://forum.unity.com/forums/ml-agents.453/) is a better place for asking questions and general discussions. I would suggest you open a post there if you have more questions regarding your project, thanks.
