### ISSUE TITLE
StatsRecorder and mlagents_env working together by default

### ISSUE THREAD

**Issue by jziegle4** [Unity-Technologies/ml-agents#5405]
**Is your feature request related to a problem? Please describe.**
When i try to use mlagents_env with my own Python code i would like to use the same Academy.Instance.StatsRecorder to record internal statistics without having to rely on a custom sidechannel. Since this would help to use the same executable with both PPO/SAC that is integrated into mlagents and with custom code using mlagents_env. This would be helpful

**Describe the solution you'd like**
Allow Acaedmy.Instance.StatsRecorder to log values and write them into Tensorboard with a simple bool value when instancing mlagents_env. This would simplify coding on python side, since StatsRecorder seemingly cannot be used with mlagents_env since it is not registered by default.

**Comment by vincentpierre** [comment]
Hi @jziegle4 
I am not sure I understand the request. mlagents_envs does not send any information to TensorBoard on purpose because a lot of users do not need to use TensorBoard and don't even want to import it. Adding a dependency on TensorBoard in both mlagents_envs and mlagents would increase complexity. Using side channels allows for more flexibility since the data can be logged into anything from mlagents_envs and not just into TensorBoard. 
Is there an issue with the side channel API? Can you suggest some changes it its API to make it easier to use?

**Comment by iceboy910447** [comment]
Hi @vincentpierre

I'd like to use the same executable with mlagents PPO variant and with DQN like the Rainbow variant in Ray RLlib. Currently its easy for me to use Statsrecorder to gather statistical data abount the agent and directly plot that in Tensorboard without any changes in the python code. But when i use my own DQN i have to change that, because i can't log the data into tensorboard by default. In this case i have to either disable StatsRecorder or implement an own custom sidechannel both in C# as well as in python. In libaries like Ray RLlib most of the tensorboard logging is handled internally so its harder to access and adapt. With that in mind I'm searching for a way to easily use Statsrecorder to log my data into Tensorboars while using other RL libaries that are harder to adapt. If there is a way to make that happen using the existing Side Channel APi i'd be happy to use that otherwise it would be nice change the API of mlagents_env so it can handle StatsRecorder to Tensorboard

**Comment by vincentpierre** [comment]
I think the simplest way to solve your problem is to use a [StatsReporter](https://github.com/Unity-Technologies/ml-agents/blob/main/ml-agents/mlagents/trainers/stats.py#L289) with a [TensorboardWriter](https://github.com/Unity-Technologies/ml-agents/blob/main/ml-agents/mlagents/trainers/stats.py#L213) and call add_stats and write stats when the side channel receives information. Putting this logic inside of UnityEnvironment is challenging, because not all users will want their stats reported at the same time or in the same manner.

**Comment by jziegle4** [comment]
I will try that, but how can i connect the StatsRecorder on Unity side to a custom side channel on Python side?
As i see in [https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Custom-SideChannels.md](url) i have to reference the side channel using a ID. So far I could not find out how to connect StatsRecorder with a sidechannel. I hope you can help me with that?

**Comment by vincentpierre** [comment]
Hi @jziegle4 
You can receive the stats using this [side channel](https://github.com/Unity-Technologies/ml-agents/blob/colab-CI/ml-agents-envs/mlagents_envs/side_channel/stats_side_channel.py) when you register it with your UnityEnvironment it will receive the messages from the Unity side StatsReporter

**Comment by jziegle4** [comment]
Hi @vincentpierre,

I would like to try this, but currently when i follow this link i only get a 404 error. Maybe the link is incorrect or you are referrencing a different branch. I tried to see if i can find a file in the colab folder, but i couldn't find one. I hope you can help me find the file you referrenced.

**Comment by vincentpierre** [comment]
My bad. The document I tried to reference is here : https://github.com/Unity-Technologies/ml-agents/blob/main/ml-agents-envs/mlagents_envs/side_channel/stats_side_channel.py
