### ISSUE TITLE
recevied data from Unknown side channel in training gym-unity

### ISSUE THREAD

**Issue by hyuDev** [Unity-Technologies/ml-agents#5482]
I training my agent to using gym-unity.
but when train start, i recevied warnning msg.

the msg is here,
[side_channel_manager.py:47] Unknown side channel data received. Channel type:  XXX

I'm not sure this msg is simply a warning message or a fatal error to correct. My agent doesn't have a code for the side channel.

**Comment by dongruoping** [comment]
Hi, 

Please follow the issue template so that we can have the information to better help you.
What's the Unity Editor/ML-Agents version you're using?

Also, are you using your own environment or one of our examples? If you're using your custom environment and seeing errors,  please try with any of our examples first and see if the error is still there.
