### ISSUE TITLE
How to import ML-Agent to asset

### ISSUE THREAD

**Issue by Albert950207** [Unity-Technologies/ml-agents#5494]
Hi,
I just followed the instruction of building a new learning environment in doc file . I download the ML-agent package from ml-agent repository and then I import it into Unity-3D by package manger. However, the instruction says that there must be also a ML-agent folder in asset and I cant find it. Could someone please help me how to make it ?

Unity version: 2021.15f1

**Comment by vincentpierre** [comment]
Hi, 
This issue is not considered a bug. It would be more suitable for the forum since this is an ask for help. The instructions referring to the ML-Agents folder in the Assets folder assume that the github repo was cloned. It corresponds to this folder https://github.com/Unity-Technologies/ml-agents/tree/main/Project/Assets/ML-Agents 
The Unity package does not include the sample environment because they are too large to be part of a package.
