### ISSUE TITLE
Assertion Exception Error.

### ISSUE THREAD

**Issue by xogur6889** [Unity-Technologies/ml-agents#5499]
I often see this message while training AI. Can you tell what caused it?

![image](https://user-images.githubusercontent.com/55425599/129143847-8b9c0490-1e20-4f35-a3a9-a11839d245db.png)

**Comment by mahon94** [comment]
Hi  @xogur6889, 

Please follow the issue template, the steps to reproduce the bug and information on Unity and ML-Agents are necessary for us to better help with your problem.

Are you using ML-Agents example environments or your own? if you're using your environment and see these error, please try with one of our environments and see if the error is still there?

**Comment by xogur6889** [comment]
_Please follow the issue template, the steps to reproduce the bug and information on Unity and ML-Agents are necessary for us to better help with your problem._

**Okay. Next time I'll do that.**

_Are you using ML-Agents example environments or your own? if you're using your environment and see these error, please try with one of our environments and see if the error is still there?_

**First of all, I asked the cause of that error, did you misunderstand? I'm using my own environments. not using ML-Agents example. You said try one of your environments but I think it is not helpful to solve my problem. To be more specific about my problem, it usually happens in the process of putting one model in an inference state and learning another when using two models. Usually, it seems to occur once in 5 million steps.**

Thank you.

**Comment by mahon94** [comment]
Since you're using inference, it might be a Barracuda issue. Can you please provide:

- The full stack trace of the bug in Unity, it helps us to follow where the error comes from
- Barracuda Version: 
- ML-Agents version: (e.g. ML-Agents v0.8, or latest develop branch from source)
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: 
- Torch version:

**Comment by xogur6889** [comment]
Hi @mahon94

I just installed the version you told me to install in the document and it doesn't seem to be a version problem.
ex) pip3 install torch~=1.7.1 -f https://download.pytorch.org/whl/torch_stable.html

I use Windows and the computer is up to date.

In one environment I use two Behavior Names. (For example, one is red and one is blue). Use the red I want to train as Default. Blue set up the Behavior Type as Inference Only to use the trained model. And the problem arose in this environment.

**Comment by dongruoping** [comment]
@xogur6889 we're not able to help unless you provide full information, which is listed out in the comment above and the issue template. The error can be caused by many reasons and we're not able to look into it without those information.

Besides, we are unable to help reproduce bugs with custom environments since we have no access to your project. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
