### ISSUE TITLE
SAC v2?

### ISSUE THREAD

**Issue by Ademord** [Unity-Technologies/ml-agents#5533]
Is the SAC trainer based off the newer version : https://arxiv.org/abs/1812.05905?

**Comment by dongruoping** [comment]
Our SAC implementation is based on the one described in https://arxiv.org/abs/1801.01290 and implemented in https://github.com/hill-a/stable-baselines.

Since this is not a feature request or bug report, I'm closing this now. For general questions, our [forum](https://forum.unity.com/forums/ml-agents.453/) is a better place to get help from.

**Comment by Ademord** [comment]
Thank you so much!! 

as a wrapping up question, the PPO implementation is based on Schulman 2017 if I did my research correctly?

**Comment by dongruoping** [comment]
yes, it's an implementation of PPO as described in: https://arxiv.org/abs/1707.06347
