### ISSUE TITLE
I followed q learning with unity environment, but the onnx didn't work

### ISSUE THREAD

**Issue by luckyShaw** [Unity-Technologies/ml-agents#5596]
I followed [https://colab.research.google.com/github/Unity-Technologies/ml-agents/blob/release_18_docs/colab/Colab_UnityEnvironment_2_Train.ipynb](url),
and then transfer the model into onnx by following code which i found in 
![code](https://user-images.githubusercontent.com/65491120/138802121-2f641e5c-51f5-41e0-bfcb-a3d7ca462391.png)
[https://docs.unity3d.com/Packages/com.unity.barracuda@2.0/manual/Exporting.html](url)
and applied to unity gridword, but i get errors like this,
![errors](https://user-images.githubusercontent.com/65491120/138802381-76b2f269-7393-4519-84ef-9c0950771e9c.png)
only the agent in center area seems to be working.
I'm thinking if there is any clear tutorial about how to transfer a pytorch model into onnx that can be applied in unity, that would be really helpful.

**Comment by luckyShaw** [comment]
Thanks a lot, I've running the model in binary file. And i got another question. Am I be able to create environment that is able to execute Multi-agent reinforcement learning algorithm??

**Comment by mahon94** [comment]
Yes, ML-agents supports multi-agents training for cooperative and competitive scenarios in a couple of our sample environments. You can find more about it on the [`docs`](https://github.com/Unity-Technologies/ml-agents/blob/3bd0b68bf88aa147c3dfb0b6d3336b8454799750/docs/Learning-Environment-Design-Agents.md#defining-multi-agent-scenarios) and [blog posts](https://blog.unity.com/technology/training-intelligent-adversaries-using-self-play-with-ml-agents).

**Comment by jrupert-unity** [comment]
If you work off the version of the colab on the main branch it will now create a model that will work with the GridWorldColab example scene, also on the main branch.  

These will be in the upcoming release if you would prefer to wait for a released version rather than using the main branch.

The DQN colab notebook can also be used as a reference for how to create a model that names tensors how Barracuda (which does runtime inference in Unity) expects them, and adds several extra tensors that are expected to provide configuration information.

Closing this now but please re-open if there are further issues related to this.
