### ISSUE TITLE
Question about visual observation

### ISSUE THREAD

**Issue by imankgoyal** [Unity-Technologies/ml-agents#562]
For visual observation, the code supports rendered image(s) from single/multiple cameras, but there is no direct way to get the depth/normal map. I saw a closed issue (#329) requesting the depth feature. I think one can use DepthTextureMode in camera and make a suitable depth shader (http://willychyr.com/2013/11/unity-shaders-depth-and-normal-textures/). I need the depth-map in my project and wanted to seek suggestion as to whether this is a good workaround.

**Comment by awjuliani** [comment]
Hi @imankgoyal,

As a workaround, it is definitely possible to use a "depth" shader on a camera, and render that way. We are actually interested in including an option to allow people to use depth instead of RGB for visual observations (similar to the switch to use b/w). If you happen to implement this, we'd be happy to accept it as a PR into ML-Agents.

**Comment by awjuliani** [comment]
Here is more information on the depth texture: https://docs.unity3d.com/Manual/SL-CameraDepthTexture.html

**Comment by imankgoyal** [comment]
Thanks!

**Comment by maystroh** [comment]
@awjuliani, where we stand on this? is it done? I mean to allow the use to use depth image instead of RGB for visual observations.
