### ISSUE TITLE
Bug in documentation?

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5634]
**Describe the bug**

https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md#training-the-environment

Option "beta_schedule: constant" errors

`mlagents.trainers.exception.TrainerConfigError: The option beta_schedule was specified in your YAML file for PPOSettings, but is invalid.`

**Comment by jrupert-unity** [comment]
This looks like another case where the documentation is ahead of the latest release.   

If you are on Release 18 you can switch to look at that version so that the documentation you are looking at corresponds with the version you are using.
![image](https://user-images.githubusercontent.com/92821409/145694095-fff01f8f-bf6d-458d-9102-adb882aabec4.png)

**Comment by trsh** [comment]
This is lot of confusion. Unity could:

a) Put a warning, that this is WIP version docs;
b) Handle docs in a way, that the default one corresponds to latest release;

**Comment by jrupert-unity** [comment]
Thank you for the feedback, I will discuss it with the team.
