### ISSUE TITLE
Defining an empty observation for Buffer Sensor

### ISSUE THREAD

**Issue by CubeMD** [Unity-Technologies/ml-agents#5684]
**Is your feature request related to a problem? Please describe.**
If Buffer Sensor is not completely filled with observables the rest of observations are zeros. This might become an issue in case that an observation full of zeros is a valid entity observation.

**Describe the solution you'd like**
It might help to define a custom empty observation per buffer sensor and just before writing sensor values using it to fill in the remaining observables. I came up with a solution which looks like this in the Editor
![image](https://user-images.githubusercontent.com/5870779/149992026-26c30071-3a76-4531-bdd9-f473c87f6e3d.png)

**Describe alternatives you've considered**
Ignoring it and hoping that the agent will learn regardless

**Comment by maryamhonari** [comment]
Hi @CubeMD,

The [BufferSensor](https://docs.unity3d.com/Packages/com.unity.ml-agents@2.0/api/Unity.MLAgents.Sensors.BufferSensor.html) is for [variable-size of observation](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Design-Agents.md#variable-length-observations) by design. It is processed by an attention module on trainers and all the zero/empty entities will be ignored. You can look through sorter and dodgeball examples to see how it's being used.

**Comment by maryamhonari** [comment]
Hi, Thanks for bringing up this request. Currently we consider a nearly zero entity as an empty observation and it's a fair point that it might be a valid observation. I logged this internally as MLA-2360 and will prioritize accordingly.
