### ISSUE TITLE
Issues with Basic example

### ISSUE THREAD

**Issue by malvakian** [Unity-Technologies/ml-agents#57]
**After train Basic agent with PPO.ipynb and sending back the bytes file to Unity, console shows this error:**

`UnityAgentsException: Expects arg[0] to be int32 but float is provided
CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:240)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:312)
Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:250)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:337)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:260)`

I have checked that the Action space type is Discrete, any ideas?

-----------------------------------------------------------

**Try to use BasicDecision.cs return this error in console:**
`NullReferenceException: Object reference not set to an instance of an object
BasicAgent.AgentStep (System.Single[] act) (at Assets/ML-Agents/Examples/Basic/Scripts/BasicAgent.cs:25)
Agent.Step () (at Assets/ML-Agents/Scripts/Agent.cs:209)
Brain.Step () (at Assets/ML-Agents/Scripts/Brain.cs:324)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:346)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:260)`

Easy fix replacing line 9 with this:
`return new float[1]{ 1f };`

Regards

**Comment by vincentpierre** [comment]
Thank you for testing this part of ML-Agents. Both the issues you raised are bugs that need to be addressed. I made a change in the development branch `dev-broadcast`. The fix you made for the second issue is the right one I believe because the error you were getting is because the default `float[]` is null. 
If you want to fix the first error, you can implement what I did in this commit [16c12f5](https://github.com/Unity-Technologies/ml-agents/commit/16c12f5e7cfefb49355d64a36c3002f0e56982d3) Basically, the state is a `float[]` by default that needs to be converted into an `int[]` if the state space type is discrete. I hope this helps.
