### ISSUE TITLE
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 127.

### ISSUE THREAD

**Issue by z3r097** [Unity-Technologies/ml-agents#5707]
Has anyone seen this bug?
i want to use my rl_model in unity_enviroment
my model was used in gym_enviroment
no error occurs in windows and my ubutu but on another ubuntu it does
enviroment is same

Ubuntu 20.04.2 LTS
mlagents_envs.__version__, = 0.28.0
API_VERSION, = 1.5.0
Gym-unity = 0.28.0

error code

File "MYPATH", line 418, in _poll_process
    raise UnityEnvironmentException(exc_msg)
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 127.

**Comment by hvpeteet** [comment]
Hi, thanks for your interest in ml-agents. We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle [discussions, installation issues, etc] like this. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.
