### ISSUE TITLE
UnityToPettingZooWrapper in documentation but not in mlagents_envs.envs

### ISSUE THREAD

**Issue by liznelson** [Unity-Technologies/ml-agents#5877]
I'm interested in using the UnityToPettingZooWrapper to wrap a custom built environment and train with Petting Zoo.

It is referenced in this doc: https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Python-PettingZoo-API.md.
It is not available in the code and I can't see it referenced anywhere. Perhaps I just can't find it?

 Is this method intended to be used for custom environments? If not, this would be incredibly helpful.

**Comment by liznelson** [comment]
Ok I see now that there are two different wrappers, One for the AEC Petting Zoo API and the other for the Parallel Petting Zoo API. UnityAECEnv and UnityParallelEnv. Your documentation should be updated to reflect that. 

The env wrapper works great though.

**Comment by MRanka29** [comment]
I am still unable to import UnityAECEnv. Is it from mlagents_envs.envs import UnityAECEnv or am I missing something?
I am trying to work with UnitToPettingZooWrapper and tried to import UnityAECEnv but getting the error 
ImportError: cannot import name 'UnityAECEnv' from 'mlagents_envs.environment'

**Comment by elliottower** [comment]
> I am still unable to import UnityAECEnv. Is it from mlagents_envs.envs import UnityAECEnv or am I missing something?
> I am trying to work with UnitToPettingZooWrapper and tried to import UnityAECEnv but getting the error
> ImportError: cannot import name 'UnityAECEnv' from 'mlagents_envs.environment'
I think the correct import statement would be `from mlagent_envs.envs.unity_aec_env import UnityAECEnv`. If you check the [envs directory](https://github.com/Unity-Technologies/ml-agents/tree/develop/ml-agents-envs/mlagents_envs/envs) you can see it’s within the unity_aec_env file, and then if you check [__init__.py](https://github.com/Unity-Technologies/ml-agents/blob/develop/ml-agents-envs/mlagents_envs/envs/__init__.py) you can see it doesn’t import the submodules automatically (i.e., you have to import explicitly from the folder which the class is located, rather than from envs import UnityAECEnv).

Not sure if this is intentional or not but a lot of other repositories will have their __init__.py files import the submodules so that users have an easier time doing what you tried to do. Adding the lines `from unity_aec_env imprt UnityAECEnv` and so forth to the init file will allow your command to work.

Also if you look at the documentation it shows that the class is from the unity_aec_env file, just for future reference if you want to make sure you are importing correctly and not have to look through the source code: https://unity-technologies.github.io/ml-agents/Python-PettingZoo-API-Documentation/#mlagents_envs.envs.unity_aec_env.UnityAECEnv

**Comment by skandermoalla** [comment]
@miguelalonsojr shouldn't this issue be reopened until the documentation is fixed? It wasn't easy to find.

**Comment by GF-Huang** [comment]
Same for me, the docs out of date.
