### ISSUE TITLE
ML agents not learning most basic board game strategy

### ISSUE THREAD

**Issue by mrsam993** [Unity-Technologies/ml-agents#5897]
I am currently trying to use ML-Agents to learn and play the board game Kalah (rules here for those interested but not strictly needed for this question). I am currently using the most basic board possible that still allows for some decision-making, having 2 pits per side and 1 marble per pit. If the Agent (player 1) moves the marbles in the first pit (bottom left), they are guaranteed to lose as whatever move the second player makes will secure them a win. If the Agent moves the marbles in the second pit (bottom right) they gain a free move and are secured a win by performing the only valid move left which is the first move. With enough training, the Agent should move the marbles in pit 2 100% of the time as doing that secures them a win, and doing the only other move guarantees them a loss, despite this even with around 250000 games of training it averages a 50/50 win loss rate. My current working theory is that, as a win requires the Agent to make both moves once, it is evaluating them equally and essentially tossing a coin as to which it does first, even when I specifically give it a reward for moving the marbles in the second pit first this does not change. My question as a whole is, can ML-Agents learn the importance of the order of moves, have I set something up incorrectly or is this something the Agent will never learn? Attached are pictures of the board, my results are 250000+ games and my general setting, code files can be attached as well if they will prove useful. Thank you in advance! 
![Capture](https://user-images.githubusercontent.com/67601210/229501743-3f418759-a691-4e80-88da-e2b32faa7b51.PNG)
![Capture1](https://user-images.githubusercontent.com/67601210/229501750-ec80299d-822d-40eb-8622-d32fcdc6cbe9.PNG)
![Capture2](https://user-images.githubusercontent.com/67601210/229501754-aba36312-5226-473c-afbc-e132a8fa6a9f.PNG)
![Capture3](https://user-images.githubusercontent.com/67601210/229501755-5e66f7b3-31ee-4452-b1f0-5b009f790696.PNG)

**Comment by elliottower** [comment]
Can’t offer help but would be curious if you figure out the solution on your own, as I am interested in doing a similar thing with another board game. Maybe you could post your full code/repo once you have it working so other people can use it for reference. 

If you just want to train an agent to play a board game and don’t care as much about the rendering, you could try implementing your game using [PettingZoo](https://github.com/Farama-Foundation/PettingZoo) and trying various training methods there, to ensure that the issue is not due to unity. I can’t comment on how well the integration works with unity ml-agents and pettingzoo but there are a good amount of tutorials on here. Disclaimer that I’m a maintainer of PettingZoo so I’m obviously biased but we have a discord and active dev team which can help with any questions you encounter.

I’m not 100% sure but I believe you can use PettingZoo with the unity ml-agents low level API in order to control the environment through python. I am planning to test this out in the near future so I can let you know if I am able to get it working.

**Comment by miguelalonsojr** [comment]
Please resubmit your bug report using our template. This will allow us to try to reproduce the error. Also, We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue. If it turns our this is not a bug, I'd recommend posting to our forums and seek help from the community: https://forum.unity.com/forums/ml-agents.453/.
