### ISSUE TITLE
Problem with new environment

### ISSUE THREAD

**Issue by GEORGJOSE007** [Unity-Technologies/ml-agents#59]
I created a new environment as per the instructions given. Created the build file and tried to run the PPO file. But for some reason it is stuck in the line env.reset(train_mode=train_model). Specifically it is stuck at this statement inside environment.py (line 172)  
state = self._conn.recv(self._buffer_size).decode('utf-8')

PPO file was changed to give some random actions at each step. I checked the same for 3D Ball and it is working.  I am unable to debug this issue. Please provide some help.

**Comment by vincentpierre** [comment]
Do you have some errors in the unity environment ? Can you build a development build or look into the [logs](https://docs.unity3d.com/Manual/LogFiles.html) and tell us if you get an error? When python gets stuck it is usually because it is waiting for a message that will never come from the unity environment.

**Comment by GEORGJOSE007** [comment]
Thanks for pointing to the log which I haven't known of before. I really helps in debugging. I setup the  academy again from scratch and now it is working.

Thanks for the help :)
