### ISSUE TITLE
How spawn the checkpoints progressively so the AI agent can follow a preferred route?

### ISSUE THREAD

**Issue by mra16r** [Unity-Technologies/ml-agents#5917]
I'm training a AI with ML legend, and I'm wondering if there's a way to spawn the checkpoints progressively so the AI can only see 1 checkpoint at a time, and complete the training easier.

Currently my checkpoints are scattered in a very non-linear way in my level. It has to go up an elevator, touch a checkpoint, then go back on the elevator to go back down, then exit the door.

It's very non-linear and has to go back on its way, and most of the time it just jumps down and falls over, and it resets the episode.

**Comment by ARandomFrenchDev** [comment]
Hi @mra16r , I don't think that's a question you should ask here, since it's more about how Unity works instead of how ML-Agents works.
Either way, you could setup an array of checkpoints with a specific order, and the agent gets a positive reward if he goes through them in order, and a negative one if he skips one for instance.

**Comment by miguelalonsojr** [comment]
Please submit this question on the forum: https://forum.unity.com/forums/ml-agents.453/
