### ISSUE TITLE
2 GPU of 4090

### ISSUE THREAD

**Issue by Sam-WangXZ** [Unity-Technologies/ml-agents#5978]
Hello. I got a PC with 2 GPUs(4090). At the moment I'm only using one for training, but is it still possible to use multiple GPUs? which version should i use? i am now using release 19

**Comment by Eelam** [comment]
Hi,
I am curious to know:

1. How many parallel threads are you running?
2. What is the GPU usage (%)?
3. How long does it take to complete the training?
4. What version of Pytorch are you using?

Did you check https://stackoverflow.com/questions/73267607/how-to-train-model-with-multiple-gpus-in-pytorch ?

**Comment by Sam-WangXZ** [comment]
Thanks a lot, i'll check this link first. See if it works.

**Comment by Sam-WangXZ** [comment]
I'm a rookie and I was just running the demo of ml-agents(platforms to keep balls) ,so don't understand question1
q2 about 20to30percent i guess since I haven't been to lab for a whole week, can't remember well XD
q3 not too long just a few minutes
q4 ML-Agents Release 19 with pytorch==1.12.1

**Comment by Eelam** [comment]
When you look at the 3DBall: 3D Balance Ball example, There are twelve parallel threads running (12 agents): https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/images/balance.png
If you increase the number of agents (e.g. 48),  it will increase the GPU usage. However, 2 x 4090 GPUs are overkill for this example.
Another option is to change the parameters in the YAML file. This depends on your project's complexity.

Let me know GPU usage (%) and training time when you increase the number of agents by a factor of 10 (120 agents).

**Comment by miguelalonsojr** [comment]
Unfortunately, multi-GPU training is not currently supported (adding support for distributed training is TBD). However, the main bottleneck currently is not actually the policy updates in PyTorch. It's the environment rollout/experience buffering from Unity to python, due to gRPC serialization/deserialization. This is a known limitation and will likely be the case until supported for things like shared memory or direct tensor creation in GPU mem by Unity. Both of which are not currently planned.
