### ISSUE TITLE
Imitation learning car racing example

### ISSUE THREAD

**Issue by Xunzhaocunzi** [Unity-Technologies/ml-agents#598]
Hello all, 

I found this imitation learning example of a racing car game on Youtube for Unity ML-Agents 0.3. Does Unity release the source code of this example to the public? 
Thank you!
![capture](https://user-images.githubusercontent.com/32579634/38523871-6be3ac58-3c12-11e8-9237-86dedc13bc84.JPG)

**Comment by mmattar** [comment]
Hi @Xunzhaocunzi - since this demo was based on a real game, we unfortunately cannot release its source code. We provide several sample environments to help you get started, including one for imitation learning (BananaImitation): https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md

**Comment by bartlomiejwolk** [comment]
I believe that the demo was made using Unity Hover Racer example project.

> This example is based on the Hover Racer project developed by Unity using the assets from the game Antigraviator from Cybernetic Walrus. 

https://blogs.unity3d.com/2018/05/24/imitation-learning-in-unity-the-workflow/

**Comment by Xunzhaocunzi** [comment]
Thank you. That's exactly what I want to learn. 

Are there source codes online for public to study?

**Comment by bartlomiejwolk** [comment]
AFAIK source for _Hover Racer_ project with _ML-Agents_ is not available.
