### ISSUE TITLE
In a multi-agent environment, unity freezes when an agent is destroyed or setActive(false)

### ISSUE THREAD

**Issue by yangkang2318** [Unity-Technologies/ml-agents#6006]
I created a 2v2 air combat environment where the program froze when the missile hit a fighter. How can I fix it?
Thanks !

**Comment by Heidar-An** [comment]
it's hard to say when you haven't sent any code? this is obviously a wild shot but I'd guess that you have a reference to one of the fighters in your code somewhere and you're trying to call a method / access a property from it but since the fighter has been destroyed now, it produces an exception (because you're trying to access a game object that hasn't been destroyed). But that's just a wild guess, send your exceptions / snippets of your code here.

**Comment by yangkang2318** [comment]
Thank you for your reply, and I agree with you. I once set the Agent script directly on the fighter gameobject, which caused the program to freeze once the fighter gameobject was destroyed. Now that I set the fighter gameobject as a child of the empty object and set the Agent script on the empty object, then the problem is solved. But why would dynamically destroying and generating agents directly cause the program to crash? #228

**Comment by Heidar-An** [comment]
Hey, I'm not an expert on MLAgents so this might be wrong, but it could be because of this reason : https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Learning-Environment-Design-Agents.md (scroll down to destroying agents).

You need at least on agent at all times, perhaps that's the issue? Otherwise, send the error messages you were getting before and I can try to help.

**Comment by yangkang2318** [comment]
Thank you very much! I have 4 fighter agents, but as soon as one fighter is destroyed, unity just freezes.  And the program don't throw any errors, it just stand still.  However, I solve the problem by referring to #228 . I'm just wondering why the agent script is set directly on the corresponding gameobject, and once an agent is destroyed (please note that there are other living agents in the environment), the program freezes.

**Comment by miguelalonsojr** [comment]
We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
