### ISSUE TITLE
Incorrect model creation if agent is not in the scene at the first frame

### ISSUE THREAD

**Issue by roger-creus** [Unity-Technologies/ml-agents#6027]
**Describe the bug**
Hi,

I am having problems because my agent with the BehaviourParameters component is not by default in the game scene.

First I generate the world and navMesh, then I spawn the agent and programmatically add the BehaviourParamater component and its specifications later. Hence, when I run mlagents-learn, it creates a model with empty observation and action spaces, which causes errors as it returns nulls (e.g. action_model is None).

How can I solve this? Ideally, I would delay the model creation and the entire mlagents-learn pipeline until the agent is spawned in the game.

Thank you!

**Comment by miguelalonsojr** [comment]
How long after the game begins does the agent spawn? Typically, you can train the agent in a training environment to build a policy and then use that policy in the actual game environment. The way MLA is architected is such  that for training, the assumption is that all agents are present in the game. There are workarounds such as stepping the academy manually or having the agent present in the environment but disabled (you can then instead of spawning a new object, just enable it), etc etc. You don't necessarily have to train in the same environment as the final game, as long as the agent is configured the same (i.e. same obs and action space) and the environment is more or less the same in terms of tasks/reward, then you can train the agent in one scene (env) and use it in another, where you can control things like spawning etc. You still might have the situation where you will need to pause the academy from stepping or stepping it manually. This isn't a bug. I'm curious, what's your environment or use case?

**Comment by roger-creus** [comment]
Hi @miguelalonsojr ! Thank you very much for your response. I'm building on top of a large Unity project (originally a game for Steam) where there is a menu from which you start the game. When that option is selected, there is a process of generating the procedural map, which is quite big, the navmesh, spawning the player, and connecting with the servers... I have added MLA on top to spawn an AI player and I am trying to train it in the game environment. However, the player spawning process happens after maybe 2 seconds, and it's where I have programmatically added the BehaviourParameters and DecisionRequester components, but the mlagents-learn pipeline has already defined an empty model at that point. I understand that MLA is not meant to be modified at runtime, and I am now attempting this trick of having a GameObject deactivated in the scene and activating it later. However, it is challenging since many components for the GameObject need to be added after the world is generated...

**Comment by miguelalonsojr** [comment]
I would suggest creating a separate training environment that bypasses much of the manual configuration, e.g. menu selection, etc. The procedural map gen and env setup should happen before the academy script starts to step. You can change the execution order of any script in the project settings: https://docs.unity3d.com/Manual/class-MonoManager.html  The env setup scripts should come first, and then the MLA scripts. You can also extend the timeout of the mlagents-learn command in the training config file under env_settings: https://unity-technologies.github.io/ml-agents/Training-ML-Agents/#environment-settings. You can even spawn agents, you just have to make sure that everything is done before the Agent script is executed for the first time. You can even try to mess with the academy, by adding a script before the MLA scripts that pauses the Academy stepping by setting Academy.AutomaticSteppingEnabled = false. Once things are ready, you can then have another script to enable the academy. You should check out the Unity event lifecycle docs, they may also be helpful in understanding the even execution loop. https://docs.unity3d.com/Manual/ExecutionOrder.html
