### ISSUE TITLE
Graph Scope Could Not Be Found Error?

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#606]
I've trained 4 separate brains in one session just like the Soccer Example(They have two brains here Goalie and Kicker), but when I import the byte file from my training I'm getting an error

The node BRAIN_ML0/action could not be found. Please make sure the graphScope BRAIN_ML0/ is correct

The thing is I've entered the correct scope name, and everything looks fine just like the soccer example but it does not work!!

12 Hours of training and I can't use the brain is very frustrating!

**Comment by mmattar** [comment]
@superjayman, this may be due to a mismatch in the brain name and graph scope (likely because of the use of underscores). At the end of training there is a printed message that includes this information. I recommend training for 5 seconds (by either interrupting training or setting the number of steps to a small number) and checking the printed message.

**Comment by superjayman** [comment]
mmattar you're right the underscores were causing the issue, I think this should be clearly documented somewhere, so what's the rule used to generate the scope names? Can we find this out a different way other than checking the printed message?
