### ISSUE TITLE
Learn.py takes all GPU memory

### ISSUE THREAD

**Issue by r-lipton** [Unity-Technologies/ml-agents#612]
Hello,

When I run a training using `learn.py`, the process allocated all the memory of the GPU.
Is there a way to avoid this, and make it takes only what it needs?

Thanks

**Comment by Hengoo** [comment]
I dont think the problem is with tensorflow or the ml-agents (when i start training it uses about 20 mb vram)

You should check if your game is doing what you think it does. If you have some kind of memory leak you have to remember than the game is played 100 times as fast as normal, so that might amplify the problem.

**Comment by mmattar** [comment]
Hi @r-lipton, is this using one of our sample environments or your own? Generally, as @Hengoo and @MarcoMeter pointed out, we haven't noticed this on our environments.

**Comment by r-lipton** [comment]
It's using my own created environment.
The solution of @Sohojoe worked for me, thanks!

**Comment by awjuliani** [comment]
Hi all. I've made a PR for this, and it will be added to the v0.5 release. https://github.com/Unity-Technologies/ml-agents/pull/1192
