### ISSUE TITLE
3D Ball Game, understanding the vector_observations and actions

### ISSUE THREAD

**Issue by prerna-p** [Unity-Technologies/ml-agents#628]
Hi
I am following the code in the Basics.ipynb Jupyter Notebook.
This line of code:
`print("Agent state looks like: \n{}".format(env_info.vector_observations[0]))`

gives an output:
```
Agent state looks like:
[[ 0.                  0.          0.          0.          0.                   0.
   0.                  0.          0.          0.          0.                   0.
   0.                  0.          0.          0.         -0.04766776  -0.08700117
  -0.54295158          4.          0.11863136  0.          0.                   0.     ]]
```
**I'm confused how to interpret the coordinates from the given 2D array**
What are the X & Z components of the platform's rotation?

According to documentation, 
_The Brain instance used in the 3D Balance Ball example uses the Continuous vector observation space with a State Size of 8. This means that the feature vector containing the agent's observations contains eight elements: the x and z components of the platform's rotation and the x, y, and z components of the ball's relative position and velocity. (The observation values are defined in the agent's CollectObservations() function.)_

Also, the documentation mentions that the vector action space has _one value corresponding to X-rotation, and the other to Z-rotation_ but it does not mention which component these values belong to. Is it the platform?

**Comment by vincentpierre** [comment]
This is the code used by the balance ball to collect observations : 
```csharp
public override void CollectObservations()
    {
        AddVectorObs(gameObject.transform.rotation.z);
        AddVectorObs(gameObject.transform.rotation.x);
        AddVectorObs((ball.transform.position - gameObject.transform.position));
        AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity);
    }
```
This means that you will see 8 values : `rotation.z` `rotation.x` `ball.position.x` `ball.position.y` `ball.position.z` `velocity.x` `velocity.y` `velocity.z` The brain also has number staked vector observations set to 3, this means each agent will have 24 floats. If the observations you printed, the first 16 are 0 because the agent just reset : 
-0.04766776 is the x rotation
-0.08700117 is the z rotation
-0.54295158          4.          0.11863136 are the 3 coordinates of the position
0.          0.                   0. are the initial velocities (the agent just reset so it does not have a velocity yet)
I hope this helps.

**Comment by prerna-p** [comment]
This is extremely helpful, thanks a lot for clarifying.
I'm still confused as to why stacked vector observations are 24? What do the remaining 16 values represent?

**Comment by vincentpierre** [comment]
We stack the observation by time : Imagine o_t is the observation at time t. We feed into the network [o_t-2, o_t-1, o_t] to give the network more information about the state. If o_t contains position then [o_t-1, o_t] can be used to infer the speed information. We try to give more relevant information to the network to make learning easier.
I hope this helps.

**Comment by prerna-p** [comment]
I see. I reduced the number of stacked observations to get a reduced matrix showing only current state, as I wanted. 
Thanks for all the help!
