### ISSUE TITLE
Tensorflow vs Tensorflow-gpu

### ISSUE THREAD

**Issue by ruanrothmann** [Unity-Technologies/ml-agents#633]
Hi,

I've read in previous discussions that unityml is currently not particularly optimised for use with tensorflow-gpu and you will get similar performance with cpu-based tensorflow, is this still the case? (as it simplifies installation by quite a bit).

**Comment by vincentpierre** [comment]
Yes, it is still the case. As of version 0.3, both PPO and BC are not GPU optimized.

**Comment by maystroh** [comment]
@vincentpierre When are you planning to support GPU? I'm wondering because I'm using visual observations which requires GPU capabilities to run the trainings.

**Comment by vincentpierre** [comment]
If you are using Windows, there is a section on how to use the GPU [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md#optional-step-4-gpu-training-using-the-ml-agents-toolkit) if you use Mac or linux, installing `tensorflow-gpu` instead of `tensorflow` will let you use the GPU version of tensorflow.
Our implementation of PPO is not optimized for GPU, I do not think you would get a big performance increase by using the GPU. The image resolution we typically use is 84 x 84 which is not too large (Our implementation of PPO assumes a rather small resolution for the images).
