### ISSUE TITLE
Not saving .bytes file

### ISSUE THREAD

**Issue by Fable67** [Unity-Technologies/ml-agents#663]
Hi guys,
I'm currently training the crawler model. It's taking quite long and I don't know how long, so I wanted to stop the model. The tutorial says it's saving the .bytes file when you press CTRL+C in the terminal after it printed "Saved Model". However, this doesn't happen. It's not saving the .bytes file. Does somebody know what's the problem and if not how long does "Crawler" need to train?

**Comment by vincentpierre** [comment]
If you are using windows, I am not sure the CTRL+C method will work. You can always modify the max_step field of the crawler brain in the `trainer_confic.yaml` file. If you decrease the amount of max steps, the simulation will stop sooner. I hope this helps.

**Comment by MarcoMeter** [comment]
> I am not sure the CTRL+C method will work

I observed that it works sometimes. Just can't tell which circumstances make it fail.

**Comment by mmattar** [comment]
Thanks for pointing this out @Fable67. Closing this issue for now, but please do submit a new one if you face additional issues.

**Comment by xiaomaogy** [comment]
This bug has been fixed with https://github.com/Unity-Technologies/ml-agents/pull/1558. The error message 
```
forrtl: error (200): program aborting due to control-C event
Image PC Routine Line Source
libifcoremd.dll 00007FFDAFF994C4 Unknown Unknown Unknown
KERNELBASE.dll 00007FFDEF127EDD Unknown Unknown Unknown
KERNEL32.DLL 00007FFDF2131FE4 Unknown Unknown Unknown
ntdll.dll 00007FFDF226EFC1 Unknown Unknown Unknown
```

still exist, which is related to this stackoverflow https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception. Our fix get around this error by adding another ctrl-c event handler which saves the model before this error.
