### ISSUE TITLE
Choosing action 

### ISSUE THREAD

**Issue by abhigyanMalviya** [Unity-Technologies/ml-agents#665]
Hello everyone,
I am working on a card based game where the agent will start with a set of cards and he will choose which card to play. And when he plays the correct card he will get reward. 
I am feeding the values the of the card to the brain as the vector observations. Ex: [ 412, 321, 207,120 ] This are four cards the agent have and this goes to brain as vector observations . Now I want the agent to choose one of this card to play. The AgentAction() function will give some values and I have to make it choose one of this cards. 
I also want the agent to decide whether he should play the card or not. If he doesn't have the right card, he should skip his turn. So there will be one more variable for deciding whether he will play a card in this turn or not (if he doesn't have any card he will skip his turn).
Anyone having any tips for doing this.
Thanks!

**Comment by vincentpierre** [comment]
Hi,
I do not think feeding the values of the cards as visual observations will work as the size of the vector observation must be fixed (and I supposed the number of cards is not fixed in this game). Feeding only card values will most likely remove the strategy aspect of the game as it will be impossible for the agent to know what is going on, what cards do and what relations the cards have between each other. I think the cards should be represented as vectors instead of values to be more representative of what "the right card" means. The biggest limitation I see is that the Brain will expect a fixed size for the vector observation.
I hope this helps.

**Comment by MarcoMeter** [comment]
For such kind of games, isn't it common practice to go with RL algorithms, which use a model for planning?

**Comment by abhigyanMalviya** [comment]
@MarcoMeter I am using RL algorithm.
@vincentpierre  thanks for your reply sir.
I know that we have to fix the size of the vector observation. I set the size to 10. The agent can have at max 10 cards in his hand. So if he has only 5 cards then the rest to the values in the vector observation will be zero. Ex: [112, 312, 109, 306, 411, 0, 0, 0, 0, 0]. 
In my game the cards has two attributes. One is it's color and second is it's type. So if the cards value is 412 then, 4 represent it's color and 12 represent it's type. There are 13 types of cards and 4 color cards. 1 represent blue, 2 represent green, 3 represent red and 4 represent red.  The agent will get different rewards when he play same color card and same type card.
Now I know that feeding only the values won't work. So instead of feeding the value of card I will feeds its color and type in the vector observation. Ex: [4,12,1,9,3,10,2,1,].
Will this helps?
I also need help in manipulating the vector action to select one of this cards. Any tips?

**Comment by vincentpierre** [comment]
I think you need to feed one hot encodings of the cards (since the order of the types / colors of the cards does not matter.) Example : Card 0 is color 2 and type 3 would be : `0010` for color and `0001000000000` for type. This would give you a (4 + 13) * 10 vector observation size. Even then I am not sure PPO alone would solve your problem, like @MarcoMeter said, planning seems to be more appropriate in this scenario.
