### ISSUE TITLE
Specify config file

### ISSUE THREAD

**Issue by r-lipton** [Unity-Technologies/ml-agents#704]
Hey

Can we specify the config file to run instead of using always `trainer_config.yaml` when running `python3 learn.py`?
This can be useful for running multiple instances with different parameters

Thanks

**Comment by Hengoo** [comment]
Not really answering your question, but im sure the learning process only reads the condig file once at the beginning. This means you start your first training and then change the config and start your second training. I did this multiple times and im very certain it works

**Comment by r-lipton** [comment]
Yes, I know this is possible, but I want to automate the process, like running one command to launch multiple instances with different configurations. 
One way to do this is to create a script to replace some value in the `trainer_config.yaml` and then launch a training and repeat it until the desired number of instances is reached.
But is there a simpler way ?

**Comment by eshvk** [comment]
@r-lipton 
Couple of things:
1. Modify `learn.py` to make the [`TRAINER_CONFIG_PATH`](https://github.com/Unity-Technologies/ml-agents/blob/master/python/learn.py#L58) a variable that takes a command line argument rather than a constant.

2. Now use your wrapper script to run all the experiments by repeatedly calling `learn.py`. Caveat being that you will have to override the port. You could also very launch a bunch of docker containers (presuming you want to run concurrent experiments that will practically not fit into one machine).

**Comment by mbaske** [comment]
@r-lipton This might be what you're looking for  https://github.com/mbaske/ml-agents-hyperparams

**Comment by r-lipton** [comment]
`ml-agents-hyperparams` is exactly what I am looking for thanks!
