### ISSUE TITLE
Curriculum Learning lessons not changing after passing threshold

### ISSUE THREAD

**Issue by Techno263** [Unity-Technologies/ml-agents#713]
I'm using the ml agents to train an ai to navigate to a spot in a room. My plan was to start with small rooms and increase the size of the room as the ai improved using curriculum learning. I thought i had done everything correctly, but it seems like the ai will not move on the the next lesson after meeting the threshold for the current lesson.

Here is my curriculum json file
```
{
	"measure" : "reward",
	"thresholds" : [0.95, 0.95, 0.95, 0.95, 0.95],
	"min_lesson_length" : 15,
	"signal_smoothing" : true,
	"parameters" :
	{
		"width" : [10, 10, 10, 10, 10, 10],
		"height" : [10, 10, 10, 10, 10, 10],
		"roomNum" : [1, 1, 1, 1, 1, 1],
		"roomMinSize" : [3, 5, 3, 5, 7, 9],
		"roomMaxSize" : [3, 5, 5, 7, 9, 9],
		"minExtraConnections" : [0, 0, 0, 0, 0, 0],
		"maxExtraConnections" : [0, 0, 0, 0, 0, 0]
	}
}
```

And here is a copy of my cumulative reward graph.
![image](https://user-images.githubusercontent.com/23108218/39659546-961c980a-4ff8-11e8-80de-b9b3d0ee8cb7.png)

I don't quite understand why the lesson is not changing. I'm new the machine learning so if it is something obvious I'm sorry. If anyone knows what I'm doing wrong or if it is a bug I would be very grateful. 

Thanks.

**Comment by vincentpierre** [comment]
Hi, The lesson will only change when the academy resets. This means that you either must set the academy to done manually (with Academy.Done) in Academy.Step when some conditions are met OR set Academy max step to some positive value in the inspector of the academy. If each academy episode is too long, it will probably take a long time to change lesson since min_lesson_length is 15 in your scenario. In order to make sure the lessons are changed when the academy is done, I would decrease min_lesson_length, decrease the thresholds and deactivate signal smoothing (just to make sure it works, you can change them back afterwards)

**Comment by Techno263** [comment]
OK. Thank you for the help.
