### ISSUE TITLE
My agent does not learn anything

### ISSUE THREAD

**Issue by leewsimpson** [Unity-Technologies/ml-agents#729]
Hi - I have been trying to solve this myself for quite some time.  I created a very basic 'game', followed all of the examples as best I could and then tried to train it.  Every time I get poor results.  I have tried playing with the parameters, but no luck.  I don't think that my agent task is too complex:

A bouncy object is dropped at random from the top of the screen.  The agent has to move under the object and ideally keep it bouncing.  It gets a reward for bouncing it, and a small penalty for missing.

I use a discrete input - left and right flags. (I have tried continuous too)

For the observations I give the agent the normalised relative position. (I have not tried absolute world space, but may do now that I'm out of options)

Code is here https://github.com/leewsimpson/fruitfight if anyone has time, or wants a quick challenge :)  This project could also serve as another community example if we can get it working!  Thanks in advance.

**Comment by mbaske** [comment]
That sounds like a task which could be hardcoded rather easily. I'm not saying that to discourage you from solving it with RL. But plugging in a heuristic first can sometimes help tracking down flaws in the RL setup. 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Heuristic-Brains.md

**Comment by vincentpierre** [comment]
Hi, 
Did you manage to get the example learning environments to learn?
If yes, the problem might come from the definition of the problem, maybe making the task simpler first would help. It could be that the agent does not get enough information to solve the problem, you can try to visualize the vector observations provided and see if they correspond to what you expect. 
You could also implement the heuristic brain to see if you can get expected behavior this way, it is usually a great way to see if your vector observations are what you expect them to be.
Another issue could be in your reward system, try simplifying the problem to see if complexity is an issue with the reward signal.
I hope this helps.

**Comment by leewsimpson** [comment]
Many thanks for taking the time to respond @mbaske and @vincentpierre.

I did indeed get the heuristic decision to work with some simple code - but it still struggled to learn anything at all when set to external.

Then I simplified the game even more with a much narrower field, as well as removing the bounce.  This did the trick and after 1M iterations, it kinda works.  I expect that I would need to consider a curriculum. 

My hopes and dreams are a bit shattered though, as I was kinda hoping Machine Learning could learn just about anything.
