### ISSUE TITLE
Using two brains is way too slow.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#731]
So I have a sphere which runs after cubes and the cubes try to avoid the sphere.
Both are controlled by two different brains. 

I can see the frames changing in the training but the step summary is too slow even at 10, where as usually the step summary even at 1000 is fast with just one brain.

**Comment by vincentpierre** [comment]
This seems odd, it should be slower but not by an order of magnitude. Are the two brain exactly similar ? It is possible that the two brain did not receive the same training parameters, if one of them uses recurrent, then the training should be slower.
Are you sure the number of steps is slower or is it just the summary freq that is slower ? Python will only print a summary if there was new completed episodes since the last summary. It is possible that python does not report the summaries because no new episode was completed. You should definitely not have summary freq be lower than the buffer size, batch size or time horizon.

**Comment by Aarsh-Singh-Vishen** [comment]
Hi! So I got them to train and saved the output file. But when I try to plug in the graphs and hit play, I get this error:

> UnityAgentsException: Matrix size-incompatible: In[0]: [1,6], In[1]: [3,128]
	 [[Node: dense/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_vector_observation_0_0, dense/kernel/read)]]
CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:334)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)
.

Any ideas?

**Comment by vincentpierre** [comment]
It seems the size of the input and the expected size are different. Make sure the observation size used in training is the same as the one used at inference. Same goes for number of stacked vector observations. Finally, make sure the graph scope is set correctly in the internal brain settings.

**Comment by Aarsh-Singh-Vishen** [comment]
> It seems the size of the input 

Size of which input ?

**Comment by vincentpierre** [comment]
Sorry, the `vector_observation` size.
