### ISSUE TITLE
Masks key in training_buffer

### ISSUE THREAD

**Issue by hejcz** [Unity-Technologies/ml-agents#742]
What is the goal of the `masks` key in `training_buffer` and using it's values in `create_ppo_optimizer` later. It has only `1.0` values appended so it seems unnecessary as `tf.boolean_mask` returns tensor without any changes. Do I miss something?

**Comment by vincentpierre** [comment]
When using RNN, we pad the sequences with 0 data (in order to always feed the same length to the NN). For this reason, when sampling from the buffer, the mask is only one when the data point was added by the trainer. This allows at training time to ignore these data points in the back-propagation.
I hope this helps.

**Comment by hejcz** [comment]
Sure. Thanks for help!
