### ISSUE TITLE
Python API when "Reset on Done" = False

### ISSUE THREAD

**Issue by camigord** [Unity-Technologies/ml-agents#751]
Hello,
I am making some experiments using the 3DBall scenario but I am having some problems when using the python API and setting the agents "Reset on Done" flag to False in the Unity Editor. 

The main idea is that I would like to receive a done flag together with a final observation for any terminated agent whenever I execute `env.step(actions...)`. Something like:

```
env_info = env.step(action)[default_brain]
----
len(env_info.agents):  12
env_info.agents:  [884, 886, 892, 898, 930, 936, 944, 958, 968, 972, 974, 978]
env_info.local_done:  [**True**, False, False, False, False, False, False, False, False, False, False, False]
```

Meaning that after the last step, agent 884 "died".

After this, and using the done flags, I would expect to be able to call `env.step(...)` once more inputting the actions for the remaining 11 agents...

The problem right now is that after calling `env.step()` _sometimes_ I get the environment information corresponding to only **one** single agent, the agent that "died" during this step:

```
env_info = env.step(action)[default_brain]
----
len(env_info.agents):  1
env_info.agents:  [884]
env_info.local_done:  [**True**]
```

I then have to call `env.step(...)` once again with one single action in order to receive a new env_info with the information of the remaining 11 agents...

I wonder if someone else has experienced this issue and I would like to know what is the current logic implemented in Unity for these cases. Is it a bug on the code or am I approaching the problem in thw wrong way?

Thanks

**Comment by vincentpierre** [comment]
When the agent dies, It sends a done flag immediately to Python, it does not wait (like the other 11) that `XXX` fixed updates pass before sending the new observations. This is the expected behavior, in a similar manner, it you had one of the balance ball with a decision frequency set to 1, you would receive an observation for that balance ball alone `XXX` times in a row before receiving all 12 observations at the same time. Agents are not required to send their information at the same time when they do not reset on done.
The reason is mainly because of what can happen in OnAgentDone : We need to make sure that the done flag of a dying agent is sent to python. If the agent is destroyed in OnAgentDone, the done flag must have been sent prior. For this reason, the dying agent does not wait `XXX` fixed updates to send the done flag.
I hope this helps

**Comment by camigord** [comment]
Hi @vincentpierre , thanks a lot for the reply!
So, if I understand correctly, it has to do with the "Decision Frequency" which is assigned to each agent in the Unity's Editor right? If I were to put a decision frequency of 1 for all the agents, I wouldn't be getting this problem right? Given that regardless of whether the agents are done or not, they will reply at the same time...

One last comment, whenever I receive an individual reply from one particular agent (before getting the reply from all the remaining agents), I then have to step the environment by sending a number of actions equivalent to the number of agents which actually replied (in this case 1). But the environment still has 11 agents left... in this case I am not really advancing the environment right? I am basically just querying for the other agents... 

Thanks again for the reply,

**Comment by vincentpierre** [comment]
The balance ball will probably not train properly with a decision frequency of 1, that is because the consequences of each actions do not have a lot of weight.
You are right in your second paragraph, when you receive observations from one agent, the environment expect an action for this agent. The others are not affected since this extra communication is between their decision period of XXX frames. You are advancing the environment by one fixed update and then at the next `env.step` you will be advancing the simulation by `XXX-1` fixed updates instead of having a `env.step` corresponding to `XXX` fixed updates all at once.

**Comment by camigord** [comment]
Cool, I think I get it. Thanks for the help.
