### ISSUE TITLE
The brain Ball3DBrain was set to External mode but Unity was unable to read the arguments passed at launch.

### ISSUE THREAD

**Issue by Robintjhb** [Unity-Technologies/ml-agents#753]
Please help~
I followed the steps above at https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md.

But when using the cmd command line: python learn.py python.exe --train --slow, call build's python.exe application.

The output_log.txt output shows "The brain Ball3DBrain was set to External mode but Unity was unable to read the arguments passed at launch."

Please help me, I have tried many times this problem, thank you.

My unity version is Unity 2018.1.0f2 (64-bit)

<img width="458" alt="1" src="https://user-images.githubusercontent.com/12596145/40031992-c3773376-5824-11e8-8b89-0310be678e92.png">

**Comment by vincentpierre** [comment]
Just to clarify, you are not opening python.exe manually, `learn.py` is opening the executable right ?
There could be a problem naming your executable python.exe, maybe your system is confusing it with the python program, you should rename it `ball` for instance. This could be due to a discrepancy between the python version of ml-agents and the unity version of ml-agents. Make sure both these versions are the same, the simplest way is to pull from `master`. 
I am not sure how to reproduce your error, if you want to debug it, you can try Logging the arguments passed at Launch by modifying line 229 of `ExternalCommunicator.cs`

**Comment by Robintjhb** [comment]
You are right. Thank you very much. After I renamed the application of build to ball.exe, I succeeded in running it. Thank you very much.
