### ISSUE TITLE
Correct input for discrete CollectState.

### ISSUE THREAD

**Issue by liamFerris** [Unity-Technologies/ml-agents#79]
Hi all,

From the docs I have found the following statements about the format of discrete states:

> * return a list of length 1 containing the float equivalent of your state.
> * should be encoded in one-hot fashion (ie 3 -> 0, 0, 1).

I have a couple of questions around this.

I'm unsure whether my discrete input should all be binary, as in 1 or 0. In that case what happens with a leading 0? (e.g. `001` would turn into `1`). Or am I able to put any number in, to represent more complex states? (e.g. 3,9,2 -> 392 or something) My question then would be what happens when I have 10 possibilities for a state, how do I denote 10 in this format? 

Also, what happens when my float equivalent of my state is bigger than the max value of a float? Am I just out of luck?

Many thanks,
Liam

**Comment by awjuliani** [comment]
Hi @liamFerris,

If you have categorical variables which you'd like to add to your state representation, you can use so-called one-hot encoding. This would correspond to adding 0, 0, and 1 using `state.Add()` to represent 3. You should avoid using integers to represent categories, since the neural network interprets them as continuous variables (ie 4 is more than 3) which doesn't make sense if it corresponds to something like enemy type. Hope that makes sense.
