### ISSUE TITLE
CollectObservations() is called per frame even on Demand Decisions

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#792]
I have a agent with "Reset on Done" and "on Demand Decisions" checked.

The Demand Decisions are thus:
timeBetweenDecisionsAtInference = 0.5f

```
public void FixedUpdate()
    {
        WaitTimeInference();
    }

    private void WaitTimeInference()
    {
        if (!IsDone())
        {
            if (!academy.GetIsInference())
            {
                RequestDecision();
            }
            else
            {
                if (timeSinceDecision >= timeBetweenDecisionsAtInference)
                {
                    timeSinceDecision = 0f;
                    RequestDecision();
                }
                else
                {
                    timeSinceDecision += Time.fixedDeltaTime;
                }
            }
        }
    }
```
AgentAction function is correct and it called according to RequestDecision(). But CollectObservations() is called per frame. Is this the correct behavior?

I also noticed that there is no function to set done to false after receiving the event in the AgentOnDone function. The only thing I can do is call the AgentReset function inside AgentOnDone, but this does not change done to false. With this, AgentAction function is not called.

**Comment by icaro56** [comment]
I want to be in control at the time of resetting the agent so I can clear the scene first. I would like to clear the scene with a delay to avoid some bugs that are happening because the agent is reset too fast and some objects are slow to appear.

**Comment by vincentpierre** [comment]
> AgentAction function is correct and it called according to RequestDecision(). But CollectObservations() is called per frame. Is this the correct behavior?

It is not the correct behavior. `CollectObservation` and `AgentAction` should both be called at every decision given the code you posted above. If you had not used On Demand Decision, you should have a `CollectObservation` every `Decision Frequency` and an `AgentAction` at every fixed update. Could you give more information about how you counted the number of collect observations and agent action ? Do you observe this misbehavior at inference or training ?

 > I also noticed that there is no function to set done to false after receiving the event in the AgentOnDone function. The only thing I can do is call the AgentReset function inside AgentOnDone, but this does not change done to false. With this, AgentAction function is not called.

Once an agent is done, you cannot take it back. If `Reset On Done` is checked, the agent resets automatically (and the done flag is reset to false). _(It seems to be the case for you since you said Reset On Done is checked)_. You should not call AgentReset manually at all.

 > I want to be in control at the time of resetting the agent so I can clear the scene first. I would like to clear the scene with a delay to avoid some bugs that are happening because the agent is reset too fast and some objects are slow to appear.

I would recommend having the agent __NOT__ reset on done and destroy it in . `AgentOnDone`. Then, when the scene is fully reset (no matter how long it takes) spawn a new agent in the scene from a prefab and assign it the right brain.
I hope this helps.

**Comment by icaro56** [comment]
> Could you give more information about how you counted the number of collect observations and agent action ? Do you observe this misbehavior at inference or training ?

I put a print inside collectObservation function and the print is called each frame after agent to call Done(). This happens when Reset On Done is not checked.

I observe this misbehavior at inference. I think is agent's broadcast that call the collectObservations

**Comment by icaro56** [comment]
@vincentpierre I have another problem with code. In training phase the agent call the RequestDecision each frame. And in Inference phase, the agent call RequestDecision after a time (0.5 seconds).

When I run the project in Inference phase, the agent takes so long to respond and ends up dying like a idiot. If I call RequestDecision in each frame like in Training phase, then the agent gets smarter, but the but the movement of the game is very fast. I'm doing a project with discrete movement on grid.

**Comment by xiaomaogy** [comment]
@vincentpierre

**Comment by icaro56** [comment]
The old behavior that was presented does not happen anymore.
