### ISSUE TITLE
Simple enemy Ai

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#803]
Hi! I want to make the enemy stay close to the player as long as health> 50, otherwise I want it to retreat and heal but come back close when it has healed?
How do I go about it? 
I've tried but get no where close.  *ANY* guidelines will help :)

This is my rewards function if it helps:
```
if (Vector3.Distance(pos, playerpos) < 5) {
            health -= 1;
            AddReward(-0.1f);
            if (health > 100)
            {
                AddReward(1);
                Done();
            }
            else {
                
                AddReward(-0.1f);
            }

        }
        if (Vector3.Distance(pos, playerpos) < 10&& Vector3.Distance(pos, playerpos) >5)
        {
            if (health < 0)
            {
                health = health;
                AddReward(0.1f);
            }

        }
        if (Vector3.Distance(pos, playerpos) >10)
        {
            if (health < 0)
            {
                health += 1;
                AddReward(0.1f);
            }
            else {
                AddReward(-0.1f);
            }

        }
```
Thanks!

**Comment by Aarsh-Singh-Vishen** [comment]
🏷 help-wanted

**Comment by xiaomaogy** [comment]
This seems something you can code through a hard coded logic.

**Comment by Aarsh-Singh-Vishen** [comment]
But it'd take much less time to code in ml than to hard code it. ML is supposed to make AI coding easier xD

**Comment by Aarsh-Singh-Vishen** [comment]
Any help is appreciated!

**Comment by vincentpierre** [comment]
I looked at the code you sent briefly and I think if the agent does not do what you expect is either because of the way the reward function is defined or because the agent is stuck in a local minima.
I find it strange that you would set the agent to Done when close to the player and with high health.
Here is what I would do : 
 - I would give a small reward to the agent for being close to the player with high health.
 - I would give small penalty to the agent for being close to the player with low health.
 - I would give a strong penalty and set the agent to done when dying.
Assuming that the agent looses health when close to the player, recovers health when far from the player.
You will need to give the agent its health as observation. You will need to normalize it : `AddVectorObs(health/ maxHealth);` or even add a boolean when on low health.

**Comment by awjuliani** [comment]
Hi all,

I am closing this thread due to inactivity. Please feel free to re-open it if desired.
