### ISSUE TITLE
Agent with trained brain doesn't move

### ISSUE THREAD

**Issue by roboserg** [Unity-Technologies/ml-agents#825]
I watched the [tutorial](https://www.youtube.com/watch?v=FcJI6Vc1YHo&index=9&list=PLX2vGYjWbI0R08eWQkO7nQkGiicHAX7IX) for training the PushBlock env and I have two issues:

1. I trained the agent up to 4.8 mean reward. But when using that brain in unity just like shown in the video the agent doesn't move at all ([see picture](https://puu.sh/AxAN5/5303888486.png)) If I use "PushBlock" that was already there, it works. But not with the brain I just trained for 4.8 mean reward.
2. How do I abort and save the model when training? CTRL+C doesn't do anything on windows, and if you press it twice it aborts, but doesn't save the model

I am on win10 x64, python 3.6, Unity 2017.3.1f1
I have TensorFlowSharp installed and enabled - [picture](https://puu.sh/AxBvw/3a41b9a0fd.png)

**Running the same brain with learn.py --load works fine!**

**Comment by xiaomaogy** [comment]
@roboserg 
To answer your first question, did you train the push block agent with everything as it is in the repo, or did you change something? Also did you enable the Area (1) to Area (31) before doing the train? It trains better with more agent so that the brain doesn't get stuck in a local minimum. 

To answer your second question, this is a bug we've fixed in the v0.4, please try pull the master and try again.

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.

**Comment by xiaomaogy** [comment]
This bug has been fixed with https://github.com/Unity-Technologies/ml-agents/pull/1558. The error message 
```
forrtl: error (200): program aborting due to control-C event
Image PC Routine Line Source
libifcoremd.dll 00007FFDAFF994C4 Unknown Unknown Unknown
KERNELBASE.dll 00007FFDEF127EDD Unknown Unknown Unknown
KERNEL32.DLL 00007FFDF2131FE4 Unknown Unknown Unknown
ntdll.dll 00007FFDF226EFC1 Unknown Unknown Unknown
```

still exist, which is related to this stackoverflow https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception. Our fix get around this error by adding another ctrl-c event handler which saves the model before this error.
