### ISSUE TITLE
Possible train in unity?

### ISSUE THREAD

**Issue by diamondcm** [Unity-Technologies/ml-agents#856]
I am new to ML-agent. After reading and practicing the example, it seems like that it could only be trained external with Python. Is it possible to train in unity in the future? I would like to visualize the procesure with Unity. Thanks a lot!

**Comment by xiaomaogy** [comment]
@diamondcm Currently we don't have a way to train only in Unity since we are using tensorflow for our ml library. However with the v0.4 release you will have the ability to train within the Unity editor, with a python process connecting to it. 

Also to visualize the procedure of training with Unity, currently you can monitor the training process through the opened unity executable, and you can visualize the trained model in the inference mode.

**Comment by diamondcm** [comment]
Thanks a lot.

**Comment by alexchacon2341** [comment]
Now that v0.4 is out, is there any documentation for training in Unity? I tried launching learn.py and pressing play with an external brain as the announcement mentions (https://blogs.unity3d.com/2018/06/19/unity-ml-agents-toolkit-v0-4-and-udacity-deep-reinforcement-learning-nanodegree/), but get this error:

https://blogs.unity3d.com/2018/06/19/unity-ml-agents-toolkit-v0-4-and-udacity-deep-reinforcement-learning-nanodegree/

**Comment by xiaomaogy** [comment]
@alexchacon2341 You didn't post the error picture. 

Also for in-editor training (training in Unity) documentation, you can follow this documentation. 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#training-the-brain-with-reinforcement-learning

**Comment by alexchacon2341** [comment]
Sorry, this was another response I sent via email and it looks like my
upload was not copied properly.

No matter, though! I followed the instructions you sent from the
documentation and everything worked brilliantly! Thanks so much!

Best,
Alex

On Fri, Jun 22, 2018 at 2:30 PM, Vincent(Yuan) Gao <notifications@github.com
