### ISSUE TITLE
Frame-Stacking in the Environment

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#952]
Hi - As far as I can tell, frame-stacking for visual observations isn't supported yet. My guess is that regarding bandwidth, it would make sense to buffer frames on the python end. However, I made an attemt to implement stacking in the environment, so I'd have some control over delay times and additional processing like frame subtraction. If someone wants to give it a try, code and example environment are at https://github.com/mbaske/ml-agents-frame-stacking

**Comment by awjuliani** [comment]
Hi @mbaske,

Thanks for sharing this. We've actually had it on our roadmap to implement this at some point, but it had taken the back-burner due to our current focus on vector observations-based environments. There is also the issue around the best way to implement this in a way that is efficient. If you were interested, it would be great to potentially integrate the work you've done here into the main repository. Would you be open to making a PR, so we could review the code and discuss more?

**Comment by eshvk** [comment]
Thanks for this discussion, we are going to close this issue because it is merged!
