### ISSUE TITLE
Optimizing my curriculum learning training

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#954]
Hello,
I managed to get the curriculum learning training working with my project.
In each lesson the agent will have to reach the flag to complete the level and receive a reward (+1), but if he falls on the spikes he will receive a penalty (-0.25).
In the first lesson everything goes as expected and the agent manages to reach the goal consistently fairly quickly, but once he moves on to the second lesson he gets stuck in a local minimum and can no longer consistently reach the target. In the second lesson he only receive rewards by succesfully landing in the first platform (which he learned in the first lesson and gives a reward of +0.6) and reaching the flag (+1).
I have tried playing around with the beta value in the trainer_config.yaml file but it didn't seem to help much.
Do you have any suggestions on how i could improve my curriculum training?
https://drive.google.com/open?id=1msqvAvxyf6KwEtd5dgN-WKQ5Zyol-VyM

**Comment by traveltrousers** [comment]
Make more platforms and slowly remove them each lesson...

**Comment by jpax1996** [comment]
@traveltrousers  i've tried that but it didn't change much

**Comment by scotthovestadt** [comment]
@jpax1996  Here's what has worked for me:

1- Don't give a penalty for falling on spikes-- at least at first. Just call `done()`.

2- Give a reward based on the time it took the agent to reach the flag. This will encourage them to be quick without punishment. I found personally a formula like this worked for me:
`AddReward(Mathf.Min(2 * Mathf.Abs(1f - ((float) GetStepCount() / (float) agentParameters.maxStep)), 1f));`

The point of that formula is that it's not completely linear. The agent can get the full reward if he completes in a reasonable time, but the reward below that then scales down. I found that a strategy like this is necessary to avoid the agents over-optimizing for things they cannot control (like the randomly generated goal being impossible to reach in the same amount of time every round).

I've debated rounding it to the nearest decimal but haven't tried that yet.

3- `use_curiosity` will increase training time (sometimes massively) but I found that it helps avoid the agent getting stuck in the local minimum. With this setting sometimes it will be a long while before your agent even manages to reach the flag once, but it's because it is rewarding itself for figuring out the environment. Once it figures the environment out it will no longer be able to generate internal reward and it'll find your reward and ramp up.

**Comment by jpax1996** [comment]
@scotthovestadt  thanks for the response, i'll try out your advices, how can i set use_curisity to true?

**Comment by scotthovestadt** [comment]
@jpax1996 Take a look at the Pyramid example, which uses it. Let me know how it works for you!

**Comment by mmattar** [comment]
Thanks @scotthovestadt. Let us know if this resolves your issue @jpax1996 or if you have any additional follow-ups.

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if you continue facing issues.
