### ISSUE TITLE
Agent fails to learn in simple environment 

### ISSUE THREAD

**Issue by KarolloS** [Unity-Technologies/ml-agents#984]
Hello!

I created quite simple environment with a device (simple model of laparoscope) which is supposed to navigate to the sphere (target), grab it and move it to the final position (goal). I added some bounding box in which the tip of my device can move, if it hits the wall simulation ends. 

I’m using continuous observation and actions. In case of grasping I assign true (grasped) if the continuous value is larger than zero and false (not grasping) when this value is smaller than zero. My observation are as follow:
```
AddVectorObs(fulcrum.transform.localRotation);
AddVectorObs(scope.transform.localPosition.z);

Vector3 relGoalTipPos = goal.position - tip.transform.position;
AddVectorObs(relGoalTipPos);

Vector3 relTargetTipPos = target.position - tip.transform.position;
AddVectorObs(relTargetTipPos);

Vector3 relTargetGoalPos = target.position - goal.position;
AddVectorObs(relTargetGoalPos);

AddVectorObs(isGrasping ? 1f : 0f);
```

At the beginning I used only one big reward at the end (target moved to the goal position) plus small negative reward per simulation steps. I didn’t get any interesting results so I introduced some intermediate rewards, for example small positive one when the device is holding the target -again, no interesting results. I tried to use curiosity as well. 

The problem doesn’t seem to be very complicated but I’m still not able to teach my agent how to perform this task. Maybe my approach is wrong at some point?  – I would appreciate any help.

Ps.: If the bonding box is very small and the position of the target is very close to the goal I was able to get at least some results. However, I wasn’t able to scale my solution to bigger problems – it looks like the agent learned to do some circular movement through whole space and try to grab something on its way. It seems that it is not using observations at all.

**Comment by scotthovestadt** [comment]
Hi @KarolloS,

I encountered exactly the same issues when working on [my first project](https://www.youtube.com/watch?v=pLofPJNPFVw&feature=youtu.be) with Unity neural networks. I had trouble initially because the agent really needs to learn how to even move since the steering wheel, throttle, etc aren't as simple as just 'move up'.

Here are a few general tips from my experience:
- **Normalize. Everything.**
- Use curriculum learning. Start extremely simple and ramp up. Just make sure that the agent cannot advance until it learns to use observations (use `reward` and set it to 80% success rate or so).
- Use rewards sparingly and punishments even more so. In the end I settled on only a single reward for reaching the target. Instead of punishment, early levels just end when the vehicle goes out of bounds.
- Randomize everything as much as possible.
- If your AI isn't making progress (slower linear progress OK), it's likely a failure of the course and will not improve with long training times.

I'd need to see what your continuous actions are to provide more assist.

Generally speaking you just need to scale it down to what is REALLY the simplest problem and then go up from there. Your initial idea of what the simplest problem is won't even be close :)

**Comment by KarolloS** [comment]
Thanks @scotthovestadt for quick answer and for your tips!

A few comments to your suggestions:
-  My observations are supposed to be normalised on python side (in ppo), my actions are clamped to the range (-1, 1) and my rewards are also between -1 and 1.
- Before I try curriculum learning I wanted to get some result in the simplest case - in my problem this means very small bounding box and target close to the goal.  I tried to teach my agent how to grab the target first and then cary on with the problem where he needed to move the target to the goal position but it didn't work. He learned how to grab very quickly but when I moved to the further problem it seems that he "forgot" everything about grabbing.
- To avoid dense rewards I can try using only one intermediate reward - at the moment of grabbing and I'll finish my simulation when he drops it.
- Initial position of my sphere (target) and goal are always random (within my bounding box of course).


You asked about my actions:  

You can see my device in the picture below - it can be rotated (X, Y), pivot inside the sphere and whole device can be inserted (Z) as well.
![lap](https://user-images.githubusercontent.com/25109601/42885143-1f2ad056-8a98-11e8-8f3a-8d6114c979c9.jpg)

My actions in the code:
```
float rotX = Mathf.Clamp(act[0], -1f, 1f);
float rotY = Mathf.Clamp(act[1], -1f, 1f);

float insertion = Mathf.Clamp(act[2], -1f, 1f) * 0.1f;
bool graspActionVal = Mathf.Clamp(act[3], -1f, 1f) > 0f;

fulcrum.transform.Rotate(new Vector3(rotX, rotY, 0), Space.Self);
scope.transform.Translate(new Vector3(0, 0, insertion), Space.Self);

// add movement limits: rotation (-45, 45), insertion (-3, 3)
Vector3 fulcRot = fulcrum.transform.localRotation.eulerAngles;
Vector3 insVec = scope.transform.localPosition;

fulcRot.x = MathUtils.ClampAngle(fulcRot.x, rotLimit[0], rotLimit[1]);
fulcRot.y = MathUtils.ClampAngle(fulcRot.y, rotLimit[2], rotLimit[3]);
fulcRot.z = 0f;
fulcrum.transform.localRotation = Quaternion.Euler(fulcRot);

insVec.z = Mathf.Clamp(insVec.z, insLimit[0], insLimit[1]);
scope.transform.localPosition = insVec;
```

**Comment by scotthovestadt** [comment]
There's a sample project that's somewhat similar to yours. Have you seen it?
https://www.youtube.com/watch?v=2N9EoF6pQyE&feature=youtu.be

I would definitely start with just having to learn to consistently "pick up" the target and then move onto the next stage after that's been fully trained. Make sure that you randomize the agent's position and the object's rotation every time so it has to learn to use observations to find it within your time limit.

I would also manually normalize everything. One exercise that helped me was trying to navigate my agent while using only observations. If I couldn't (slowly...) manage to get my agent to the goal using only observations I knew I was missing something.

Here are some things that jump out to me:
- You're limiting rotation using Euler limits but the rotation you pass (Quaternion) looks normalized (range of 0-1 like all Q angles) but actually isn't. I would definitely normalize any rotation values you pass to 0/1 as the min max achievable by the agent. I have not had good luck with the auto normalize feature.
- Instead of passing relative positions I have personally had better luck with normalized directions + distance (normalized 1 to 0 over X distance, X is always the same).

**Comment by KarolloS** [comment]
Thanks @scotthovestadt  for your help. I combined some of your tips and it seems that it is working right now! I'm moving to some more complicated problems!
